### ISSUE TITLE
claimbot has no unclaim feature?

### ISSUE THREAD

**Issue by ctlewitt** [Growstuff/growstuff#1005]
I couldn't find an "unclaim" command in the claim-bot documentation.  
https://github.com/Growstuff/growstuff/wiki/Our-bots
Is this a feature that should be implemented, or is it just undocumented?  Or are there other ways to mark an issue as unclaimed?

**Comment by pozorvlak** [comment]
It [looks like a missing feature to me](https://github.com/afuna/ghi-assist/blob/master/ghi_assist/api.py). We don't control that project, but it sounds like a useful feature and I bet they'd welcome it if you wrote it. Failing that, we could fork it and run the forked version of the bot.

The current "unclaim" workflow is "post a comment asking one of the admins (me, @cesy, @maco, @CloCkWeRX) to remove you from the issue". Do you have an issue in mind?

**Comment by pozorvlak** [comment]
Testing mentions of @Growstuff/committers, apologies to my fellow committers for the spam...

**Comment by pozorvlak** [comment]
BTW, I just gave all the members of @Growstuff/committers admin privileges for this repo. With great power comes great responsibility.

**Comment by ctlewitt** [comment]
Thanks!  I'll see what I can do about the bot feature.  

There wasn't a particular issue I wanted to be removed from.  I just noticed as I was poking around and trying to get to know the project.  I'm pretty new to open source.

**Comment by maco** [comment]
We only just got claim bot like a week ago, so we're learning too.

**Comment by ctlewitt** [comment]
Cool!  I'll let you know what I find.  (In the meantime, the claim bot is pretty sure you've got this one.  ;-)  )

**Comment by maco** [comment]
Doh!

**Comment by Br3nda** [comment]
Is claimbot still running?
Homu bot seems to be offline.

**Comment by Br3nda** [comment]
closing because claimbot seems to be dead
