### ISSUE TITLE
Add "fork me on github" banner

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#1014]
@pozorvlak hmm alignment's a little odd there...think it's ok?

(note to self: this involved `z-index: 2000` on the banner image to get it over the nav bar)

<img width="400" alt="screen shot 2016-06-22 at 12 07 04 pm" src="https://cloud.githubusercontent.com/assets/401264/16274044/f32220ec-3871-11e6-85ea-0290b17b92c0.png">

**Comment by pozorvlak** [comment]
Possible CSS-only solution to the overlap problem: https://codepo8.github.io/css-fork-on-github-ribbon/

**Comment by CloCkWeRX** [comment]
I think this turned into a wontfix after trying both approaches in #1022 - we do have the ribbon one the blog and a footer link
