### ISSUE TITLE
Members page "recent" view has caching issue

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#1015]
I know martelvonc signed up on June 17, which was 5 days ago. Tess did indeed sign up about an hour ago.

<img width="1171" alt="screen shot 2016-06-22 at 2 26 53 pm" src="https://cloud.githubusercontent.com/assets/401264/16278574/74446a6e-3885-11e6-8da0-43a3df2f6609.png">

**Comment by Br3nda** [comment]
fixed
