### ISSUE TITLE
If a crop doesn't have a photo but a harvest does, use that

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1017]
Very similar to #997 
 * Find a crop with no photo (grapefruit on staging?)
 * Add a photo of your harvest of it

Expected:
 * The crop gets the harvest photo

Actual:
 * No photo unless you also attach it to the crop

**Comment by SaiVardhan** [comment]
can you provide the steps to reproduce it.

**Comment by maco** [comment]
Find a crop in the database that shows the "there's no photo available"
graphic.

Create a harvest of that crop.

Add a photo to that harvest.

Look at the all crops page. That crop should have the photo you attached to
its harvest displayed instead of the "no image available" graphic.

**Comment by CloCkWeRX** [comment]
Should have been sorted in #1021
