### ISSUE TITLE
Add links to OpenFarm growing guides?

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1038]
Was looking at https://github.com/FarmBot/ and realised they used https://openfarm.cc/ for growing guides.

There's a lot of overlap and I think some of the openfarm folks like @roryaronson have already come across us.

Similar to what we've done with Gardenate, we should deep link to relevant guides in OpenFarm.

http://www.growstuff.org/crops/tomato
- Gardenate guide: http://www.gardenate.com/plant/tomato
- Openfarm equiv: https://openfarm.cc/en/crops/tomato

At a deeper level, https://github.com/openfarmcc/OpenFarm/blob/master/docs/api_docs.md exists and would make a great deal of sense to pull attributes we don't model from their API; or otherwise integrate data where we are missing it when managing crops (no crop picture but OpenFarm has one? set URI, add appropriate attribution)

**Comment by cesy** [comment]
Sounds good to me.

**Comment by pozorvlak** [comment]
Definitely +1 to adding deep links; pulling data from their API would be
great (assuming license compatibility), but would obviously be more work.

**Comment by roryaronson** [comment]
+1! FYI, all of our data (photos too) are in the public domain. Let us know if you begin using the API or have any troubles. We're responsive on github or you can pop into our slack channel at slack.openfarm.cc
