### ISSUE TITLE
Failed to open TCP connection to localhost:9200

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1047]
when i run the specs i get 100+ tests failing with  Failed to open TCP connection to localhost:9200
Is this for elastic search? the comments in application.yml.example lead me to thing this isn't needed to run the app or the tests.

I have config/application.yml, with GROWSTUFF_ELASTICSEARCH: "false"

Is it supposed to be possible to run the specs without elastic search?
Are there instructions somewhere on setting up elastic search for dev,test,ci?

---
p.s. typed with a small child pulling on my arm. forgive typoss.

**Comment by pozorvlak** [comment]
Hi @Br3nda! That does look like an ElasticSearch error, and yes, it should be possible to run the test suite (excluding ElasticSearch-specific tests) without having ElasticSearch running - we do it all the time in TravisCI. But I'm getting this problem locally too - I'll investigate.
