### ISSUE TITLE
growstuff.org/places does not show map tiles

### ISSUE THREAD

**Issue by thoka** [Growstuff/growstuff#1051]
http://www.growstuff.org/places currently show now map tiles as mapbox seems to refuse tile requests at the moment:

http://a.tiles.mapbox.com/v4/growstuff.i3n2c4ie/2/3/2.png?access_token=%20pk.eyJ1IjoiZ3Jvd3N0dWZmIiwiYSI6IkdxMkx4alUifQ.n0igaBsw97s14zMa0lwKCA 

Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by CloCkWeRX** [comment]
Fixed in #1043 ; just not deployed yet
