### ISSUE TITLE
Eventually get to rails 5

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1054]
I think https://github.com/comfy/comfortable-mexican-sofa/issues/728 was one of the key blockers, and that may have just turned solved - it would be good to understand what else blocks us.

**Comment by Br3nda** [comment]
Getting closer to making this possible...

**Comment by CloCkWeRX** [comment]
Next one to knock off:
```
quiet_assets was resolved to 1.1.0, which depends on
      railties (< 5.0, >= 3.1)
```

**Comment by CloCkWeRX** [comment]
Just pushed https://github.com/CloCkWeRX/growstuff/tree/rails5 - wasn't 100% on the configuration changes that it generated.

**Comment by CloCkWeRX** [comment]
So, going to park it for the moment - bunch of stuff whinging for no good reason. Feel free to fork from my branch and chip away at it.

**Comment by cesy** [comment]
Anyone up for having another go at some of the bits of this?

**Comment by Br3nda** [comment]
Progress made on #1211
