### ISSUE TITLE
Planting edit doesn't propogate to photos

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1057]
I planted yams. Because they are delicious!
I uploaded lots of photos of my yams to growstuff.org.  So far so good.

I then learned, that what I call yams, are not what most of the english speaking world call yams. I am growing New Zealand yams, an entirely different plant. Here in New Zealand we just call those "yams".,

I corrected my planting to "New Zealand yams", but the photos remain attached to "yams"
http://www.growstuff.org/plantings/shiny-vege-gardens-yam
http://www.growstuff.org/crops/search?utf8=%E2%9C%93&term=yam

I think, whenever a planting is changed to a different plant, the associated photos should be change plant too.

**Comment by Br3nda** [comment]
Correction! Only the search results have the wrong photos on yams
http://www.growstuff.org/crops/search?utf8=%E2%9C%93&term=yam

**Comment by maco** [comment]
That might just be caching.

**Comment by Br3nda** [comment]
It's been caching for several weeks then.

**Comment by maco** [comment]
We've been known to have the front page say "1 minute ago" 9 months later,
so not outside the realm of possibility (which would also be a bug). Are
you able to confirm in the Rails console that it's not being moved to the
other crop?
