### ISSUE TITLE
proposal: turn on review requirements

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1089]
Github now  supports requiring a number of reviews and checks passing before making the merge button green.

It looks like this on my other projects:
![github](https://cloud.githubusercontent.com/assets/12266/20695441/cf1e82a0-b650-11e6-89b0-a0b4e6c69114.png)

Let's turn it on for growstuff. A PR could require 2 reviews from commiters, and for Travis to pass. 

Essentially it makes the button look a bit scary if the criteria isn't met, and makes the button a comforting green if it's good.

**Comment by maco** [comment]
:+1: to this from me.

**Comment by CloCkWeRX** [comment]
I'm for leaving it as optional - its useful to add feedback in a structured way; but I don't think we should rigidly enforce it.
Its rare that we push without review and we haven't done so in a way that Breaks Everything

**Comment by maco** [comment]
Well, I don't know about requiring 2 reviewers since sometimes some of us
wander off for a week or whatever. At my work the way we're using it is
that approve/change indicates whether the reviewer is saying "this is a
nitpick and not totally necessary, but..." or "this has to change."

**Comment by cesy** [comment]
Yeah, we should set it to one reviewer as that's what we currently require,
but let's turn it on and play with it.

**Comment by pozorvlak** [comment]
I'm OK with trying this out, but currently our problem is that we're not
fast enough at reviewing and merging things, and AFAICT this has the
potential to make that problem worse. So, let's try it for a bit, and turn
it off again if it's not working.

**Comment by Br3nda** [comment]
This wouldn't enforce. You can still press the button. The change only makes the button scary looking when nobody has reviewed or tests have failed.

**Comment by Br3nda** [comment]
I've found this can make it faster. We don't have to keep checking and re-reading if the pr is reviewed as good. It's down there ar the bottom.

**Comment by Br3nda** [comment]
I have turned this on. I also ticked that the branch should be up-to-date with the latest changes in the branch you propose merge into. 

![image](https://cloud.githubusercontent.com/assets/12266/20728709/d7693fac-b6e3-11e6-917c-0b02bf9c6beb.png)

**Comment by maco** [comment]
Thanks. I noticed the out of date warning. I tried to find the checkbox to
do this proposal and couldn't. Where'd ya find the setting?

**Comment by Br3nda** [comment]
It's under "protect  branches". I turned it on for dev and master
