### ISSUE TITLE
Deployment happens twice per merge

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#1099]
Both the ElasticSearch and non-ElasticSearch builds deploy on success; we should only deploy once (probably from the ElasticSearch build)?

**Comment by Br3nda** [comment]
Are you heroku pipelines to deploy?

**Comment by pozorvlak** [comment]
No, we're using [Travis CI's deployment hook](https://docs.travis-ci.com/user/deployment/heroku/).

**Comment by Br3nda** [comment]
Okay. Maybe pipelines will help. I've used in @WhareHauora
