### ISSUE TITLE
Weird layout on garden photos

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#1100]
On a wide browser window, @Br3nda's garden page looks like this:

![screenshot from 2016-11-30 15-49-51](https://cloud.githubusercontent.com/assets/225991/20759449/e225c682-b714-11e6-9188-0f709d78439a.png)

The photo of the garden overlaps the "lavender" card awkwardly.

On a narrow window, it looks fine:

![screenshot from 2016-11-30 15-50-12](https://cloud.githubusercontent.com/assets/225991/20759478/ec12bb32-b714-11e6-9a68-2b02ba1ddac7.png)

I'm using Firefox 49.0 on Fedora 23.

**Comment by CloCkWeRX** [comment]
Same as #939 but this is more detailed, so keeping this one.

**Comment by Br3nda** [comment]
Fixed a whole ago.
