### ISSUE TITLE
cannot connect flickr account

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#1106]
This looks like a side effect of moving from /cms/foo URLs to /foo URLs

<img width="489" alt="screen shot 2016-12-01 at 12 37 01 pm" src="https://cloud.githubusercontent.com/assets/401264/20804944/e2a001c8-b7c2-11e6-8d40-e73653c8ecef.png">

**Comment by maco** [comment]
Using /members/auth/flickr instead sends you to Flickr properly, but then the callback lands at /members/auth/flickr/callback which doesn't exist

**Comment by cesy** [comment]
So should we just updating our routes.rb to point /auth to the right place?

**Comment by maco** [comment]
I think so I'm just not sure how

**Comment by Br3nda** [comment]
I had a go at this, and noticed this error
```W, [2017-02-05T12:09:49.405681 #4929]  WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::Strategy::Options#display defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```

**Comment by Br3nda** [comment]
I've had a couple goes at this. I'm not sure it has anything to do with the cms. Removing the cms doesn't help.

**Comment by maco** [comment]
The cms is just catching any route that's not already defined, so I guess
that makes sense. It used to only catch /cms/* rather than /* so I was
thinking they're related.

**Comment by Br3nda** [comment]
Works in release 14
broken in release 15.

**Comment by Br3nda** [comment]
did some testing, and i think connecting a flickr account was broken in this commit
c60609d50708cb890be54f2bdcf7eca2e7ea80b3

**Comment by maco** [comment]
huh. I imagine it's one of the gem updates, but... wow.

**Comment by Br3nda** [comment]
possibly the rails update. But there's adding of facebook auth about the same time too.
