### ISSUE TITLE
crop#create dies in sys.exit

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1128]
on growstuff.org, and in git dev branch:

at line 140 of crops_controller:
```
          Role.crop_wranglers.each do |w|
            Notifier.new_crop_request(w, @crop).deliver_later!
          end
```
`deliver_later!` doesn't return. it exits the ruby process. the web container spits a http 500.
I imagine only one crop wrangler will be getting the emails right now.
This may have come in at a gem upgrade recently.

p.s. would love someone to approve "boysenberry".

**Comment by CloCkWeRX** [comment]
We can maybe swap to ```deliver_now!``` to rule out sidekiq/activejob/etc configuration without much effort.  If its sidekiq, its probably fe137a11bb363d6332b5c55e603bb870930e666a
