### ISSUE TITLE
Security issue contact

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1134]
Can we add a security contact details to the README? So if anyone finds an authorization bypass or data breach, it can be reported there and not the issue queue.

**Comment by maco** [comment]
good call

**Comment by pozorvlak** [comment]
maintainers@?

**Comment by cesy** [comment]
Yeah.

**Comment by cesy** [comment]
This should be a quick change - anyone up for it?

**Comment by AncyentMariner** [comment]
@cesy I'd like to pick up this issue, if it's still relevant. Do you know whose contact information should be added to the README? I assume it will be some kind of admin@email.com kind of format. Any ideas of specifics?

**Comment by cesy** [comment]
maintainers@growstuff.org, yes. Thanks!
