### ISSUE TITLE
What to do when a photo is removed from flickr

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1162]
for example, this is the current photo for "mint", and it's a broken image
http://www.growstuff.org/photos/183

**Comment by CloCkWeRX** [comment]
Manually deleting works for me.
Flickr has reduced a lot of limits for photos and sends out "we're going to delete your photostream" emails a bunch.

**Comment by CloCkWeRX** [comment]
Closing in favor of #1949 and manual deletion for now
