### ISSUE TITLE
javascript feature specs don't work

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1163]
about a month ago, many feature specs stopped passing for me, on my laptops and my desktop pc.
They all fail in javascript look ups of fields, eg:
```
     Failure/Error: fill_in "sci_name[2]", with: "Jasminum sambac 2"
     Capybara::ElementNotFound:
       Unable to find field "sci_name[2]"

       expected to find css "li" with text /tomato/i 5 times, found 6 matches: "magic bean Roma tomato 1 Roma tomato 2 Roma tomato 3 Roma tomato 4 Roma tomato child 1", "Roma tomato 1", "Roma tomato 2", "Roma tomato 3", "Roma tomato 4 Roma tomato child 1", "Roma tomato child 1"   

     Failure/Error: expect(page).to_not have_content alternate_eggplant.name
       expected not to find text "aubergine" in "Skip navigation menu Toggle Navigation Search crop database: Crops Browse Crops Seeds Plantings Harvests Community Community Map Browse Members Posts Forums Support Growstuff wrangler11 Profile Gardens Plantings Harvest Seeds Posts Account Inbox Crop Wrangling Sign out aubergine Alternate name: aubergine Crop: eggplant Edit | Back"
```

I've been relying on travis while trying to work this out - i've poked at upgrading capybara and poltergeist.

Anyone else seeing this? What causes it? Any help appreciated.

**Comment by pozorvlak** [comment]
That was about the time I turned off lazy asset compilation in the test environment: 18415489. Try running `rake assets:precompile` before running the tests?

**Comment by Br3nda** [comment]
tried that.. still many dozens of failed feature specs

**Comment by Br3nda** [comment]
oooo... wait yes! it works!

thank you for solving the mystery.

**Comment by pozorvlak** [comment]
It looks like lazy asset compilation was (one of the things) causing #901, so we probably don't want to turn it on again. Hmmm. We could make `assets:precompile` a dependency of the test-running Rake task?
