### ISSUE TITLE
event model

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1165]
I propose an "events" model, belonging to a planting (and maybe other models)
examples include: Diseases noticed, treated. Pests culled. pruned. fertilzer etc.

This can be presented as a timeline for each planting.

**Comment by Br3nda** [comment]
alternatively we can make disease, pested, fertilizing models.. but there will be many

**Comment by CloCkWeRX** [comment]
I don't mind the idea - we sort of already have it with the notion of 'plantings happen over time in gardens' and 'harvests happen to plantings'.

I think we have some existing tickets around 'know the rainfall' (#863) or similar - having your planting updated with a weather history seems like it would be an interesting thing to know; so you could compare big harvest one year vs smaller harvest another over time.

**Comment by Br3nda** [comment]
Right now the apple tree has apples, but i dunno if i should pick now or wait. knowing what happened last year will help

I'd like events like 
* The apple tree flowered
* fruit appeared
* I picked an apple but it didn't taste great
* i picked an apple and it was perfect"

As for weather history --- WOW YES. I'm in a high wind zone, so knowing when the storms happen, especially building up a pattern of the seasons, will be very useful.

Then i'll learn when is the optimum time to do things.

**Comment by pozorvlak** [comment]
Sounds like a plan, though we'll probably have to think about how events
interact with harvests.

**Comment by CloCkWeRX** [comment]
I have started a (limited) version of this with "weather observation"

I feel an event shouldn't just be a generic table of many, many types; so much as we make a bunch of little, specific tables and models that all adhere to a type like https://schema.org/Event (tldr - "occurred_at") and can be treated the same; but also have a lot of their own attributes.

**Comment by CloCkWeRX** [comment]
Okay, weather observations is still around but I did a generic events in #3646
