### ISSUE TITLE
"add new garden" on other member's page

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1167]
This seems wrong -- only because the "add new garden" is below a list of someone else's gardens.

![image](https://cloud.githubusercontent.com/assets/12266/22221299/40699f48-e217-11e6-804d-da84495b40a7.png)

**Comment by Br3nda** [comment]
i think this button should only show when on your own pages. 
Sound right?

**Comment by maco** [comment]
Agreed

**Comment by Thomascountz** [comment]
Hey all, is this the `./gardens/show.html.haml` view?  I'd love to take a look at this and see if I can help!

**Comment by Br3nda** [comment]
Yes please @Thomascountz ! it is indeed gardens#show.
