### ISSUE TITLE
The tests fail if i run them at lunch time

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1182]
The code isn't handling timezones correctly. I'm in UTC+13. If I run the specs between 12pm and 1pm, I get failures like this:

  1) PlantingsController GET new sets the date of the planting to today
     Failure/Error: assigns(:planting).planted_at.should == Date.today
     
       expected: February 04, 2017
            got: February 03, 2017 (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -February 04, 2017
       +February 03, 2017

**Comment by CloCkWeRX** [comment]
Expectation seems wrong, the controller is doing:
```'planted_at' => Time.zone.today```
