### ISSUE TITLE
Remove references to Discourse

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#1193]
The forum at http://talk.growstuff.org is pretty much dead - we're communicating through GitHub Issues. However, it's still costing us money.

 - [ ] Preserve any useful threads by transferring them to the wiki ([this one](http://talk.growstuff.org/t/fatal-role-postgres-does-not-exist/216/3) looked useful; I didn't notice any more on a quick pass)
 - [x] Remove [references to talk.growstuff.org](https://github.com/Growstuff/growstuff/search?utf8=%E2%9C%93&q=talk.growstuff.org) from the code
 - [ ] Shut down Discourse.

**Comment by cesy** [comment]
Is anyone up for this? We've just had another monthly payment go out.

**Comment by Br3nda** [comment]
Can you do a data export from discourse?

**Comment by cesy** [comment]
Yeah, looks like they do a backup you can download. I'll do that now and then cancel, then?

**Comment by Br3nda** [comment]
@cesy Sounds good.

**Comment by Br3nda** [comment]
done in #1275
