### ISSUE TITLE
500 error when sending message

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#1197]
After you hit send, you get an error screen. Logs suggest to look at `/app/app/controllers/
notifications_controller.rb:  10:in `index'`

Also:

```
Error message
ActionView::Template::Error: No route matches {:action=>"show", :controller=>"members", :id=>nil} missing required keys: [:id]

```

**Comment by maco** [comment]
Browser being weird...can't edit post...

I think `current_member` is maybe not set

**Comment by Br3nda** [comment]
seems to work in dev for me -- is this on production?

**Comment by Br3nda** [comment]
i sent you a message on growstuff.org, didn't get an error.

**Comment by maco** [comment]
It was while trying to send you one that I got an error. Hmmm

**Comment by Br3nda** [comment]
@maco is this still happening? Is there a particular message content that causes this, or all messages?

**Comment by maco** [comment]
Still happening. 500 when I try to view my inbox too.

**Comment by maco** [comment]
And I tried just putting "this is a test" ... no links to crops or urls or
anything... and yeah, it failed. so i guess all messages
