### ISSUE TITLE
can we turn off coveralls comments?

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1232]
It makes notifications, and noise in my activity thread -- and i think "yay someone commented" only to find it's coveralls again.

I've seen it configured as a status check

We could also use codeclimate's coverage, and remove coveralls entirely.

**Comment by cesy** [comment]
I'm fine with turning it from comments to status.

**Comment by CloCkWeRX** [comment]
+1 to making it quieter

**Comment by pozorvlak** [comment]
+1 to making it quieter. I think a status check would also be more useful
than what we currently have.

**Comment by jcaudle** [comment]
From a historical point, Coveralls couldn't be configured as a status check when we added it. 👏 Great suggestion @Br3nda!

**Comment by Br3nda** [comment]
I don't think I have the permissions / role to do this on coveralls

**Comment by Br3nda** [comment]
ANyone got permissions? ?I can't see a webhook or integration -- and i can't access growstuff/growstuff on coveralls.

**Comment by cesy** [comment]
Found it - coveralls comments turned off in the settings.
