### ISSUE TITLE
Fix "validation_regex" issue in app/models/post.rb

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#1252]
Insufficient validation for 'subject' using /\S/. Use \A and \z as anchors

https://codeclimate.com/github/Growstuff/growstuff/app/models/post.rb#issue_58b5f663969465000100016f

**Comment by arun1595** [comment]
@maco I would like to start contributing to Growstuff by fixing this minor issue. Looking at the code, we have the following regex `/S` which any non-whitespace character will match. 

Why do we even need this validation? To make sure people don't just enter whitespaces or leave it empty?

That said, I think it might be better if we add a min-length validation for the `subject`. What do you think?

**Comment by maco** [comment]
This is an error the security scanner threw up. All it has right now is `/\S/`, and the security scanner thinks we ought to be stricter so as not to allow things like Javascript injection.

> Calls to validates_format_of ..., :with => // which do not use \A and \z as anchors will cause this warning. Using ^ and $ is not sufficient, as they will only match up to a new line. This allows an attacker to put whatever malicious input they would like before or after a new line character.
>
> See [the Ruby security guide](http://guides.rubyonrails.org/security.html#regular-expressions) for more details

**Comment by arun1595** [comment]
@maco Yeah, I had a look at it and I understand why CC is complaining. What I am suggesting is that we can remove the regex validation and pass `presence: true` to the `validates` method.

That will make sure the input string non-blank. What do you think?

**Comment by maco** [comment]
And then the thing that would prevent it doing dangerous JS stuff is that
anywhere we want to show the post name, we don't incorrectly add the
"escaped" keyword?

**Comment by arun1595** [comment]
@maco As far as I understand, the dangerous JS sscript will only run if we're sloppy and run the malicious code via a link or any other means. The code example in the [Rails security guide](http://guides.rubyonrails.org/security.html#regular-expressions) is as follows

```ruby
link_to "Homepage", @user.homepage
```

where `@user.homepage` holds the malicious script. Since we won't ever link the post subject anywhere and we will just use it as a text, we can feel safe.

Does that make sense?

**Comment by maco** [comment]
yep

**Comment by Br3nda** [comment]
the field is for the subject of a blog post, so i think it should look for a single line of text (no newlines) and a length limit.
The field is safely escaped at display time AFAICT.

But, the code appears to not have a max length, which could really mess with the display of some of the pages on growstuff.

**Comment by arun1595** [comment]
@Br3nda Can you please review my [PR](https://github.com/Growstuff/growstuff/pull/1284)?

(I can't request a review using the github interface as I don't have enough permissions to do so.)

I am using `presence: true` instead of the regex validation which, essentially does the same thing.
