### ISSUE TITLE
Differentiate between annual and perennial

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1268]
The are plantings that are years old. An apple tree seldom finishes. Likewise a basil plant doesn't last 4 years. 

I'd like to have a flag on the crop for this. Then we can make a ui to allow users to quickly mark old crops as finished.. And not show progress bars  on forever crops.

**Comment by Br3nda** [comment]
We can instead show time until harvest, seasonly, on fruit trees etc.  And still have "finished" when the plant dies or is removed.

**Comment by maco** [comment]
Yes!

**Comment by CloCkWeRX** [comment]
So what's better to model: average_lifespan or a supports_recurring_harvest?

**Comment by Br3nda** [comment]
recurring sounds wrong. some are continuous (e.g. rosemary).
Is annual/perennial not covering it?

**Comment by Br3nda** [comment]
another aspect is maturity. I've been entering "finished_date" to make the maturity estimates work and a progress bar show. What i actually want is an estimate on when i can harvest. Because i've set the finished_date to 12 weeks in the future, the planting gets treated as finished just as it is mature enough to harvest. I've then had to go unmark the planting...

Finished should mean gone -- no more harvests. Maturity should mean the harvests can start.

So.... as a quicker fix, maybe we want maturity estimations to be called something else. A UI for entering what the seed/seedling packaging said (or sometimes i just google "cherry tomato maturity weeks") and then calculating a progress bar to maturity, instead of to finished.

**Comment by maco** [comment]
Good points. I think I usually call it "ready" if I'm not specifically
saying ripe about fruit.

**Comment by Br3nda** [comment]
Perhaps `planting.ready_at`
