### ISSUE TITLE
Build failing in dev branch

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1271]
/home/travis/build/Growstuff/growstuff/Gemfile:125:121: C: Metrics/LineLength: Line is too long. [123/120]
/home/travis/build/Growstuff/growstuff/Gemfile:126:28: C: Style/ExtraSpacing: Unnecessary spacing detected.

**Comment by CloCkWeRX** [comment]
Isn't that just from me adding
> # Pin until https://github.com/Growstuff/growstuff/issues/1270 / https://github.com/brigade/haml-lint/issues/186 is fixed
?
