### ISSUE TITLE
contributor check needs to check author too

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1289]
some commits have different commiter to author. git records this. 

however our script is only checking one. When i was commiter, and Megan was the author, it didn't pick up that Megan isn't in the contributors file.

**Comment by Br3nda** [comment]
this file is script/check_contributors_md.rb

**Comment by pozorvlak** [comment]
[For reference, the commit @Br3nda's talking about was d167a42]

We're currently checking for the presence of the author's GitHub username, which we're determining based on
 - whoever opened the PR, if we're in a Travis build
 - `git config github.user`, if we're running on a developer's machine.

I guess we could switch to checking for `git log $(target_branch)..HEAD --format=fuller | grep -e Author: -e Commit:` (or hopefully something equivalent but less horrible), but several of us use multiple names - for instance, I see that commit 5abc1fb lists you as "Brenda Wallace" under "Author" and as "Shiny" under "Commit".
