### ISSUE TITLE
Interesting members are not unique

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1305]
![image](https://cloud.githubusercontent.com/assets/12266/24849446/f47e6682-1e1f-11e7-9852-18e71afcadbf.png)

This is a bug i introduced when i moved this to a scope. In my dev dataset there aren't duplicates

it needs to be a left outer join -- but it isn't immediately obvious to me how to convince active record to do that AND recognise which model it's to create objects as.

**Comment by CloCkWeRX** [comment]
So it's
```

  scope :interesting, lambda {
    confirmed
      .located
      .recently_signed_in
      .has_plantings
  }

```
and
nor `scope :has_plantings, -> { joins(:plantings).where("plantings.id IS NOT NULL") }`

Adding a group by members.id should fix it; because we only care about if they have plantings, not the plantings themselves.

**Comment by CloCkWeRX** [comment]
oh, and 
 joins(:plantings).where("plantings.id IS NOT NULL")

is implied/redundant; it can just be 'joins(:plantings)` which should boil down to JOIN plantings ON plantings.member_id = member.id / there should be no way for plantings.id to be NULL; unless its a left join.
