### ISSUE TITLE
title/photo links are inconsistent

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1308]
In many places in the app, there is both a title and a photo of an item presented. 

e.g.
![image](https://cloud.githubusercontent.com/assets/12266/24986600/4978b9ae-204f-11e7-8c52-611a6f73d942.png)

the destination of the link for the title, versus the photo, is inconsistent on the site:

gardens_path
Title -> the garden
Photo -> the garden

plantings_path
Title -> the crop
Photo -> the planting

harvests_path
Title -> the harvest
Photo -> the crop

seeds_path
Title -> the seeds
Photo -> the crop

Can we make it consistent for our users?

**Comment by pozorvlak** [comment]
Ouch, that's a UI fail. Yes, we should do that.​
