### ISSUE TITLE
home page tables don't adapt well to small screens

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1334]
![image](https://cloud.githubusercontent.com/assets/12266/25872567/5e9c3ebc-355f-11e7-8b8f-af6dd58a09c5.png)

![image](https://cloud.githubusercontent.com/assets/12266/25874985/45d48a74-3569-11e7-98ca-fd3696e2675d.png)

Note: that's a firefox screen shot. On Chrome on android the hamburger menu is push right off the screen when the tables are wider than the screen, and the user has to scroll to find it.

**Comment by CloCkWeRX** [comment]
I wonder if we missed that one when looking at #808
