### ISSUE TITLE
Planting has different owner to its garden

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1342]
The way factoryGirl creates models in our spec means many are running with member1 owning the Garden and member2 owning the planting in that garden.

This is an invalid state for plantings to be in. -- and we may be missing strange data interactions that are possible because of this

I propose we add validations to not allow a planting to have a different owner to its garden.
I'd like to go even further and have a planting delegate it's owner to it's Garden.

We never have plantings that aren't in a garden.

**Comment by pozorvlak** [comment]
+1
