### ISSUE TITLE
Harvest predictions

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1350]
So we know when we're likely to have the first pumpkins etc, instead of just when the plant is likely to die off.

**Comment by Br3nda** [comment]
Should we go all out and have


finished_predicted_at
finished_at
maturity_predicted_at
maturity_at
first_harvest_predicted_at <-- calculated from harest records
first_harvest_at <-- unnecessary if recording harvests

and include whether plant is annual or perenial. 

I'd like to use to calculate:
"Plantings of this type in your area are usually harvested from January to March"
"Cabbage plants in your own gardens are mostly harvested in September"

I know some areas have zones - but they vary so much from country to country (and by seed brand!) that I can't see us using them reliably - but rather we'll start to create our own version of that if we have enough data.

**Comment by cesy** [comment]
Yes, this sounds good.

**Comment by Br3nda** [comment]
@cesy @pozorvlak I'd like to make Harvest.harvested_at required, otherwise calculating time to the first harvest gets messy.

**Comment by pozorvlak** [comment]
Sounds reasonable - defaulting to "today"?

**Comment by Br3nda** [comment]
Yes. The form already does default to today. Now it's just required..
