### ISSUE TITLE
Quick plant form

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1351]
Propose a modal form (with AJAX/remote) from the gardens#show that lets the user specify only which crop they planted and thus quickly enter data.

**Comment by jturnerWNC** [comment]
I'm a newer Rails developer and this is my first attempt to contribute to an OSS project. I'm super excited, but need a bit of guidance. I have growstuff running locally, but I did have to comment a line in the views/layouts/_meta.html.haml file due to this error: no implicit conversion of nil into String. This quick plant form looks like something I could attempt, but let me know if there would be a better beginner item to tackle.

**Comment by pozorvlak** [comment]
Hi @jimmy_turner, and welcome! I suspect there are easier open issues than
this one, but feel free to have a go - have a look at
https://github.com/Growstuff/growstuff/blob/b9edd2f89ba39b151ece7b88b9a7a4330347db67/app/assets/javascripts/posts.js
and
https://github.com/Growstuff/growstuff/blob/b9edd2f89ba39b151ece7b88b9a7a4330347db67/app/controllers/likes_controller.rb
for some existing AJAX code.

I'm concerned by the problem you're experiencing - can you give us a bit
more detail, either here or (better) as a new issue? We'd like to know

   - What you were doing when you encountered the error (which page you
   were looking at, for instance)
   - Which line you commented out
   - The full stack trace
   - Possibly a screenshot?

**Comment by jturnerWNC** [comment]
Thank you for the examples! I will send you information regarding the errors I experienced. I do want to confirm my local setup.  Should I create this file:  'config/application.yml' and copy the content over from 'config/application.yml.example', then delete the examples file? 

Also, can you add a bit more detail to the request for "lets the user specify only which crop they planted and thus quickly enter data". I'm new to the site and I'm slowly learning my way around, thanks!

**Comment by CloCkWeRX** [comment]
> then delete the examples file?
More customise the copy you took a bit for your local environment. The defaults 'should work', but for some features people will sometimes register a private dev account/key/credentials/database config/etc for their local machine; while we we use in production is different again.

**Comment by jturnerWNC** [comment]
Ok, so I will create the config/application.yml file so I can customize it, and git ignore this and just leave the config/application.yml.example file alone. Having the .example extension on this file won't create problems?

**Comment by CloCkWeRX** [comment]
Shouldn't be an issue :)

**Comment by jturnerWNC** [comment]
I needed to change ruby versions from 2.3.4 to 2.3.3. When I run it locally it says GrowStuff(dev) which I think would be correct.
