### ISSUE TITLE
bundle exec rspec failures RAILS_SECRET_TOKEN not set

### ISSUE THREAD

**Issue by shadjachaudhari** [Growstuff/growstuff#1368]
I am new to Ruby.
I followed all steps mentioned in documentation.
They didnt help me in getting all tests passed.

CommentsController
  GET new
    dies if no post specified
    with valid params
      assigns the old comments as @comments (FAILED - 1)
      picks up post from params
  DELETE destroy
    not my comment
      example at ./spec/controllers/comments_controller_spec.rb:113 (FAILED - 2)
    my comment
      redirects to the post the comment was on (FAILED - 3)
  PUT update
    not my comment
      example at ./spec/controllers/comments_controller_spec.rb:87 (FAILED - 4)
    my comment
      redirects to the comment's post (FAILED - 5)
    attempting to change post_id
      does not change post_id (FAILED - 6)
  GET RSS feed
    returns an RSS feed
  GET edit
    my comment
      assigns previous comments as @comments (FAILED - 7)
    not my comment
      example at ./spec/controllers/comments_controller_spec.rb:72 (FAILED - 8)

Failure/Error:
       raise "RAILS_SECRET_TOKEN environment variable"\
         "not set - have you created config/application.yml?"
     
     RuntimeError:
       RAILS_SECRET_TOKEN environment variablenot set - have you created config/application.yml?

**Comment by Br3nda** [comment]
From your command prompt, run: bundle exec rake secret

It will generate a long string of characters. Copy this string and paste it into config/secrets.yml as follows:

```
development:
  secret_key_base: <paste the string here>
test:
  secret_key_base: <paste the string here>
```

**Comment by shadjachaudhari** [comment]
Hey this worked for me to remove that particular error. Hence I am closing this issue but creating new one for other errors.
Thanks for help!
