### ISSUE TITLE
Clean up interagrated apps

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1371]
These are the apps with hooks on this repor
![image](https://user-images.githubusercontent.com/12266/28410575-2fe0ff2a-6d92-11e7-9db6-7c38bbe98b79.png)

How about we delete all but the travis one? The others seem to be remnants of another time.

**Comment by cesy** [comment]
Hmm, I haven't used IRC in ages, happy to turn that one off, and we should probably close the channel at some point if none of us are active. Pivotal is definitely dead. Gemnasium is still useful. We're not using the Twitter integration, but actually it might be helpful if we can fix the thing that made it auto-tweet whenever we released.

**Comment by Br3nda** [comment]
Deppbot and codeclimate seem to do what Gemnasium does.

**Comment by cesy** [comment]
I can't see the same kind of info in codeclimate, and deppbot doesn't catch everything that gemnasium does, from what I can see.

**Comment by cesy** [comment]
Thanks for raising this, though. I've removed PivotalTracker now, and if others agree, we can remove IRC as well. It looks like Twitter can't do releases-only so I've removed that now.
