### ISSUE TITLE
Add google picker photo upload support

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1378]
Parent issue #513
https://developers.google.com/picker/?hl=en was something I did in another project that was fairly easy.

Use case:
 * I have an android phone
 * I have google photos on it (fairly common I'd suggest)
 * Google automatically syncs photos to the cloud
 * I can easily attach a cloud stored photo publically

Will have a shot at it in a while

**Comment by Br3nda** [comment]
Does the jpeg stay hosted on a google server?

**Comment by CloCkWeRX** [comment]
I think like flickr  they already syncd - So I gave consent for google to
dish up a URL

**Comment by CloCkWeRX** [comment]
Annoyingly, this just doesn't exist from a google photo API perspective.
