### ISSUE TITLE
Spam in forums again (sigh)

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1380]
http://www.growstuff.org/posts/ehan147-20170710-cash-for-cars-in-los-angeles-california and a few others.

**Comment by Br3nda** [comment]
Should we turn off forums? They aren't active at all.

**Comment by Br3nda** [comment]
Can i have admin?

I can just give it to myself -- but best i asked...

**Comment by cesy** [comment]
Happy for you to have admin and delete spam. If we turn them off, won't we also lose the good history there?

**Comment by Br3nda** [comment]
deleted it -- just 3 bits of spam. doesn't look automated.

**Comment by CloCkWeRX** [comment]
I'm happy to forum garden as well on occasion. I'm -1 for turning them off even if they are a bit dormant.
