### ISSUE TITLE
Let's turn on hound bot?

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1393]
Instead of linting on Travis. Hound will comment on the line in any PR, giving much better feedback when code doesn't meet the code style

**Comment by pozorvlak** [comment]
Huh, that does sound more convenient.

**Comment by cesy** [comment]
Yes, sounds good, I've used it on other projects.

**Comment by Br3nda** [comment]
I've turned it on..

I'll look for some time to also add a hound.yaml file -- until then it's using the default config.
