### ISSUE TITLE
Upgrade production elasticsearch to 2.4.0

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1395]
Because Staging and Travis are running on 2.4.0

creating task so it doesn't get forgotten

**Comment by cesy** [comment]
https://docs.bonsai.io/docs/upgrading-your-version has info.

Migration checker passed with no issues.

New cluster created, Bonsai Navy. We need to update our env variables to refer to it in the right places, then when we're ready, upgrade it to the paid tier and make the switch.

**Comment by Br3nda** [comment]
@cesy okay if I go ahead and do this? I'll run the migration and move production over. We might have an outage, but we can also undo it.

**Comment by Br3nda** [comment]
(I'd change the heroku configuration to point at the new elastic, rather than change code)

**Comment by cesy** [comment]
Sure, go ahead.

**Comment by Br3nda** [comment]
Currently elasticsearch 6
