### ISSUE TITLE
Deprecation warnings in Travis logs

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#1406]
There appear to be four separate deprecations we should fix:

parser, required by i18n-tasks:
```
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

Something to do with PostgreSQL:
```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.
You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
```

PhantomJS:
```
......You're running an old version of PhantomJS, update to >= 2.1.1 for a better experience.
```

Something else to do with i18n:
```
DEPRECATED: The language code "kh" is deprecated and will be removed in 2.0. For Khmer support use "km" instead.
DEPRECATED: The language code "kr" is deprecated and will be removed in 2.0. For korean support use "ko" instead.
DEPRECATED: This language code "rs-latin" is deprecated (invalid serbian language code) and will be removed in 2.0. For Serbian latin support use "sr-latin" instead.
DEPRECATED: This language code "rs" is deprecated (invalid serbian language code) and will be removed in 2.0. For Serbian support use "sr" instead.
```
The last one in particular is repeated over and over.

**Comment by cesy** [comment]
See also #1388

**Comment by pozorvlak** [comment]
@cesy d'oh, sorry I missed that.

**Comment by Br3nda** [comment]
These should go away when we reach rails 5

**Comment by Br3nda** [comment]
they are sitll there in Rails 5 :(

**Comment by Br3nda** [comment]
appears to come from here
https://github.com/jrfferreira/bootstrap-datepicker/blob/master/js/locales/bootstrap-datepicker.kh.js

**Comment by CloCkWeRX** [comment]
Also in web console
datepicker deprecation warnings:
![image](https://user-images.githubusercontent.com/365751/59324108-aba79c80-8d1c-11e9-87db-12f077e1ab71.png)

**Comment by Br3nda** [comment]
Most of the warnings are gone now.

**Comment by Br3nda** [comment]
Next to fix

DEPRECATION WARNING: [Devise] `DeviseHelper.devise_error_messages!`
is deprecated and it will be removed in the next major version.
To customize the errors styles please run `rails g devise:views` and modify the
`devise/shared/error_messages` partial.
 (called from block in _app_views_devise_registrations__edit_email_html_haml__326412798331984106_122236620 at /home/travis/build/Growstuff/growstuff/app/views/devise/registrations/_edit_email.html.haml:5)

**Comment by CloCkWeRX** [comment]
https://github.com/Growstuff/growstuff/pull/2019 addressed this more

**Comment by CloCkWeRX** [comment]
#2031 created for the last one, closing.
