### ISSUE TITLE
Allow brackets in garden names

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1419]
![image](https://user-images.githubusercontent.com/12266/31966745-2b2e1db0-b968-11e7-8a92-ef1e5b38cf90.png)

**Comment by logangingerich** [comment]
This is one that I would love to work on early this week (Tues-Wed), unless anyone else really wants to take it before then.

**Comment by pozorvlak** [comment]
@logangingerich go for it!
