### ISSUE TITLE
Order photos by date taken

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1421]
currently we order by the local database :created_at, but both flickr and the jpeg have a date taken field. When the user imports several photos of a plant, we can order by the date the photo was taken, and then it appears to grow from photo to photo.

![image](https://user-images.githubusercontent.com/12266/31966838-79665aa6-b968-11e7-997b-58a1914a7d5d.png)

**Comment by mftaff** [comment]
@Br3nda Is this open? Mind if I have a go at this?

**Comment by Br3nda** [comment]
Please go ahead.

**Comment by mftaff** [comment]
I should preface here that I am relatively new to open source contributing 😃 

in `plantings_controller#show`
```
  def show
    @planting = Planting.includes(:owner, :crop, :garden, :photos)
      .friendly
      .find(params[:id])
    @photos = @planting.photos.order(created_at: :desc).includes(:owner).paginate(page: params[:page])
    respond_with @planting
  end
```

Am I on the right track in thinking the change to be made has to do with 
`@photos = @planting.photos.order(created_at: :desc).includes(:owner).paginate(page: params[:page])`
replacing `created_at: :desc` with something like `date_taken: :desc`? If so, I have not found where in the db that info is stored? Is it part of the flickr metadata that gets assigned when a new photo is created? Do we need to add a db column to photos?

Thanks for letting me have a shot at this! Hopefully I can learn, and be helpful at the same time 🚀

**Comment by Br3nda** [comment]
Current photo table looks like this
```
  create_table "photos", force: :cascade do |t|
    t.integer  "owner_id",        null: false
    t.string   "thumbnail_url",   null: false
    t.string   "fullsize_url",    null: false
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "title",           null: false
    t.string   "license_name",    null: false
    t.string   "license_url"
    t.string   "link_url",        null: false
    t.string   "flickr_photo_id"
  end
```
So the date_taken field isn't in there.
We could read it at time of import from Flickr.
Photos are probably one of the more complicated controllers though, so don't be dismayed if it's all confusing at first.

**Comment by mftaff** [comment]
Great! Here is where I am up to based on your last message:

we will need to add a date_taken column: 
```
20180118112809_add_datetaken_to_photos.rb

class AddDatetakenToPhotos < ActiveRecord::Migration
  def change
    add_column :photos, :date_taken, :datetime
  end
end
```
And then we will need to populate `date_taken` when we make the Flickr api call by adding a line to the flickr_metadata method in photo.rb:
```
Photo#flickr_metadata

  def flickr_metadata
    flickr = owner.flickr
    info = flickr.photos.getInfo(photo_id: flickr_photo_id)
    licenses = flickr.photos.licenses.getInfo
    license = licenses.find { |l| l.id == info.license }
    {
      title: calculate_title(info),
      license_name: license.name,
      license_url: license.url,
      thumbnail_url: FlickRaw.url_q(info),
      fullsize_url: FlickRaw.url_z(info),
      link_url: FlickRaw.url_photopage(info),
-->   date_taken: info.dates.taken
    }
  end
```
Finally, we will update the `plantings_controller#show` method using `date_taken` instead of `created_at`:
`@photos = @planting.photos.order(date_taken: :desc).includes(:owner).paginate(page: params[:page])`


Thoughts? Did I miss something?

**Comment by Br3nda** [comment]
This all sounds good to me.

Also adding and/or modifying some tests (specs) for this.

**Comment by mftaff** [comment]
With regards to tests, I am not sure where/what to add.
It seems that the flickr api tests for photos has been kept intentionally broad:
```
  describe 'flickr_metadata' do
    # Any further tests led to us MOCKING ALL THE THINGS
    # which was epistemologically unsatisfactory.
    # So we're just going to test that the method exists.
    it 'exists' do
      photo = Photo.new(owner_id: 1)
      photo.should.respond_to? :flickr_metadata
    end
  end
```

I also was having some trouble creating a test to check that the photos are getting ordered by date taken.. Maybe you could point me in the right direction?
In the meantime I will create a PR to allow for feedback on what I have already done.

**Comment by pozorvlak** [comment]
Sorry, that comment (which I wrote) was needlessly obscure. It's not so
much "kept intentionally broad" as "we couldn't think how to write good
tests" - we very quickly ended up writing lots of hand-rolled mocks which
only exercised our logic superficially and gave us little confidence that
our code would work when run against the real system. If you can think of
some meaningful tests to write, then go for it.
