### ISSUE TITLE
Can we detect perennials? 

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1430]
If a planting has lived for 2 years or more according to data in growstuff, can we reasonably mark it as perennial?

**Comment by pozorvlak** [comment]
I'd want some evidence of continued activity - it might just be abandoned.

**Comment by Br3nda** [comment]
Harvests or seeds or photos?

**Comment by Br3nda** [comment]
There will be perennials that die or are pulled out of gardens. So maybe we just have to manually mark perennials.
