### ISSUE TITLE
wrapping badly in mutiple places

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1459]
Many of the card/thumbnail elements of the page wrap in strange ways

homepage seeds
![image](https://user-images.githubusercontent.com/12266/32986878-3e898cd2-cd40-11e7-8bad-554bbf4f998f.png)

gardens#index
![image](https://user-images.githubusercontent.com/12266/32986869-298628e0-cd40-11e7-817a-ccaf490562d4.png)

**Comment by Br3nda** [comment]
might be fixable with use of clearfix
https://v4-alpha.getbootstrap.com/utilities/clearfix/

**Comment by samuelssnider** [comment]
@Br3nda I'm a first time contributor, but I'd love to give this a shot. For theses two pages, do you want them to wrap and then start at the furthest-left card position?

**Comment by Br3nda** [comment]
If you can work it out --- i dunno much css, so propose a solution and I can test it.

**Comment by jenkr55** [comment]
Also /seeds and /members are wrapping funnily 
<img width="1222" alt="seeds wrapping issue" src="https://user-images.githubusercontent.com/8432175/38458957-61ea8b5e-3a69-11e8-8297-5ecfd0de8e3b.png">
<img width="1237" alt="screen shot 2018-04-07 at 1 42 21 pm" src="https://user-images.githubusercontent.com/8432175/38458970-898ab990-3a69-11e8-9035-6d8109526f0b.png">

**Comment by Br3nda** [comment]
Fixed in #1609
