### ISSUE TITLE
Ensure all controller index pages have pagination or similar, to prevent ever displaying 1000's of records accidentally

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1475]
From #1471

```
 def index
    @accounts = Account.all.order(created_at: :desc)
```
seems common in a few places, we should hunt these down and make sure there are sane limits/pagination/etc where appropriate

**Comment by Br3nda** [comment]
- [ ] controller specs for pagination
- [ ] feature specs for pagination
