### ISSUE TITLE
only show preview/start of a blog post

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1476]
there's some long "posts" on some pages -- and they appear early on the page, pushing some data off the screen waaaay to the bottom on mobile. e.g. http://www.growstuff.org/crops/tomato

How about we turn posts into a shorter preview of the post on:

- [ ] crop#show
- [ ] post#index

**Comment by CloCkWeRX** [comment]
The tomato blog posts.... doesn't seem *too* excessive at the moment; at least on desktop. Maybe we add a few 'scroll to bottom/top' type links, as per Travis for mobile users to the default layout?

**Comment by Br3nda** [comment]
This was done in the new design
