### ISSUE TITLE
Connect / login by twitter and Facebook broken

### ISSUE THREAD

**Issue by TinaHeiligers** [Growstuff/growstuff#1479]
As a new member editing my profile, I want to be able to connect to Twitter, Flikr or Facebook when clicking the icons so that I can link my profile to those accounts.
Current behaviour: the links to make to a page showing that the page I am looking for does not exist.
Desired behaviour: the links should take me to the social media page.
Bugs captured using bugReplay: https://app.bugreplay.com/shared/report/3864db91-3bb2-4a2f-91c3-38e09ed4a603

**Comment by Br3nda** [comment]
Thanks for the bug report.

**Comment by Br3nda** [comment]
i started to look at this - there's a few mysteries in the registrations/members code. it mostly dates from 2013. Is anyone more familiar with older devise?

**Comment by pozorvlak** [comment]
I was around then, but IIRC we mostly cargo-culted that code :-/ Is there anything specific that's confusing you?

**Comment by Br3nda** [comment]
Yeah, the app has linked to /auth/flickr /auth/twitter etc. But I can't find what view those are in. I think I found it once before when I fixed Flickr authentication earlier this year.

**Comment by Br3nda** [comment]
`app/views/devise/registrations/_edit_apps.html.haml` <-- found!

**Comment by TinaHeiligers** [comment]
Well done @Br3nda !
