### ISSUE TITLE
Maps broken in staging. 

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1536]
Production is fine, but there's no markers on the maps on staging.

**Comment by Br3nda** [comment]
community map is fine - only the crops#show map is broken

**Comment by Br3nda** [comment]
Still looking at this one.

**Comment by Br3nda** [comment]
found this cause. the response from crops#show in json no longer includes the plantings


also noticed the community map pulls down *ALL* members and then look for location client side in js -- i'll log an issue to fix that.

**Comment by CloCkWeRX** [comment]
Lets consider test coverage too (low priority)
