### ISSUE TITLE
Tell me what will be ready to harvest soon?

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1538]
Help me predict what will likely be ready to harvest now, next week, next month.

**Comment by Br3nda** [comment]
Also last year's data (for perennial, Eg when did this apple tree have harvests in previous years

I've been toying with presenting data for your hemisphere. E.g tomatoes in the southern hemisphere are most often planted (or harvested, or finished) in X month. But better to present in a visualisation than on a single fact. Then we can see clusters of plantings around a time of year.

**Comment by Br3nda** [comment]
The progress bars right now are time to finished, not time to harvest. I'm gonna play with more ways to present time to first harvest and last harvest.

**Comment by Br3nda** [comment]
@CloCkWeRX did you imagine a source for weather data? I have my own station and use homeassistant. 

In the next year or so, I'm thinking a growstuff module that integrates with the hone automation, and the open source irrigation system like open sprinkler and rain machine .

**Comment by CloCkWeRX** [comment]
http://openweathermap.org/price - free tier of that perhaps; similar to the know the rainfall tickets we had.

For the home automation stuff, it might be worth looking into a generic MQTT endpoint using something like mosquitto or a hosted solution (https://www.cloudmqtt.com/ / something with a free tier?) to receive any kind of data.

At work we use it for a google docs like 'who is looking at this now' feature using https://github.com/eclipse/paho.mqtt.javascript I think + the websockets interface.

**Comment by Br3nda** [comment]
Related to  #472
