### ISSUE TITLE
community map downloads all members

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1541]
community map pulls down ALL members and then looks for location client side in js
We should only send members with locations to the browser - to save on traffic, memory use, and other things that cause global warming.

**Comment by pozorvlak** [comment]
I think the crop map will have the same problem.

**Comment by jenkr55** [comment]
Is this still an issue? It appears to be pulling members with `:located` scope in the places controller and confirmed when looking at logs

<img width="577" alt="screen shot 2018-04-18 at 5 34 23 pm" src="https://user-images.githubusercontent.com/8432175/38961645-0afcb226-432f-11e8-82d1-e6399c3c58a6.png">

**Comment by Br3nda** [comment]
thanks for checking.
Looks like this bug report is wrong.

**Comment by pozorvlak** [comment]
Looks like it *was* an issue, but was fixed way back in 2011: 35f3ee89489adbb531949f242691dd1949e94631.
