### ISSUE TITLE
crops#show includes all photos. This could be a lot of photos.

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1542]
We might want to only show the X most recent. I suggest 5. 

in `app/views/crops/show.html.haml`

```
- content_for :opengraph do
  - @crop.photos.each do |photo|
    = tag("meta", property: "og:image", content: photo.fullsize_url)
```

**Comment by CloCkWeRX** [comment]
Torn between performance and semantic webbyness :P Can I barter with you for a max of 20
