### ISSUE TITLE
Harvest's planting matching only show if they're is a match

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1595]
Currently we show this text on a harvest that is not yet associated with a planting
"Planting: Is this from one of these plantings?"

But we show it when when there are no suggestions. 

Only show if there is a suggestion

**Comment by jenkr55** [comment]
Is this issue resolved or is there still more to fix?

**Comment by Br3nda** [comment]
I haven't seen it happen for a while now. Seems fixed when i checked.
