### ISSUE TITLE
Unable to log in with Facebook

### ISSUE THREAD

**Issue by jenkr55** [Growstuff/growstuff#1642]
Clicking "Sign in with Facebook" on production brings me to Facebook and this error pops up:

<img width="545" alt="screen shot 2018-05-28 at 11 00 58 am" src="https://user-images.githubusercontent.com/8432175/40622321-7a5c3f3c-6266-11e8-84ec-8f0b234b97a2.png">

Googling the issue brings up lots of ways to fix it, whoever has access to the Facebook app settings probably needs to make some changes https://stackoverflow.com/questions/37063685/facebook-oauth-the-domain-of-this-url-isnt-included-in-the-apps-domain

**Comment by Br3nda** [comment]
Which domain are you signing in with?
is it www.growstuff.org? growstuff.org? something else?

**Comment by CloCkWeRX** [comment]
```
Hi,

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app Growstuff.org  (AppId: 362358580765484) doesn't comply with the following:

Platform Policy 8.1: Verify that you have integrated Login correctly. Your app shouldn't crash or hang during the testing process.

During Login, your app or website is crashing or hanging excessively, creating a broken experience for people trying to use your Login integration. To make sure this flow runs smoothly, check that you've integrated Facebook Login correctly. We recommend that you test Login on all integrations. If you have not already done so, please:

• We encourage you to test your Login integration following these steps here: https://developers.facebook.com/docs/facebook-login/testing-your-login-flow/
• Best Practices for Login can be found here: https://developers.facebook.com/docs/facebook-login/best-practices


You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.

Please make the requested changes by 2019-06-26 at 12:00 PST.

Let us know when you've updated your app by replying to this email. If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help. 
```

Given the tone of that message, I'm inclined to tell Facebook where to go and drop the feature. Any strong objections?
I was originally for this, to enable the use case of local gardening interest groups or similar community groups to easily make use of growstuff, and while it still applies, I'm not sure if its been effective.

**Comment by Br3nda** [comment]
I don't use Facebook at all. That means i cant test this

**Comment by Br3nda** [comment]
An alternative approach is to use auth0 or similar, which manages the multiple sso dor us.
