### ISSUE TITLE
Impending Flickr apocalypse 

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1738]
Flickr will be deleting the photos from free accounts soon. If we want to preserve our plant photo database we'll need to copy these real soon.

**Comment by cesy** [comment]
I thought you can keep up to 1000 photos for free?

**Comment by Br3nda** [comment]
yes - many of our user-contributed photos will potentially not be in their latest 1,000 photos and thus will be deleted.

**Comment by pmackay** [comment]
What would the future ideal setup be? Is there an intent to move to managing image storage for the project, rather than being dependent on one provider?

**Comment by Br3nda** [comment]
I'd like to know any of our assembled data belongs in wiki commons somewhere.

**Comment by cesy** [comment]
Do we have a plan for funding S3? I'm currently paying all the hosting costs myself, and it would be good to share that out at some point.

Long-term, I'm wary of us putting too much effort image hosting ourselves rather than outsourcing it.

Flickr was just the easiest first service to add - it would be great to add others, particularly others that support copyleft, as you say.

I like the other features you list, Brenda.

**Comment by pmackay** [comment]
>Do we have a plan for funding S3?

I'm generally interested in this and the wider perspective on funding this site. How sustainable is it for @cesy to maintain funding?

**Comment by cesy** [comment]
It's not ideal. Skud had a whole business model originally, but it was pretty dependent on one person working on it full time as a small business. I think we're better off considering it a charity, to get enough data to provide it to the world for free. Setting up an official non-profit requires a bit of paperwork but is probably the long-term answer. In the meantime I will happily accept donations towards it. Heroku is currently £12-£20 a month depending on exchange rates and what add-ons we have been gradually rationalising. Domain etc. is £35 a year. Mapbox have stopped charging me, I can't remember if that was deliberate or if there's a problem with our maps.

**Comment by Br3nda** [comment]
I don't think we use mapbox... Do we? Its all leaflet and opem street maps.

**Comment by Br3nda** [comment]
Sad to report Skud's photos werw deleted by Flickr.

**Comment by Br3nda** [comment]
@cesy how shall we do donations? Something like gittip or patreon? (both have some problematic history)

**Comment by cesy** [comment]
Yeah, I think we switched over at some point.

I'd be inclined to just do Paypal to my email address for now, until we can sort out a proper way to structure it. Gittip appears to be dead, but Liberapay looks like a good fork?
