### ISSUE TITLE
Automatic let's encrypt by heroku.

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1783]
Heroku now manages let's encrypt automatically. To use this feature, we'll need to do the DNS changes. I went to check what we had already, and i think that option no longer exists, which resulted in (i fear) heroku picking an option that does and saving the settings. I can't tell if i've broken it :-/ yikes

To use the automatic letsencrypt, we'd need to use this as our DNS settings.
growstuff.org CNAME to reticulated-apricot-i00qvzwegb2flbaxnt1riic7.herokudns.com
www.growstuff.org CNAME to warm-blueberry-cv60x6dwsrkqaj0otd10bt9r.herokudns.com

Who has DNS admin rights?

**Comment by maco** [comment]
The DNS is in Namecheap, and all of us on the shared LastPass folder have
access to it.

**Comment by maco** [comment]
(Which is to say, I can make that change.)

I should note that right now we have growstuff.org set to redirect to
http://www.growstuff.org , which I imagine should also change in the course
of this.

**Comment by Br3nda** [comment]
the redirect is good, as long as it's doing it on https/443 as well.

**Comment by maco** [comment]
It’s not. I don’t think you can do a DNS redirect differently depending on
protocol. Should I change it to be https for the destination? (Do we want
to do HTTPS everywhere?)

And should I go ahead and do the DNS changes in this ticket *now*?

> --
Mackenzie Morgan
Linux User #432169

**Comment by cesy** [comment]
HTTPS everywhere sounds good to me.

**Comment by pozorvlak** [comment]
+1 for HTTPS everywhere.

[Also sorry for my general non-responsiveness in recent months: I've had a
number of attacks of life in quick succession. And Happy New Year,
everyone!]

**Comment by Br3nda** [comment]
I don't have access to the lastpass folder afaik.

I cant tell from. The replies if someone is going to look at this. Right now the app returns a ssl cert for herokuapp.com

**Comment by maco** [comment]
I'm confused by why there are two CNAMEs to use when blank currently redirects to www, so I set the www one (warm blueberry) and updated the blank redirect to use https.

After this, I see we do have mixed content warnings. The Gravatars are coming over HTTP.

**Comment by Br3nda** [comment]
Please do the CNAME for www. I'll investigate the redirect later.

**Comment by maco** [comment]
I did both. So now http://growstuff.org is bopping over to https://www.growstuff.org and that's loading up fine. Chrome isn't blocking it or anything. But the address bar also isn't green, and if I click on it, it tells me about the Gravatars. So I'm gonna close this ticket and open one for needing to go to HTTPS for Gravatar.

**Comment by Br3nda** [comment]
We still have https://growstuff.org

Will the namecheap config let you CNAME that and then we'll put a redirect in the rails app
