### ISSUE TITLE
Mixed content warnings on some assets

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#1989]
https://www.staging.growstuff.org/crops/thai-basil

mixed content warnings on some assets; such as:
```
<div style='float: right;'>
<a href='http://opendefinition.org/ossd/'>
<img alt='' src='http://assets.okfn.org/images/ok_buttons/os_80x15_blue.png'>
</a>
</div>
```
![image](https://user-images.githubusercontent.com/365751/59324075-8155df00-8d1c-11e9-9d91-910a609a1611.png)

**Comment by Br3nda** [comment]
fixed
