### ISSUE TITLE
Pagination not responsive 

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#2044]
![Screenshot_20190708_151310_com android chrome](https://user-images.githubusercontent.com/12266/60780523-f0dfb280-a192-11e9-9f4d-2d5bb33021a8.jpg)
![Screenshot_20190708_151314_com android chrome](https://user-images.githubusercontent.com/12266/60780525-f50bd000-a192-11e9-89c3-bcbba5502ec9.jpg)

**Comment by AlSufyaniT1** [comment]
https://github.com/Growstuff/growstuff/issues/2044#issue-465034832`[https://github.com/Growstuff/growstuff/issues/2044#issue-465034832](https://github.com/Growstuff/growstuff/issues/2044#issue-465034832) `

**Comment by CloCkWeRX** [comment]
https://github.com/Growstuff/growstuff/pull/3584
