### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#2067]
And fixing up semantic web pages 

Issues via Lighthouse

* https://github.com/Growstuff/growstuff/pull/3561
* Links do not have a discernible name (seems to be forum posts)
* Background and foreground colors do not have a sufficient contrast ratio. (https://dequeuniversity.com/rules/axe/4.8/color-contrast). (https://github.com/Growstuff/growstuff/pull/3568 + maybe other areas)
* Heading elements are not in a sequentially-descending order

**Comment by CloCkWeRX** [comment]
I turned off accessbilitylint as it was spamming the heck out of pull requests.

**Comment by CloCkWeRX** [comment]
Home page

Results via Chrome > Lighthouse.
![image](https://github.com/Growstuff/growstuff/assets/365751/f3f17c06-3db6-4162-a5db-93ed549bc7d0)

**Comment by CloCkWeRX** [comment]
Will address the alt tags.
Ignoring the color contrast one, as most of the things it is mad about are deliberately .muted

**Comment by CloCkWeRX** [comment]
![image](https://github.com/Growstuff/growstuff/assets/365751/f5d960c6-dc62-4e67-9f86-4573ed3cbc33)

**Comment by CloCkWeRX** [comment]
Alright, for the buttons can go from #5f8e43 to #57803C without much negative impact.

**Comment by CloCkWeRX** [comment]
![image](https://github.com/Growstuff/growstuff/assets/365751/fd9cfc3e-4058-4076-9245-ed1b699d47db)
With the alt tag fixes

**Comment by CloCkWeRX** [comment]
TODO: accessbilitylint was annoying.

axe-core-capybara plugs into the features.

https://github.com/dequelabs/axe-core-gems/blob/develop/packages/axe-core-capybara/README.md
