### ISSUE TITLE
Newly created garden layout needs minor adjustment

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#2104]
![image](https://user-images.githubusercontent.com/365751/61587397-f8f31580-abc8-11e9-96cd-fabdb896225c.png)

 1. New garden
 2. Enter details -> create
 3. View

Problems:
Garden timeline is off/odd
Nothing planted text alignment
For the 'nothing planted' if I have create rights, consider showing me a 'plant something' control (it's hard to discover under Actions)

**Comment by Br3nda** [comment]
Fixed in #2204
