### ISSUE TITLE
Avoid showing "x followers" if not authorised to follow link

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#2106]
https://www.growstuff.org/members/ybvb -> https://www.growstuff.org/members/ybvb/followers

I then see:
![image](https://user-images.githubusercontent.com/365751/61587469-22607100-abca-11e9-95d3-8a2fe22a28e3.png)

**Comment by Br3nda** [comment]
How about we let anyone see followers.
