### ISSUE TITLE
Improve gardens index page for new (all) members

### ISSUE THREAD

**Issue by simicic** [Growstuff/growstuff#2369]
As a new member seeking inspiration, `https://www.growstuff.org/gardens` is not really inspiring, gardens links, inactive checkbox and jump to cover half of the page (not to mention how it looks on mobile)

**Some of the easy fixes could be**:  
1. Navigation for "My gardens", "Everyone's gardens" and "Add a garden" does not need to be a card element - it can simply be links next to each other underneath the title.
2. Inactive checkbox can follow and be next to the rest of the filters.
3. "Jump to" can be removed? 3 lines of jump to names like `2019` and `8x2 bed` is less valuable than inspiring garden photos and list of plantings.
4.  For mobile keep garden cards as is, on web garden cards can be modified into: column for photo, owner and actions and other column next to it for plantings (limit number of plantings to keep the size unified and add a line for perennials)

I would love to share Growstuff with my friends but currently style looks quite outdated and not engaging. I think when you register (or explore) a new website you do seek inspiration or a tool that can help you improve how you do things. Being inspired by people around can be a good start to engage new users - therefor - Gardens#index is an important page. 

Let me know what you think!

**Comment by CloCkWeRX** [comment]
#513 would help a bit with this, especially since flickr has all sorts of arbitrary limits on it these days; coupled with a sort by recent plantings as a default link.

We should probably also automatically mark things inactive with no plantings in > 2 years or something like that; to get the actually active ones.

**Comment by simicic** [comment]
@CloCkWeRX thanks for the response, #513 will not solve the issue with half a page being irrelevant content - but it I do agree it will help in engaging users. However, not sure how you pay for hosting, but having Flickr as a host for the images is actually quite nice. (I say this without knowing the plan for the platform in the future)

Marking gardens as inactive is also useful and can be a separate issue. 
Still, do you think I could pick some of the quick fixes as suggested? (I also joined  gitter - we can discuss it further there)

**Comment by Br3nda** [comment]
agreed. that page could be much better.

**Comment by Br3nda** [comment]
I agree the jumpto should be removed, unless you're viewing your own gardens.

I want the whole page redone, really. It is useful as an overview of your own gardens. It's a mess when viewing everyone's gardens. And it has a lot of display mess like the finish button being huge.

**Comment by Br3nda** [comment]
the /members/:slug/gardens is the only page with an overview of your whole garden. i was thinking that page might become a reactjs component. Then add features such as filtering to what's nearly ready for harvesting now, or what will be ready next week etc so people can plan their food

Reactjs itself is working in a pull request, but the components I made on that PR was just to check it's working.

**Comment by Br3nda** [comment]
fixed in #2371
