### ISSUE TITLE
Support page is super out of date

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#2527]
Growstuff isn't run by Skud anymore or a commercial business anymore. 
https://www.growstuff.org/support

**Comment by Br3nda** [comment]
I think we need to remove their admin too. Not sure they still control their email address

**Comment by Br3nda** [comment]
i've removed Skud's admin.

**Comment by CloCkWeRX** [comment]
```
vagrant@ubuntu-groovy:~/growstuff$ ack skud
lib/tasks/openfarm.rake
5:  # usage: rake growstuff:admin_user name=skud

lib/tasks/growstuff.rake
5:  # usage: rake growstuff:admin_user name=skud
12:  # usage: rake growstuff:cropwrangler_user name=skud
vagrant@ubuntu-groovy:~/growstuff$ ack Skud
app/models/planting.rb
90:  # stringify as "beet in Skud's backyard" or similar

app/models/harvest.rb
107:  # stringify as "beet in Skud's backyard" or similar

CONTRIBUTORS.md
18:- Alex Bayley / [Skud](https://github.com/Skud)
```
That text isn't part of the codebase afaict; but present in the link. What controls that?

**Comment by maco** [comment]
It's probably in the CMS

**Comment by CloCkWeRX** [comment]
Will be blocked by #3275

**Comment by CloCkWeRX** [comment]
Fixed wiki links on the page, took out some of the business language.

Going to close for now, but if you want to edit more the CMS is fixed.
