### ISSUE TITLE
Explore edible plants dataset

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#2616]
https://www.reddit.com/r/nutrition/comments/iead1d/catalogue_of_all_the_worlds_edible_plants/?utm_medium=android_app&utm_source=share

CC BY 3.0 it seems. Probably a strong overlap with the crop lists we have.

**Comment by le-jun** [comment]
Post removed, found what seemed to be the linked content anyway : [Database from Food Plants International](https://fms.cmsvr.com/fmi/webd/Food_Plants_World).

**Comment by CloCkWeRX** [comment]
https://github.com/Growstuff/growstuff/pull/3559 instead.
