### ISSUE TITLE
Invalid swagger

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#2743]
https://www.growstuff.org/api-docs/index.html

Debug via https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fwww.growstuff.org%2Fapi-docs%2Fv1%2Fswagger.json

```
{"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^/\" does not match input string \"\"","schema":{"loadingURI":"#","pointer":"/properties/basePath"},"instance":{"pointer":"/basePath"}}]}
```

**Comment by CloCkWeRX** [comment]
b1bb1a4b95c8f8f5e0cc1dbda7e3c508aadc2169

**Comment by cesy** [comment]
https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fstaging.growstuff.org%2Fapi-docs%2Fv1%2Fswagger.json gives us a new issue: {"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://staging.growstuff.org/api-docs/v1/swagger.json"}]}
This is possibly because Heroku no longer offers SSL on free dynos, so accessing staging throws a certificate error.

**Comment by CloCkWeRX** [comment]
Try https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fwww.staging.growstuff.org%2Fapi-docs%2Fv1%2Fswagger.json - should be fine as soon as we get staging deployed

**Comment by CloCkWeRX** [comment]
Invalid; but for new reasons:
```
{
"schemaValidationMessages": [
{
"level": "error",
"domain": "validation",
"keyword": "uniqueItems",
"message": "array must not contain duplicate elements",
"schema": {
"loadingURI": "http://swagger.io/v2/schema.json#",
"pointer": "[/definitions/parametersList](https://validator.swagger.io/definitions/parametersList)"
},
"instance": {
"pointer": "[/paths/~1crops/get/parameters](https://validator.swagger.io/paths/~1crops/get/parameters)"
}
}
]
}
```

**Comment by CloCkWeRX** [comment]
Yet more duplicates!
https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fwww.staging.growstuff.org%2Fapi-docs%2Fv1%2Fswagger.json

**Comment by CloCkWeRX** [comment]
Happier: https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fwww.staging.growstuff.org%2Fapi-docs%2Fv1%2Fswagger.json
