### ISSUE TITLE
GET crops/seeds/members by coordinates/location input

### ISSUE THREAD

**Issue by sbutler-gh** [Growstuff/growstuff#2940]
I would love to be able to send an API request like

`/api/v1/crops/{lat: X, lon: Y}`
`/api/v1/seeds/{lat: X, lon: Y}`

And return the crops/seeds being grown close to that specific location.  I'm new to API development, so I'd be glad to contribute on something like this as well, and learn along the way.

**Comment by CloCkWeRX** [comment]
Duplicate of #585 - but yours is more detailed. Merging.
