### ISSUE TITLE
ICANN verification

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3059]
"You have reached a domain that is pending ICANN verification."

![image](https://user-images.githubusercontent.com/365751/170467494-cffd9a10-3c7d-4f4f-a9fd-4fbe5d21e2a1.png)

What even.
@cesy @Br3nda - any suggestions here? Happy to throw a few dollars at it to stop what appears to be a weird MITM attack by the domain name authority.

**Comment by cesy** [comment]
Weird, I haven't noticed anything about this from DNSimple, very happy for
you to log in there and check it - do you already have the details?

**Comment by Br3nda** [comment]
oh weird - can you check with the registrar we bought from?

**Comment by cesy** [comment]
Found it, verification emails were going to Skud's old address which no
longer exists, I've updated it to me, should be back online soon.

**Comment by cesy** [comment]
CloCkWeRX, I can't seem to find your email address to send you details
directly for future reference just in case, can you send to maintainers@ so
we have it handy, please? I can then add you to shared passwords etc.

**Comment by Br3nda** [comment]
there's an email on the git commits. (i won't post here)

**Comment by CloCkWeRX** [comment]
Sorted, re access/emails/etc.
