### ISSUE TITLE
Update sass

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#3129]
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

Any opinions which way we should go?

**Comment by CloCkWeRX** [comment]
I honestly haven't understood this warning in a few other projects, as at first it was "sass" is deprecated -> sassc; but then it cropped up for sassc too.
