### ISSUE TITLE
 selector :link must be an instance of String or Symbol. This will raise an error in a future version of Capybara.

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3155]
Via https://github.com/Growstuff/growstuff/actions/runs/3409912058/jobs/5672250461

/home/runner/work/growstuff/growstuff/vendor/bundle/ruby/3.0.0/gems/capybara-3.38.0/lib/capybara/selector/selector.rb:69: warning: Locator Member:#<Member id: 12, email: "chauncey@jacobson.info", created_at: "2022-11-07 11:32:47.666012022 +0000", updated_at: "2022-11-07 11:32:47.666012022 +0000", login_name: "UMRBDAEE", slug: "umrbdaee", tos_agreement: true, show_email: false, location: nil, latitude: nil, longitude: nil, send_notification_email: true, bio: "I love seeds", plantings_count: nil, newsletter: nil, send_planting_reminder: true, preferred_avatar_uri: "https://secure.gravatar.com/avatar/d021434aac03a7f...", gardens_count: nil, harvests_count: nil, seeds_count: nil, discarded_at: nil, photos_count: nil, forums_count: nil> for selector :link must be an instance of String or Symbol. This will raise an error in a future version of Capybara. Called from: /home/runner/work/growstuff/growstuff/spec/views/scientific_names/edit.html.haml_spec.rb:20

**Comment by italopires** [comment]
Hi @CloCkWeRX, I'd like to solve this issue, could you assign that to me?
