### ISSUE TITLE
Evaluate Heroku pricing or alternatives

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3157]
Starting November 28th, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.
If you have apps using any of these resources, you must upgrade to paid plans by this date to ensure your apps continue to run and to retain your data. For students, we will announce a new program by the end of September.  [Learn more](https://blog.heroku.com/next-chapter)

**Comment by cesy** [comment]
I've emailed the address quoted to ask for free non-profit options and had no response. At the moment all the DNS and Heroku bills are coming to me, but if they're going up a lot, it would be good to share it out.

**Comment by cesy** [comment]
Heroku have now given us 3 months free, I've updated the settings for staging to the new eco dynos, and two other maintainers have volunteered to chip in, so I think we're okay for now, but we should try and remember in 3 months' time to ask Heroku for more free time.
