### ISSUE TITLE
Deploy failing

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#3205]
Downgrading ruby from 3.1.3 to 3.1.2 didn't solve it, staging is still failing. Last working build was on https://github.com/Growstuff/growstuff/commit/5b5861fc9fd3b94ad82c73aeb2d37772a5de0aff

https://dashboard.heroku.com/apps/growstuff-staging/activity/builds/f5954b0c-85d3-4fe1-b679-6099ed3c90af was our last success
https://dashboard.heroku.com/apps/growstuff-staging/activity/builds/acc453d5-4182-41ab-8433-682e89179d82 is the newest failure, having reverted the changes that appeared to cause the failure.

I'll try https://devcenter.heroku.com/articles/bundler-version#known-upgrade-issues next

**Comment by cesy** [comment]
https://devcenter.heroku.com/articles/ruby-support#libraries claims we should be getting bundler 2.x since we have 2.x in our Gemfile.lock, but that's not what's happening, we're getting 1.x from Heroku for some reason and then it falls over since that is old and we're set up for 2.x.

**Comment by CloCkWeRX** [comment]
Fixed, deployed to staging
