### ISSUE TITLE
Fix broken links to deprecated Wiki

### ISSUE THREAD

**Issue by skullbunnygalaxy** [Growstuff/growstuff#3247]
A number of links, both in the GitHub markdown and the website, are broken due to linking to the old wiki. 

**Examples**
Page: https://www.growstuff.org/about
Broken Link: ` For more information about Growstuff, <a href=" http://wiki.growstuff.org/index.php/About%20Growstuff">our wiki page</a>`

Page: https://github.com/Growstuff/growstuff/blob/dev/README.md#for-coders
Broken Link: `We encourage [pair programming](http://wiki.growstuff.org/index.php/Pairing), especially for newer developers.`

Recommend searching code bases for all old wiki links and replacing either with [relevant wayback machine  links](https://web.archive.org/web/20150910121421/http://wiki.growstuff.org/) or updated [links to github wiki](https://github.com/Growstuff/growstuff/wiki).

**Comment by CloCkWeRX** [comment]
Also> For detailed crop wrangling guidelines, please consult the [crop wrangling guide](http://wiki.growstuff.org/index.php/Crop_wrangling) on the Growstuff wiki

**Comment by CloCkWeRX** [comment]
Something annoying with the CMS and saving pages, will have to dig into the error logs.

**Comment by CloCkWeRX** [comment]
```
2023-03-13T01:45:59.557373+00:00 app[web.1]: [9aad28f6-90d9-41a0-910e-10b7badd924b]
2023-03-13T01:45:59.557387+00:00 app[web.1]: [9aad28f6-90d9-41a0-910e-10b7badd924b] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "active_storage_attachments" does not exist
2023-03-13T01:45:59.557388+00:00 app[web.1]: LINE 8:  WHERE a.attrelid = '"active_storage_attachments"'::regclass
```
