### ISSUE TITLE
Codespace config doesn't do migrations or ES properly

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#3414]
Steps to reproduce:
Create a new codespace on a branch, e.g. a recent pull request
bundle exec rails s
Open the browser
See an error that it needs to do database migrations first
Try bundle exec rails db:migrate or bin/rails db:migrate RAILS_ENV=development

Get error:
== 20191226051019 ElasticIndexing: migrating ==================================
-- indexing crops
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Failed to open TCP connection to elasticsearch:9200 (getaddrinfo: Name or service not known)
/workspaces/growstuff/db/migrate/20191226051019_elastic_indexing.rb:6:in `up'

We should probably update our standard codespace config to fix this but I don't have the time to figure it out today.

**Comment by CloCkWeRX** [comment]
https://github.com/Growstuff/growstuff/blob/dev/.devcontainer/docker-compose.yml#L47 is where it should be starting up. 

Relevant snippets from container build log
```
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:7.4.0)...
7.4.0: Pulling from elasticsearch/elasticsearch
...
Creating elasticsearch               ... done
Creating growstuff_devcontainer_db_1 ... done
```

And manually accessing the container via a proxied port shows the "elasticsearch is up" content I would expect.
![image](https://github.com/Growstuff/growstuff/assets/365751/bbea052e-6eca-4d19-afa3-356d6320fef4)

So it's just a matter of making sure the dev container can 'see' elasticsearch

**Comment by CloCkWeRX** [comment]
Oops, meant to make that a PR.

Inside the container, I can certainly see elasticsearch. But after ~5 minutes it was stopping.
```
@CloCkWeRX ➜ /workspaces/growstuff (dev) $ curl http://elasticsearch:9200/
{
  "name" : "d6bd0e6b09ba",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "sGQ_hRW8S8CQwCNUGWgPkg",
  "version" : {
    "number" : "7.4.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "22e1767283e61a198cb4db791ea66e3f11ab9910",
    "build_date" : "2019-09-27T08:36:48.569419Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by CloCkWeRX** [comment]
Annoyingly, logs dont really help. But trying with increased machine size:

![image](https://github.com/Growstuff/growstuff/assets/365751/aee6f02d-abe9-405d-84f2-a3d8fb8135b0)


(F1 -> Change machine size)

**Comment by CloCkWeRX** [comment]
This seems to be working for me for day to day dev. Not doing heaps with elasticsearch, but rspec is happy.
