### ISSUE TITLE
Record Harvest > Uses time_ago_in_words instead of "days ago/today"

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3543]
https://www.growstuff.org/harvests/clockwerx-cabbage-f69a300d-ae34-4b89-8856-5cf006f48e19

Record new harvest from planting

![image](https://github.com/Growstuff/growstuff/assets/365751/cd34c866-929b-4e71-a164-1d77c2be06d9)

Expected:
Renders as "Today"

Actual:
Renders as 8 hours ago (time.now - date.to_time?)

**Comment by Br3nda** [comment]
are you in UTC+8? 
i usually see it 12 or 13 hours wrong (depending on daylight savings)
so I suspect a UTC to local time mix up

**Comment by CloCkWeRX** [comment]
t.date "harvested_at"
