### ISSUE TITLE
Member > Seeds > Add a better UX when there are no seeds

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3618]
https://www.growstuff.org/members/clockwerx/seeds

![image](https://github.com/Growstuff/growstuff/assets/365751/7c9e5250-439f-4029-a332-c193fcceb615)

**Comment by bennett-zink** [comment]
Hey @CloCkWeRX, would it be cool if I added a UX for when there are no seeds, plantings, or harvests since they are all pretty similar.
