### ISSUE TITLE
Cannot Register New Account

### ISSUE THREAD

**Issue by spencerthayer** [Growstuff/growstuff#3627]
The URL to create a [new account ](https://www.growstuff.org/members/sign_up) is giving me this error message, "`We're sorry, but something went wrong.`"

**Comment by CloCkWeRX** [comment]
Will check shortly, though annoyingly this should have spec coverage.

**Comment by CloCkWeRX** [comment]
ActionView::Template::Error (No site key specified.):
2024-02-04T21:16:54.997847+00:00 app[web.1]: [a2028a9a-1d65-4224-88e5-8ba275855f3c]     31: 
2024-02-04T21:16:54.997848+00:00 app[web.1]: [a2028a9a-1d65-4224-88e5-8ba275855f3c]     32:       -# START add reCAPTCHA


Deployment error on my part re #3586

**Comment by CloCkWeRX** [comment]
@cesy can you take a look.
I registered an enterprise recaptcha key, put in the secrets etc, however:
https://www.growstuff.org/members/sign_up

Invalid key type.

Ditto V3 key.

**Comment by CloCkWeRX** [comment]
https://github.com/ambethia/recaptcha/issues/414

**Comment by spencerthayer** [comment]
Thanks for looking into this so quickly.

**Comment by CloCkWeRX** [comment]
Just got it working - give it a go now

**Comment by CloCkWeRX** [comment]
@cesy set up a v2 key in heroku. Please review/add to 1password if you are happy with that, or I can share the relevant project with the maintainers

**Comment by cesy** [comment]
Sounds good, thank you for sorting this.

**Comment by cesy** [comment]
I've updated 1P accordingly, and @CloCkWeRX  and other maintainers should be able to see it there.
