### ISSUE TITLE
Bug: 404 on "add a bio"

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3667]
https://growstuff-staging.herokuapp.com/members/clockwerx/edit

Not found when I click "add a bio"

_Originally posted by @CloCkWeRX in https://github.com/Growstuff/growstuff/issues/3666#issuecomment-1987207104_

**Comment by CloCkWeRX** [comment]
https://github.com/Growstuff/growstuff/blob/938084612ee48681b45b1b59929979c80f425bc5/app/views/members/_bio.html.haml#L4

**Comment by bennett-zink** [comment]
Hey @CloCkWeRX, I'm new to open source and I would like to contribute to this project. Is it cool if I contribute to this issue?
