### ISSUE TITLE
Show edited date/time on posts/comments

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#476]
If someone edits a post or a comment, we should expose that fact to readers. It should say "Edited at [timestamp]" somewhere.

(After we implement hierarchical posts, this would no longer apply to comments, of course.)

**Comment by gmmowry** [comment]
I'll be seeing if I can figure this out today.

**Comment by CjayBillones** [comment]
Hi! Looks like there's no updates on this so I took the time in submitting my own PR. Will you check if this is what you want to happen @Skud ? :)

**Comment by cesy** [comment]
#704 was an earlier version of this.
