### ISSUE TITLE
Put cursor in textarea when writing a post/comment

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#478]
When I go to write a post or comment, it would be nice if my cursor was automatically positioned in the text box.

**Comment by pgblu** [comment]
We are working on this one - have made the change and are going through the tests

[pgblu](https://github.com/pgblu) & [nicole-a-tesla](https://github.com/nicole-a-tesla)

**Comment by mauricio-gonzalez** [comment]
@Skud checkout the PR :)

**Comment by pozorvlak** [comment]
@mauricio-gonzalez's PR #747 fixed this for posts but not comments; @manmeetsingh's PR #727 fixes it for both cases.

**Comment by pozorvlak** [comment]
Fixed in #727 and #747.
