### ISSUE TITLE
Delete many notifications at once

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#480]
instead of having to delete every notification individually, it would be nice if there were checkboxes and you could delete all checked items.  There should also be a "select all" option.

**Comment by bestest-mensch** [comment]
@Br3nda Is this still something that needs to be worked on? If so I'd like to pick up this issue.

**Comment by Br3nda** [comment]
please go ahead - they're messages now as part of mailboxer gem.

**Comment by bestest-mensch** [comment]
@Br3nda What do you think about something like this?

Web:
![Screen Shot 2019-10-05 at 10 29 02 AM](https://user-images.githubusercontent.com/16200338/66257150-085f1500-e75b-11e9-991e-fe5e4580b2de.png)

Mobile:
![Screen Shot 2019-10-05 at 10 28 47 AM](https://user-images.githubusercontent.com/16200338/66257151-0ac16f00-e75b-11e9-940a-0d4ac32438ee.png)

**Comment by Br3nda** [comment]
Awesome. Yes
