### ISSUE TITLE
Member profile editing forgets what tab you're on

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#497]
When you are editing your member profile, if you are in a tab other than the first one (eg. "Email" or "Password"), and you save some changes, the page reloads and puts you back on the first tab ("Profile").  It would be nice if it remembered which tab you were on.

**Comment by CloCkWeRX** [comment]
Still a (very minor) issue.
https://www.growstuff.org/members/edit -> save will reload.

Instead, on activating the tab it should rewrite the current URL to:
https://www.growstuff.org/members/edit#email

How to:
https://webdesign.tutsplus.com/how-to-add-deep-linking-to-the-bootstrap-4-tabs-component--cms-31180t

**Comment by fbuys** [comment]
Hey, I'll claim this one

**Comment by CloCkWeRX** [comment]
@bennett-zink this one might another good one to poke at

**Comment by domthor** [comment]
Hi, I would like to contribute to this issue. I think I may have found a solution to the issue after following the how to guide linked above. I can create a pull request with those changes soon if someone would like to take a look.

**Comment by CloCkWeRX** [comment]
@domthor https://github.com/Growstuff/growstuff/blob/dev/README.md#want-to-contribute
