### ISSUE TITLE
Support SSO between Growstuff and Discourse

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#499]
People should be able to login to http://talk.growstuff.org using their Growstuff account.  Discourse supports SSO but we have to implement it a certain way. 

Potentially useful:

https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045
http://stackoverflow.com/questions/25478510/incorporating-discourse-sso-with-existing-rails-site-with-devise
https://github.com/mikamai/discourse-doorkeeper-sso

**Comment by Br3nda** [comment]
Closed. Discourse is shutdown
