### ISSUE TITLE
Track types of gardens (permaculture, hydroponic, etc)

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#500]
We should allow people to select what type each of their gardens is, eg.

```
organic
conventional
container
vertical
greenhouse
rooftop
no-dig
raised bed
wicking bed
permaculture
hydroponic
aquaponic
orchard
food forest
biodynamic
```

They should be able to choose more than one.  Selection should be via a series of checkboxes (I think) on the garden new/edit form.

Note that we probably want these to be actual data in the database so that you can easily see "all food forest gardens" or similar.  See plant_parts for an example of how this might work.  Note that only admins should be able to add/edit/remove garden_types.

**Comment by Br3nda** [comment]
Go for it - a patch would be welcome

**Comment by Br3nda** [comment]
There's some work already in #1747
It just needs tidy up to be accepted.
