### ISSUE TITLE
Connect harvests with plantings

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#501]
On the harvest form, when I select a crop, a list should appear of my plantings which match that crop. For example, I choose "tomato" and shows me a list of all my tomato plantings, with enough info to choose from them, and a checkbox next to each one.  Note that "matching plantings" should include sub-varieties, for instance if I pick "tomato" it should also match on plantings of "roma tomato" and "beefsteak tomato".

I should then be able to select one or more of those plantings -- selecting multiples is important because I might eg. walk around my garden collecting a range of different types of tomatoes rather than just one kind.  

When I submit the form, the harvest should be associated with the planting(s). Harvests should appear on the relevant planting page, and vice versa.

**Comment by Br3nda** [comment]
Harvests are now linked to plantings.
