### ISSUE TITLE
create "thumbnail" views for plantings, harvests, seeds, gardens and display on index pages

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#518]
It would be good if there were "thumbnail" views for plantings, harvests, seeds, and gardens that were like the crop ones -- a photo with basic info underneath -- that we could use to display on index pages such as http://growstuff.org/harvests instead of the current ugly table, and anywhere else where these things are shown en masse.

Note 1: there is currently a planting thumbnail but it's terrible. Blow it away.

Note 2: we currently only have photos for harvests and plantings, so if seeds/gardens don't have photos yet (when you get around to doing this) then either implement that first, or else fork a new story for those ones and just do plantings/harvests.

Also look into the work @emmawinston is doing on PT #80970664 for improved crop thumbnail CSS.

Also seems related to PT #80970892

**Comment by GabrielSandoval** [comment]
Hi Skud, I would like to work on this one. I just need to know what basic info do you want to be displayed below the harvest/garden/seed photo.
