### ISSUE TITLE
Install Comfortable Mexican Sofa CMS

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#525]
This should be used for things like the TOS and other policies, FAQ, etc.  This depends on Rails 4 first, though.

**Comment by maco** [comment]
Hey @Skud since Rails 4 is now in, I'd like to grab this.

**Comment by Skud** [comment]
Ooh yes please go ahead! Grab me on IRC to discuss tho? I have a handful of thoughts I haven't documented properly.
