### ISSUE TITLE
SSL for signin/signup (and/or everywhere)

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#534]
We need to make sure that signup/signin are protected by SSL.  We might also want to use SSL everywhere; it's the way things are going these days.

**Comment by sha1sum** [comment]
This will require [proper setup of the Heroku SSL certificate](https://devcenter.heroku.com/articles/ssl-endpoint)

**Comment by cesy** [comment]
So first step is to buy the actual SSL certificate, needing key and CSR from Heroku which can be got by any admin - @Skud, have you already bought a cert, or can you, or would you like one of us to?

**Comment by drzax** [comment]
This has been made easier by the public launch of https://letsencrypt.org/ so it might be worth a re-visit of this ticket.

TLS is really non-negotiable now (at least authentication is concerned).

**Comment by cesy** [comment]
@maco, what's our next step here?

**Comment by maco** [comment]
1. get some premium features like photo upload so people give us money
2. turn on the more expensive hosting from Heroku that would let us have SSL
3. use that money from premium features to pay for the more expensive
hosting

Basically: backburner.

**Comment by drzax** [comment]
Or you could put Cloudflare in front of the site and get SSL for free.

*Simon Elvery*
+61 408 155 856 <+61%20408%20155%20856>
simon@elvery.net
elvery.net
storieswithdata.community
@drzax <http://twiter.com/drzax>
https://keybase.io/drzax

**Comment by Br3nda** [comment]
Done
