### ISSUE TITLE
Seed trading: specify costs

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#536]
When I say I'm prepared to trade seeds, it would be nice to be able to specify whether I'll send them for free, for the cost of postage, or for money.  This should appear on the seed form, below "will trade locally" etc.

Ideally, if you choose "for money", a secondary field should appear to specify the price, but for now it's probably best to just leave that in the description.

Note: we should do some user research before implementing this, not to mention checking legalities (as seedbanks have had legal issues lately), so please don't dive in before that's done!

**Comment by CloCkWeRX** [comment]
Closing for now, as most people posting seeds to trade haven't put in pricing or similar.
