### ISSUE TITLE
Companion planting

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#538]
People often request that we suggest companions.  This isn't something we would define in the system, it's something we'd want to get from members' data. Personally, I'd also like to encourage people to specify _why_ something works well as a companion, because what works in some climates/soils/environments might not work in others, or people might want to find stuff that makes practical sense (eg. root depth, pest repellent, shade) vs companion pairings that are mostly mystical in nature.

Suggested:
- When you add a planting, you can specify a companion from a dropdown list of other plantings in that garden
- You can also give a description/notes on the companion relationship, eg. "beans provide shade for lettuces in hot weather"
- We can show a summary of companions on the crop detail page, eg. "African marigold (33), garlic (23), basil (21)" and if you click through you see details of the notes people have added about the companion relationship.

**Comment by gre** [comment]
I was about to raise this issue and found it here.

I'm looking for an open source DB I could rely on that would provide me this data. I understand the idea to not hardcode this, but eventually I still wish we could extract a relatively reliable list.

Maybe we could cross the companion list of many different source and obtain a relatively reliable list?
I think it would have good potential we establish a few independent trust lists.. I don't know if gardening works like that as it's very fuzzy logic everywhere^^ and contradictory opinion.. but personally I would love to have a few data library e.g. published on NPM.

I'm thinking many things could be solved and independent libraries could be created and public-domain-ed for everyone to reuse
– for instance, I think we should all have our data using the scientific names everywhere and have translation for different langs (i'm French).

> ( context: I'm writing an app that "log" everything I do in my garden, and then visualize that (currently in https://gre-jardin.surge.sh/map – it's VERY specific to myself, not meant to be used by anyone but me at the moment^^) – I was thinking working on a constraint planner algorithm that would tell me what to plant where for the next year, taking into account many things like the previous year plant (culture rotation) and the companion planting.. just an idea but it would be fun! )

**Comment by Br3nda** [comment]
Found a source if companions by species
https://en.m.wikipedia.org/wiki/List_of_companion_plants
