### ISSUE TITLE
Maintenance/error pages

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#539]
Heroku offers the option of redirecting from an app hosted on heroku to another page hosted elsewhere for cases of errors and maintenance. We should make pages like the defaults they provide (http://s3.amazonaws.com/heroku_pages/maintenance.html & http://s3.amazonaws.com/heroku_pages/error.html), host them on another provider (maybe as status.growstuff.org or similar), and redirect to them through Heroku.  The page could also show a recent feed of Growstuff's twitter, which is where information about maintenance windows or other problems is likely to be posted.

**Comment by Br3nda** [comment]
done in #1258
