### ISSUE TITLE
Show photos based on "likes"

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#540]
I want to be able to "like" a photo (i.e. click on a little icon/link to indicate that I think it's a good pic). These "likes" should be recorded and used to choose which photos to display on the crops page.  This solves the problem of often having pictures of indistinguishable seedlings as the default crop photo.

When member A "likes" member B's photo, member B should get a notification.

See also: list of "reasons" on #541.

**Comment by Br3nda** [comment]
Not sure about the notifications. It would trigger an email right now, and that could be lots of emails.
