### ISSUE TITLE
"like" posts

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#541]
I should be able to "like" a post to indicate that I think it's helpful/interesting/whatever.

When I click "like" there should be a secondary thing to click that lets me say why I liked it:
- helpful
- interesting
- beautiful
- funny
- sympathy
- ???

(We probably want to discuss this list before implementing it. We might also want to let people choose multiples?  See Ravelry and Slashdot for design inspiration.)

We can then use this info to show eg. the most helpful posts related to a given crop.

When member A "likes" member B's post, member B should get a notification.

Note: we probably also want to apply this "why I liked it" thing to #540 (photo likes).

**Comment by maco** [comment]
I'm a fan of how Ravelry does it, which doesn't include a notification. Those might get to be excessive as the site grows. However if the helpful/interesting/etc-counts show up on the posts when viewing "My Posts" that'd be nice. You have to click through to the thread to see that info on Ravelry.

**Comment by Skud** [comment]
Agreed that it could be spammy. On the other hand we are having a 
problem with getting people with accounts to visit GS regularly, and 
occasional email reminding them of things going on on the site would 
probably help!

On 30/01/2015 2:50 pm, Mackenzie wrote:
>
> I'm a fan of how Ravelry does it, which doesn't include a 
> notification. Those might get to be excessive as the site grows. 
> However if the helpful/interesting/etc-counts show up on the posts 
> when viewing "My Posts" that'd be nice. You have to click through to 
> the thread to see that info on Ravelry.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/541#issuecomment-72150174>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by cesy** [comment]
Making the list configurable by an admin and allowing you to choose multiple items sounds best. And notifications are a good optional extra that could be added once this is working, or included in the existing activity emails.

**Comment by Br3nda** [comment]
> I should be able to "like" a post to indicate that I think it's helpful/interesting/whatever.

This portion is done

**Comment by CloCkWeRX** [comment]
#2079

**Comment by CloCkWeRX** [comment]
Likes for posts exists.
