### ISSUE TITLE
Show last login date on member profile

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#546]
When I look at someone's profile page, I should see the last time they logged in/visited the site.

Note: Miles has already done some work on this and you can find it in his github repo.  He writes:

The old code (with history rewritten to apply on top of the non-broken version, rather than the other way around) can still be seen at https://github.com/pozorvlak/growstuff/compare/story_profile, if whoever does the "show last login date" story wants to build on it.

**Comment by pozorvlak** [comment]
Fixed in #753.
