### ISSUE TITLE
Plural names for crops

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#547]
There should be an optional field in the database for a plural name for crops if the Rails inflector is wrong. For instance, harvest.to_s is currently saying "achiotes" and "garlics".

The plural name should show up on the crop view page for wranglers, and on the edit screen, eg. "Default plural is garlics. Override? [     ]"

The Rails inflector should be made, somehow, to use these plurals instead of just making shit up.

**Comment by Br3nda** [comment]
done in #1296

**Comment by Br3nda** [comment]
done in #1744
