### ISSUE TITLE
Cleanup tests to use config.currency rather than AUD

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#558]
Some of the tests for the shop and orders system are checking that prices are displayed in AUD, rather than checking them against the configured currency. This should be refactored.

**Comment by krio** [comment]
I believe the referenced issue allows this to be closed. I don't see anymore tests that reference a currency directly without using the config.

**Comment by cesy** [comment]
Yeah, this should have auto-closed but Github is fussy about the wording of the link.
