### ISSUE TITLE
Harvests RSS

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#565]
there should be an RSS feed for harvests, same as for seeds, plantings, etc

**Comment by robotscissors** [comment]
@Skud and @Br3nda, I am new to this repository, could I take this issue?
Could you clarify, are there already RSS feeds for Seeds and Plants?

**Comment by Br3nda** [comment]
Yes, there are ready rss feeds. Have a look on plantings#index using your browser. You'll see the rss link.
