### ISSUE TITLE
Add link from a member's seeds, plantings, and harvests to their profile

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#569]
If I look at a member's seeds page, eg. http://www.growstuff.org/seeds/owner/trishf42, there is no link to her member profile.

Same goes for plantings and harvests.

I think we're deliberately not showing the "owner" column in these cases -- it does show in the "Everyone's" view.  But in the one-person view, we should probably put that link somewhere outside the table.

**Comment by GabrielSandoval** [comment]
I'll work on this. :+1:
