### ISSUE TITLE
Consistent "card" based visual language

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#570]
We currently have "thumbnails" for members, crops, and plantings, usually called _thumbnail.html.haml in the relevant view directory.  It would be great if we could get better visual consistency around these, using the idea of [card based design](http://webdesignledger.com/trends-2/cardbaseddesign), and then use them more consistently throughout the site.

I feel like each card should have:

* a picture (or placeholder)
* a title
* some textual info (will vary)
* stats (will vary -- but eg. for a member this will be number of plantings, harvests, posts, etc)
* some actions (eg. edit, send message, etc)

It would be OK if some of this was in a popup and not immediately visible, depending on space considerations.

We should have cards for each major kind of thing in the system including:

* crops
* members
* gardens
* plantings
* harvests
* seeds
* posts

Once we have them, we should use them:

* on the relevant index pages eg. /crops /members /gardens /plantings /harvests /seeds
* when they're referenced from a different page, eg. when plantings are listed on a garden page or seeds listed on a crop page

**Comment by Skud** [comment]
Ping to @borracciaBlu ... I updated this issue to use the "card" language.

**Comment by borracciaBlu** [comment]
Good
