### ISSUE TITLE
One-click email unsubscribe

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#575]
At present you need to sign in to the site to unsubscribe from email notifications.  We should set up a one-click way of doing this.

**Comment by oshiho3** [comment]
I'm working on this.

**Comment by oshiho3** [comment]
How do we want this to behave?

<strong>1) Which type of emails do we want to include one-click-unsubscription link? eg. newsletter, planting reminders, inbox notifications</strong>

<strong>2) By clicking the link on an email, do we want</strong>

a) to turn off the particular email type only. 
eg. when clicking the "unsubscribe" link on planting reminder email, only planting reminder will be turned off.

b) to show a simple page with tick box options for disabling/enabling notifications.
eg. when clicking the link on planting reminder email, it opens up a page with tick boxes for planting reminder, inbox notification and newsletter. The user is only allowed to turn on/off email notifications but no other actions are permitted unless user manually logs in.

and/or

c) to login the user automatically and show edit email tab of user profile edit page. This will allow access to the site anywhere the user has access to.

**Comment by Skud** [comment]
1. Everything that is sent as a transactional email by Growstuff.  This does *not* include the newsletter but does include all other types of emails.  (The newsletter has its own one-click unsubscribe, through Mailchimp.)

2. That particular type, I think.  It would be good to have a link that says "Unsubscribe" and then you click it and it says "You have been unsubscribed from planting reminder emails.  If you wish to unsubscribe from other Growstuff emails, you may do so via your settings page."  (with a link for them to login and go to the settings page)

We *absolutely* do not want option C.  For one thing, it's not one-click; for another, it's a security risk if any emails are forwarded.

Speaking of security... the obvious thing is to have a link something like:

http://growstuff.org/member/unsubscribe?type=planting_reminder&member=Skud

(or possibly email=skud@example.com instead of member=Skud)

However, this would allow people to switch off emails for other people if they knew their username or email address, which would be a bad thing.  We should consider using a string that is not guessable, but which we can look up in the db.  For instance, hashing their email address with one of the timestamps on their member object, eg. the created_at or confirmed_at timestamps.  That's probably not Fort Knox level security but should be enough for these purposes.

Example:

Given a URL like: http://growstuff.org/member/unsubscribe?type=planting_reminder&member=Skud&check=4gsf7d689gsfd78tgsfgydbso7fs

    who = Member.find_by(:login_name => params[:member])
    if params[:check] == some_hash_function(who.created_at)
      who.email_unsubscribe[params[:type])
    else
      # raise an error message 
    end

**Comment by Skud** [comment]
Note: I'm also working on a notifications system redesign which might interact with this but I wouldn't sweat it too much at this point.

**Comment by Skud** [comment]
Btw in answer to your question 2, another option which you didn't mention was:

turn off ALL transactional emails, regardless of type (eg. planting reminders, comments, private messages, etc)

That is worth considering too.  But I think I prefer "turn off the specific type", if it's not hard to do.

**Comment by oshiho3** [comment]
Cool :-)

For security, I'm planning to encrypt the message using ActiveSupport::MessageVerifier which can encrypt a hash. So the link will look something like  http://growstuff.org/member/unsubscribe/OKnh8gH01asdfkl7....
This encrypted message will hold member_id, type, and expiry date (if we like).

I agree with you that turning off all transactional emails isn't probably be a good idea. It may annoy people rather than being convenient.

There won't be much code, so I won't worry about the notification redesigning too :)

**Comment by Skud** [comment]
Oh, interesting! That class looks like exactly what we need :)  I think 
member_id and type will be enough.

On 23/02/2015 5:51 pm, Shiho Takagi wrote:
>
> Cool :-)
>
> For security, I'm planning to encrypt the message using 
> ActiveSupport::MessageVerifier which can encrypt a hash. So the link 
> will look something like 
> http://growstuff.org/member/unsubscribe/OKnh8gH01asdfkl7....
> This encrypted message will hold member_id, type, and expiry date (if 
> we like).
>
> I agree with you that turning off all transactional emails isn't 
> probably be a good idea. It may annoy people rather than being convenient.
>
> There won't be much code, so I won't worry about the notification 
> redesigning too :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/575#issuecomment-75496109>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by pozorvlak** [comment]
What happens in the following scenario?

 - Alice gets an email from Growstuff.
 - She forwards it to Bob.
 - Bob clicks "unsubscribe".

**Comment by Skud** [comment]
Alice gets unsubscribed. I think that's an acceptable risk, and it's no different to many other services (eg twitter, mailchimp)

**Comment by oshiho3** [comment]
Can you get a clarification on all transactional emails?
When I looked at member's email profile page, send_notification_email and send_planting_reminder are the only options which members can turn on/off apart from newsletter which is outside the scope.

Are there any other types of emails I need to enable this functionality?

**Comment by Skud** [comment]
Those are the only ones at present, yeah.  There are going to be more 
when we break out notifications a bit more (eg. making a separate 
notification for follows).

A.

On 24/02/2015 3:50 pm, Shiho Takagi wrote:
>
> Can you get a clarification on all transactional emails?
> When I looked at member's email profile page, send_notification_email 
> and send_planting_reminder are the only options which members can turn 
> on/off apart from newsletter which is outside the scope.
>
> Are there any other types of emails I need to enable this functionality?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/575#issuecomment-75699189>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by pozorvlak** [comment]
As an amusing aside, this just happened to me! I forwarded an email from
Puppet Labs to a colleague, who unsubscribed me before he noticed that the
email had been forwarded.

**Comment by oshiho3** [comment]
Hi,
How should the page and email look like? Please see the below screenshots which is what I'm working on currently.

1) Unsubscribe page will appear after a user click <I>Unsubscribe</I> link.
![screen shot 2015-03-05 at 4 29 19 pm](https://cloud.githubusercontent.com/assets/7848188/6499753/d5aff7c0-c354-11e4-9d26-1981bdb0dbdc.png)

2) Inbox Notification message.
![screen shot 2015-03-05 at 4 38 33 pm](https://cloud.githubusercontent.com/assets/7848188/6499834/1be92102-c356-11e4-8e08-7760ec908179.png)

3) Planting Reminder message.
![screen shot 2015-03-05 at 4 37 17 pm](https://cloud.githubusercontent.com/assets/7848188/6499816/eebb248c-c355-11e4-8797-6cc4b666b0b5.png)

**Comment by oshiho3** [comment]
Another thing. How should I handle errors?

When the app receives wrong parameter, in this case is an encrypted string, generic errors such as "The page you were looking for doesn't exist." or "We're sorry, but something went wrong." will appear.
Should I add more code in order to make the message more customer friendly or keep it simple? Which is preferred?

**Comment by maco** [comment]
this went out in release 9
