### ISSUE TITLE
Set up OAuth for Growstuff login

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#589]
We should set up as an OAuth provider, so people can use us to login to other services.

**Comment by arealdeadone** [comment]
I would like to claim this issue. I have a fair experience in RoR

**Comment by arealdeadone** [comment]
Can I use a third party gem for setting up OAuth 2?

**Comment by pozorvlak** [comment]
Unless there's some problem with the particular gem (incompatible licence,
not on RubyGems...), then please go ahead!

**Comment by Br3nda** [comment]
Is the idea to be an OAuth provider or consumer?

**Comment by cesy** [comment]
Consumer

**Comment by CloCkWeRX** [comment]
We have this capability to login with other platforms.
To be the provider - login with your growstuff account - I think we aren't big enough/integrated enough with other places to be effective.

Closing for now unless there are strong objections.
