### ISSUE TITLE
Move wiki off Greenqloud

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#599]
With the demise of the mailing lists, the wiki is the only thing remaining on Greenqloud. Let's move it to somewhere that doesn't cost us (i.e. Skud's Dreamhost account, with setup on a separate shell account from her other stuff).  At the same time, we should upgrade the wiki to a more recent version.

**Comment by CloCkWeRX** [comment]
Is the wiki kaput by any chance?

http://www.isup.me/http://wiki.growstuff.org/index.php/Crop_wrangling suggests yes at the moment.


Still linked to in a bunch of places in dev though
```
$ ack-grep -l "wiki.growstuff"
app/views/crops/wrangle.html.haml
app/views/crops/_form.html.haml
app/views/scientific_names/_form.html.haml
app/views/alternate_names/_form.html.haml
app/views/support/index.html.haml
spec/views/crops/new.html.haml_spec.rb
CONTRIBUTING.md
README.md
```

**Comment by maco** [comment]
Very kaput. Greenqloud went away last year, and we didn't move the wiki off
of it in time, so it's gone. We need to build a new one here on GitHub, I
guess.

**Comment by CloCkWeRX** [comment]
If someone can whack the 'wiki' checkbox in the repo settings, I'll grab the old content from https://web.archive.org/web/20150910121421/http://wiki.growstuff.org/ and migrate it where its linked to.

**Comment by cesy** [comment]
Based on the discussion in the other thread, we should start building on either yours or Lindsey's repo, until we can get access to change the repo settings on master.

**Comment by pozorvlak** [comment]
I think this is done now?
