### ISSUE TITLE
Standardised harvest weights

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#601]
When a harvest is entered, the weight should be recorded in the user's preferred units but also stored as a conversion to a standardized unit (kg). This will make future statistical analysis of harvests easier.

This will also require a rake task to set the standardized weight of pre-existing harvests.

Task breakdown (from PT):

* add column to track standardised weight
* when a harvest is saved, fill in the standardised weight (probably before_save or something)
* write rake task to fill in standardised weights for older harvests
* include standardised weight in CSV downloads for harvests

**Comment by maco** [comment]
Scooting this to release 8 because it's already merged and therefore going out with release 8
