### ISSUE TITLE
Improve "request new crops" process

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#602]
As an ordinary Growstuff member, I want to be able to request crops by some mechanism other than posting in a forum.

Specifically, I should be able to use a variant of the "new crop" form, which asks me for as much detail as I have, then records that crop as "requested" or something but doesn't make it live until reviewed by a crop wrangler.

When a crop is requested, email should be sent to all crop wranglers letting them know about it.

As a crop wrangler, I should be able to see these pending crops on the crop wrangler page, and approve them (making edits if necessary).  Alternately, I should be able to reject a crop, providing a reason (eg. "not edible").  It would be good to have a list of standard rejection reasons to select from plus "other".

When the crop is approved, an email should be sent to the requester letting them know it's been added and providing links to plant, harvest, or stash seeds.  If rejected, an email should be sent with the reason.

Some notes:

1) We might want to ease up on validation a bit, eg. to allow them to request it even if they don't know the Wikipedia link or whatever

2) Be careful of race conditions if multiple crop wranglers both come to deal with a new crop simultaneously.

3) We'll need some discussion about how to actually track the state of the crop. I'd suggest that we simply have a "status" field which can be "requested", "approved", and "rejected". All current crops should be set to "approved".

4) We'll also need a requested_by field to track who asked for a crop so we can email them.

5) Keep in mind that scientific names will need to be managed in similar ways.

6) We'll want to modify the help text on crops/new to be targetted at the general public vs wranglers. OTOH, crops/edit should be wrangler-specific.

**Comment by tygriffin** [comment]
Quick update: @robertlandreaux and I worked on this about a week ago and made a lot of progress. We're going to pair again in Feb and finish this up. I intend to make a PR the weekend of Feb 7th, so it'll be ready in time for [release 8](http://talk.growstuff.org/t/release-8-planning-thread/193).
