### ISSUE TITLE
Planting advice charts

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#603]
Show planting advice (sunniness, planted_from) as little histograms rather than numbers.

There's a lot of discussion over on PT so here's a link: https://www.pivotaltracker.com/story/show/53219527

**Comment by tygriffin** [comment]
Quick update: @Marlena gave me a sneak peek of this during a pairing session this morning. It looks really coherent and well tested - not at all easy with d3! @Marlena is going to make a PR of her work in progress soon so we'll have something to chew on.

**Comment by Marlena** [comment]
@tygriffin Thank you for the kind words.  I've worked so hard on this.  Working on a pull request.

**Comment by Skud** [comment]
\o/ I'm really looking forward to this!  You might also like to look at 
these wireframes 
(http://talk.growstuff.org/t/aspirational-wireframes-for-the-crop-detail-page/204) 
for an idea of how these charts fit into some future ideas for the crop 
details page.

On 26/01/2015 2:46 pm, Marlena Compton wrote:
>
> @tygriffin <https://github.com/tygriffin> Thank you for the kind 
> words. I've worked so hard on this. Working on a pull request.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/603#issuecomment-71411680>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/
