### ISSUE TITLE
Set height/width on crop thumbnail images

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#604]
If there's a problem with Flickr you see something like this:

![screenshot 2014-12-13 10 38 29](https://cloud.githubusercontent.com/assets/103436/5421225/4332e474-82b4-11e4-9d32-334fcec0d195.png)

We should set the dimensions of this image explicitly to prevent the thumbnail formatting getting screwed up, even if we can't do anything about the broken Flickr image.

**Comment by gmmowry** [comment]
Hi, I'll be looking at this today and hopefully will have it up/working by the end of the day!

**Comment by gmmowry** [comment]
It looks like this has been fixed, is that the case? Looking at the website the thumbnails are formatted equally.

**Comment by Skud** [comment]
I don't believe it's been fixed, but it will probably only show up if there is a Flickr failure and you see the Flickr image as in the screenshot above.  That might be an intermittent problem so it might be hard to test.

One way to force it would be, on your dev box, to add a photo to something and then go in via "rails c" and manually change that photo's thumbnail URL to point to something that doesn't have a square aspect ratio (just any pic out there on the web that is not square).  That should then start showing up in the crop listing and you'll be able to see if the problem is still there.

**Comment by maco** [comment]
No, I think it is fixed. On http://growstuff.org/crops arugula is a Flickr error ( https://s.yimg.com/pw/images/en-us/photo_unavailable_q.png ), not a missing image. Missing image is what shows for chard here: http://growstuff.org/crops?page=2

I think this commit fixed it: https://github.com/Growstuff/growstuff/commit/bb6e798bced5668cac1b9dba0563b5583bb38c68

**Comment by arun1595** [comment]
@maco I guess this issue can be closed.
