### ISSUE TITLE
Track seed trades

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#605]
As a member, when I request a seed trade from another member, currently all that happens is they get a PM from me, and we then sort things out between ourselves.

It would be good to actually track seed trades in the database.

A seed trade would have:
- seed_id -- the seeds being requested
- requester_id -- the member requesting it
- message -- text message from one person to another
- address -- postal address to send to (NOTE security issues! might want to have SSL before we do this; also make sure not to expose it via API etc)
- requested_date
- accepted_date
- declined_date
- sent_date
- received_date

The process would be:
- A requests seeds from B
- B is notified of request
- seed trade shows up in lists visible to both A and B (eg. "my seed trades")
- B accepts request; accepted_date is set
- OR B declines request; declined_date is set
- B can then mark as sent when they've been sent; sent_date is set
- A marks it as received when it has been; received_date is set

**Comment by gustavor-souza** [comment]
Working on it

**Comment by CloCkWeRX** [comment]
A related feature that we're lacking around trading seeds is a seed-trade-listing page ("Show me all seeds everywhere *currently available for trade*"). We have fragments in a few places, but it's not terribly easy to find and begin a valid trade at the moment.
