### ISSUE TITLE
Track seed vendors

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#607]
(See also: #606, track seed sources)

If we're tracking where seeds come from it would be great to have details on vendors, eg. seed catalogues, retail outlets, etc, so people can find out eg. "where can I buy $obscure_herb near $location".

SeedVendor should probably have:
- name
- website URL
- location (where are they based)
- has_catalogue (boolean)
- catalogue address (i.e. postal address)

Then there should be something so that a vendor has_many retail outlets, so you can show bricks and mortar outlets.

**Comment by CloCkWeRX** [comment]
Well, we haven't managed to implement this and no open standards have really emerged for this beyond just googling it.

Going to close for now.
