### ISSUE TITLE
Links in devise emails point to growstuff.org, even on staging

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#609]
In devise-generated emails (eg. signup confirmation, forgot password, etc) the links all go to growstuff.org even if you're on staging or another such platform.  These emails should instead point to the relevant instance of growstuff, eg. staging.growstuff.org or whatever is appropriate.

Workaround: 
1. click the link
2. you wind up on growstuff.org with an error message
3. edit the URL in your browser to replace "growstuff.org" with the correct site
4. it should work

**Comment by cesy** [comment]
Do we have any tests of emails yet? I can't see them in the features folder apart from the planting reminder one, though it looks like we couldn't test this particular issue anyway due to the links issue you mention in planting reminder code comment.

**Comment by Skud** [comment]
I think there are some tests in spec/mailer as well.  But feature tests 
are the best place to look for them, yeah.  I thought we had something 
else where we were testing emails but maybe that's on my notifications 
branch (in progress) or was on 3000 acres or something. It's all 
starting to blur.

On 20/01/2015 12:14 am, Cesy wrote:
>
> Do we have any tests of emails yet? I can't see them in the features 
> folder apart from the planting reminder one, though it looks like we 
> couldn't test this particular issue anyway due to the links issue you 
> mention in planting reminder code comment.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/609#issuecomment-70490330>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by Br3nda** [comment]
This appears to have been fixed already..
