### ISSUE TITLE
Only show active/unfinished plantings on garden listing page

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#610]
On this page http://growstuff.org/gardens/owner/skud all the plantings are shown, including finished ones.  It would be better if it just showed ones that are still in progress.

**Comment by pgblu** [comment]
We are looking into this feature, and will report back by the end of day.

**Comment by soborok** [comment]
Hi, I will work on this with my pair Nell.

**Comment by soborok** [comment]
Believe we resolved it, pull request created!
