### ISSUE TITLE
Null geolocation - various weird effects

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#611]
So I noticed a member today who has a geolocation problem: http://growstuff.org/members/flatfood

They have set their location to "Bangalore, Southern India" but the lat/long seem to be null/null as you can see via the API at http://growstuff.org/members/flatfood.json ... I think this might have happened if the geolocation API request timed out, which is something that isn't all that unusual I guess.

This means that no map shows on their user profile.  OK, fair enough.  It also means that their plantings don't show up on crop detail maps, eg. http://growstuff.org/crops/purslane lists flatfood's purslane planting in the sidebar but doesn't show it on the map.

All these are symptoms though.  The real problem is that geolocation timeout.

Suggested fix: a rake task, which runs daily(?), to look for members who have set a location string but whose lat/long are null, and then re-geocodes their location.  That should fix things.

Workaround: for any member who notices this happening to themselves, and wants a quick fix, the fix is to re-edit your location and re-save it.  Eg. change your location to "some random place", save, then change again back to your real location and save again.  Hopefully it will work this time! Note that if you have put a ridiculous location that can't be found on a map, this won't work. For example, "Hogwarts".  You can use http://openstreetmap.org/ to test the location search function. (Though, sigh, it seems that [Hogwarts DOES appear on openstreetmaps](http://www.openstreetmap.org/node/3235935980)!)

**Comment by Skud** [comment]
Probably :)  But for now my mental definition is:

Minor: cosmetic, or doesn't really bother anyone
Major: bothers people, actually has an effect that makes people less likely to use GS
Critical: site down, data being lost, everything on fire, DRAMA!!!1

**Comment by pozorvlak** [comment]
It turned out that our existing `depopulate_null_island` rake task handled this perfectly, so we just had to schedule it to run daily on Heroku.
