### ISSUE TITLE
Limit the vertical space taken by crop varieties in sidebar

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#621]
It would be nice if we could limit the vertical space taken by the crop varieties in the sidebar of the crop detail page, eg. http://growstuff.org/crops/tomato

We could maybe do this by showing the first N and then having a "show NNN more" link which opens out the rest of them.

**Comment by oshiho3** [comment]
I'm going to do this one.

**Comment by maco** [comment]
this was merged, so i'm closing the bug
