### ISSUE TITLE
Add deprecation notes to top of all controller and view tests

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#622]
It would be great if someone could go through all the controller and view tests and leave a block comment at the top, where it can't be missed, saying that they're deprecated and that people should be writing feature tests instead.

**Comment by Skud** [comment]
Wording for a deprecation notice:

> DEPRECATION NOTICE: Do not add new tests to this file!
> View and controller tests are deprecated in the Growstuff project.  We no longer write new view and controller tests, but instead write feature tests (in spec/features) using Capybara (https://github.com/jnicklas/capybara).  These test the full stack, behaving as a browser, and require less complicated setup to run.  Please feel free to delete old view/controller tests as they are reimplemented in feature tests.
> If you submit a pull request containing new view or controller tests, it will not be merged.

**Comment by tygriffin** [comment]
Maybe we could also put all these under a "deprecated" folder like `spec/views/deprecated/`. The tests would still run (I think) and it would be easy to notice.

**Comment by tygriffin** [comment]
I'll do this over lunch today.
