### ISSUE TITLE
Add context to the top of post pages for logged-out visitors

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#625]
A surprising number of visitors land on Growstuff by googling something like "lawn replacement" and winding up on post someone's made called eg. "Suggestions for replacing my lawn".  It would be nice to include some context at the top of each post saying "This is a post on Growstuff, Growstuff is blah blah blah..." and encourage them to look around the site some more, sign up, or whatever.

**Comment by rocky-jaiswal** [comment]
I can have a look at this during the weekend, if that is ok? Thanks :)

**Comment by Skud** [comment]
That would be awesome :)

For context/background: there is a has_and_belongs_to_many relationship between crops and posts, so you should be able to get a list of the crops with post.crops

There is also a partial called crops/_thumbnail.html.haml (I think) which is the thing used on /crops/index to display a crop pic with its name and some info about it.  If you could use this partial, that would be ideal, as we're trying to standardise that look-and-feel.

I would love to see some screencaps of what it would look like with the crops shown in various places on the page, before deciding to approve the code.  Some possibilities include:

- top of page, under heading but above the post
- under the post but above the comments
- in a sidebar created for the purpose

Good luck, and shout out if you need a hand or if we can explain anything more clearly about the code etc.

**Comment by Skud** [comment]
Oh wait sorry, I conflated two different issues!  I thought this was #629 which shows pics of crops mentioned in a post.  You can ignore most of what I said before!

Here's some language to use:

> (member) is using Growstuff to discuss (post title) with a community of food gardeners worldwide.  We have advice on growing hundreds of different [crops](http://growstuff.org/crops), and a community from all around the world.  Sign in or sign up to respond to this post, or to start using Growstuff to track what you're planting and harvesting.

Note: use the shared/signin_signup partial for the last bit!

**Comment by rocky-jaiswal** [comment]
Sure. I will keep you updated on my progress.
