### ISSUE TITLE
On single post page, show thumbnails of crops mentioned

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#629]
If a post mentions some crops using our crop shorthand markdown (\[tomato](crop)) we create a relationship between the post and the crop(s) in question.

It would be cool if, when you come to a post display page (eg. /posts/whatever), it showed the crops mentioned across the top of the page, in thumbnail form.  (Or maybe the bottom. Or down the side. We should experiment.)

This would help people who land on this page from out of nowhere (as many of our visitors seem to, according to our analytics) and give them some context/linkage into the rest of Growstuff, rather than them being sort of at a dead end.

**Comment by pozorvlak** [comment]
I like it!

**Comment by oshiho3** [comment]
As stated as "we should experiment", I have implemented the version which shows mentioned photos below the post. Please check it up or let me know if you want me to upload a screenshot! :)

Btw, I originally thought about making a scrollable photo gallery, but realized it'll require some sort of JQuery library. I have a feeling that we don't want to integrate unnecessary library like that, do we?

**Comment by Skud** [comment]
Thank you! Could you post a screenshot please?

**Comment by oshiho3** [comment]
You're welcome! Here is the screenshot. I'm using _image_with_popover.html.haml in here.

![screen shot 2015-02-23 at 5 52 36 pm](https://cloud.githubusercontent.com/assets/7848188/6323834/fabac216-bb84-11e4-81c3-18fa6eaeb764.png)

**Comment by Skud** [comment]
Looking pretty good! Thanks for the screenshot :)

Instead of the image with popover, can you please use the thumbnail 
partial instead (_thumbnail.html.haml)?  I think that will be more 
widely used in the glorious future of our card based design, and 
_image_with_popover will probably be deprecated when we do the homepage 
redesign and it's not called from anywhere anymore (just a guess).

Also, I see you have put the images in _single.html.haml but that 
partial's used in many places, including on the crop page, member 
profile page, and places like that. (Also, when we get hierarchical 
posts, which I've been working on, every comment will be a post, and 
that will mean that things would get very busy with images).  So, I 
think these images should only appear on post/show.html.haml and so 
should be outside the .well div.  So maybe just above the "edit post" 
buttons etc?


On 23/02/2015 5:57 pm, Shiho Takagi wrote:
>
> You're welcome! Here is the screenshot. I'm using 
> _image_with_popover.html.haml in here.
>
> screen shot 2015-02-23 at 5 52 36 pm 
> <https://cloud.githubusercontent.com/assets/7848188/6323834/fabac216-bb84-11e4-81c3-18fa6eaeb764.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/629#issuecomment-75496519>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by oshiho3** [comment]
OK. Here is the new version!

![screen shot 2015-02-23 at 6 52 30 pm](https://cloud.githubusercontent.com/assets/7848188/6324366/34276e98-bb8d-11e4-9dfc-460bb020f8f5.png)

**Comment by Skud** [comment]
Love it :)  Push the code up and I'll review.

A.

On 23/02/2015 6:56 pm, Shiho Takagi wrote:
>
> OK. Here is the new version!
>
> screen shot 2015-02-23 at 6 52 30 pm 
> <https://cloud.githubusercontent.com/assets/7848188/6324366/34276e98-bb8d-11e4-9dfc-460bb020f8f5.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/629#issuecomment-75501805>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by oshiho3** [comment]
Glad. Just came back from sweating at the GYM. Pushing the updated code, done.

**Comment by GabrielSandoval** [comment]
Can I have an update on this one? I'd be glad to be of help.

GabrielSandoval,
AELOGICA Intern

**Comment by oshiho3** [comment]
@GabrielSandoval, it's in Pull Request #708 waiting to be merged.

**Comment by GabrielSandoval** [comment]
Thanks for the update @oshiho3.

**Comment by cesy** [comment]
Fixed by #708.
