### ISSUE TITLE
Data section on homepage

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#630]
I'm breaking this out from #628 into a separate story so @tygriffin and I can work on each part separately :)

This story is just to create the section that shows the data available at the bottom of the page.

**Comment by Skud** [comment]
Don't think we're going to have time to test this properly for release 8. Pushing it back to release 9.

**Comment by jacemonje** [comment]
What data do we need shown? The x number of y were planted in z kind?

**Comment by maco** [comment]
@jacemonje on [the wireframes](http://talk.growstuff.org/t/major-homepage-redesign/168) the first one shows the home page redesign. I think it's for the "Use Our Data" section.

**Comment by CloCkWeRX** [comment]
Stalled, wireframes MIA.
