### ISSUE TITLE
Set container min-height to avoid footer weirdness

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#640]
As per http://talk.growstuff.org/t/please-test-footer-redesign-seo-friendly-crop-detail/189/8 we should set .container to have a min-height that ensures that the footer doesn't look weird on short pages (eg. the sign in form).

**Comment by Skud** [comment]
FWIW, I couldn't get this to work any way at all.

Firstly I added an ID to the main container as there are also containers for the header and footer and we don't want to affect them.

Then I did:

```css
#maincontainer {
  min-height: 90%;
}
```

This did nothing.  So then I tried a fixed number, eg. 1000px, and that worked... but it will make a mess in different sized browser windows.

So basically at this point I'd like someone who knows CSS better than me to take a look at this!

**Comment by cesy** [comment]
Did you try quote marks around the percentage? That used to be a problem in some browsers.

Can you link your branch here so others can copy without redoing your work, please?

**Comment by Skud** [comment]
I didn't actually make a branch, just fiddled on the one I was on, and 
never committed.

On 20/01/2015 12:01 am, Cesy wrote:
>
> Did you try quote marks around the percentage? That used to be a 
> problem in some browsers.
>
> Can you link your branch here so others can copy without redoing your 
> work, please?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/640#issuecomment-70489034>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by Skud** [comment]
@Cesy I'm just about to close this, but in future could you please use "fixes #NNN" in your PRs, which should auto-close the ticket when the PR is merged. Thanks!
