### ISSUE TITLE
Error on trying to set Heroku config with figaro

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#644]
I was doing a production push and tried to set the config using figaro, as described in the [release process docs](http://wiki.growstuff.org/index.php/Production#Production)

```
figaro heroku:set -e production --app=growstuff-prod
/Users/skud/.rvm/gems/ruby-2.1.5@growstuffdev/gems/figaro-1.0.0/lib/figaro/cli/task.rb:28:in `system': no implicit conversion of Fixnum into String (TypeError)
```

I don't think there were actually any config changes so this probably doesn't affect the production push, but I think Figaro's changed again and we probably need to re-tweak our docs :-/

**Comment by tygriffin** [comment]
That's really weird, because I just updated those docs to reflect the changes in the updated figaro gem.

**Comment by tygriffin** [comment]
Ah, it might have to do with [production config vars not being strings](https://github.com/laserlemon/figaro/issues/143).

But it was [supposed to have been fixed](https://github.com/laserlemon/figaro/pull/144)?

**Comment by Skud** [comment]
Basically the workaround is "quote your strings".  I don't think it's something we need to fix other than to do that.
