### ISSUE TITLE
Signup/signin with Twitter, Facebook, etc

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#645]
It would be good if people could signup with Twitter etc -- might make the onboarding process smoother.

**Comment by jacemonje** [comment]
Hi, will do this :)

**Comment by CloCkWeRX** [comment]
How are you traveling with this @jacemonje? Happy to go add various providers if you are a bit stuck

**Comment by CloCkWeRX** [comment]
One of the issues with flickr based signup is the lack of email in the profile API.

https://www.flickr.com/services/api/flickr.people.getInfo.htm

It means that a signup with flickr needs to do SELECT * FROM members WHERE sha1(email) = ? ; but by default I don't think we'd have the postgres crypto (pgcrypto) things enabled.

**Comment by cesy** [comment]
Yeah, I don't think we need sign in with Flickr, just Facebook/Twitter/Google. Flickr is mainly useful to add to an existing account for photos, until we get our own photo hosting.

**Comment by CloCkWeRX** [comment]
Closing.
Flickr isn't what it was, Twitter is declining, Facebook made me annoyed with trying to do an "App review" process on us.
