### ISSUE TITLE
Use elasticsearch from autosuggest UI

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#649]
This is forked off from #618 as the UI issues around the autosuggest dropdown are kinda separate from the elasticsearch backend.

Basically, when we use the autosuggest (eg. on the "new plantings" form) we should be able to search for "solanum..." and have it show tomatoes, or search for "silverbeet" and have it show swiss chard.

The problem is that if we do that at present, only the main system name is shown in the dropdown.  How do you know if "swiss chard" is really what you want if there isn't a UI hint to show you the association between that and the alternate name "silverbeet"?

It looks like in order to do this we'll want to use javascript.  There are some good-looking plugins that do this, eg [ddSlick](http://designwithpc.com/Plugins/ddSlick) (though it looks like it's had no update for 2 years, so there might be something newer).

Anyway, I think it would be good if the select text showed something like:

> **Tomato**
Scientific name: solanum lycopersicum

or

> **Swiss chard**
Alternate name: silverbeet

... using the appropriate contextual thing depending on what it matched on.

An alternative might be to just *always* show scientific and alternate names, eg:

> **Swiss chard**
Scientific name: beta vulgaris var. cicla
Alternate names: chard, silverbeet

... but that might take up a lot of vertical space.  Not to mention horizontal space for things that have a lot of alternate names.

**Comment by maco** [comment]
does the date of closure on this suggest it was actually part of release 8?

**Comment by tygriffin** [comment]
I believe that's the case.
