### ISSUE TITLE
Migrate our Figaro environment variables to Rails secrets

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#660]
Rails 4 lets us store secrets in secrets.yml as per http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml rather than using a third-party gem like Figaro.

We should migrate to doing this the railsy way, not just to reduce our dependence on a bit of a finicky third-party gem, but also in the hopes that it might also help with #491 (at present we can't push our Figaro config up to Heroku).

**Comment by CloCkWeRX** [comment]
https://github.com/Growstuff/growstuff/commit/92f8a843691a65cb3235cb6fdb08881660e6ceb9
