### ISSUE TITLE
Adding a new crop without scientific name gives an uncaught error

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#666]
If a crop wrangler adds a new crop and only fills in the name, not the scientific names (contrary to our wrangling guidelines, but possible), instead of being caught smoothly, you get an ActiveRecord error.

ActionController::UnpermittedParameters in CropsController#create
found unpermitted parameters: scientific_names_attributes

**Comment by Skud** [comment]
FWIW, this error doesn't occur on staging (or production) at present.

On 22/01/2015 9:39 pm, Cesy wrote:
>
> If a crop wrangler adds a new crop and only fills in the name, not the 
> scientific names (contrary to our wrangling guidelines, but possible), 
> instead of being caught smoothly, you get an ActiveRecord error.
>
> ActionController::UnpermittedParameters in CropsController#create
> found unpermitted parameters: scientific_names_attributes
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/666>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by tygriffin** [comment]
I know exactly what this is. We need to pass a hash of permitted params for scientific names when setting permitted params for crops. I'll fix when I'm at my computer in a couple hours.

iPhone$B$+$iAw?.(B

2015/01/22 20:39$B!"(BCesy <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by tygriffin** [comment]
@Skud That's probably because permitted params are configed to only raise exceptions in dev. Should probably make it raise in staging too, I think.

iPhone$B$+$iAw?.(B

2015/01/22 20:43$B!"(BSkud <notifications@github.com> $B$N%a%C%;!<%8(B:
