### ISSUE TITLE
Edit things "in place"

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#672]
This is a bit broad, but basically what I'd like is to be able to edit things like plantings, harvests, gardens, etc "in place" on the page where you view the thing, rather than clicking on "edit" to get a massive form.

For example, you'd be looking at a certain planting and you could click on the "description" (or on a little pencil next to it, or something) to edit that property.  Then it gets saved without sending you to another page or anything like that.

Once we figure out _how_ to do this, we should do it for:
- member profile
- gardens
- plantings
- harvests
- seeds

and probably some other stuff, but I think those are the main ones.

**Comment by tygriffin** [comment]
I really like this feature too. One big consideration though: If the info you're editing appears anywhere else on the page, that info will then be out-of-date after saving. This is the problem single page app frameworks like Angular or Ember generally solve with model binding.

**Comment by Skud** [comment]
I think in most cases the info will only appear once on the page, won't it?

On 23/01/2015 1:40 pm, Taylor Griffin wrote:
>
> I really like this feature too. One big consideration though: If the 
> info you're editing appears anywhere else on the page, that info will 
> then be out-of-date after saving. This is the problem single page app 
> frameworks like Angular or Ember generally solve with model binding.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/672#issuecomment-71139084>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by tygriffin** [comment]
I think that will generally be the case, but I can imagine for example an in-line edit widget for the name of a garden with a link to that garden somewhere further down the page. After editing, the link text would be wrong. Actually, in that case, would the link continue to work since the name of the garden is in the url?

**Comment by Skud** [comment]
Friendly ID version 5 fixes that problem with the URLs, in that you have 
to explicitly regenerate the slug (it doesn't auto-regenerate when you 
just save the object).

Anyway, I can see the hypothetical problem, but I don't think it's 
likely to be that big a deal (or, we can get around it some other way).

Eg. if I look at 
http://growstuff.org/gardens/skud-ballarat-backyard-zone-1 I see the 
phrase "Ballarat backyard, zone 1" (which is the name of the garden) 
repeated multiple times, but the repetition (especially under "what's 
planted here") is bad UI and should be fixed.

Here's another example, this time a planting: 
http://growstuff.org/plantings/skud-ballarat-backyard-zone-1-rainbow-chard 
Note that a planting doesn't have a name; its to_s method generates a 
string that is made up of the owner, crop, and garden name.  If you 
edited eg. the crop that you planted (in this case "rainbow chard"), you 
would invalidate the h1 and title on the page.  This probably isn't so 
easily get-round-able as the previous example.

One workaround might be to flag certain properties as "requires a page 
reload". So if you edit the crop or garden you'd need a reload, but if 
you edit the quantity or date planted, you don't.


On 23/01/2015 1:52 pm, Taylor Griffin wrote:
>
> I think that will generally be the case, but I can imagine for example 
> an in-line edit widget for the name of a garden with a link to that 
> garden somewhere further down the page. After editing, the link text 
> would be wrong. Actually, in that case, would the link continue to 
> work since the name of the garden is in the url?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/672#issuecomment-71140004>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by Skud** [comment]
Looks like Andru has a solution to this using ReactJS, here: http://talk.growstuff.org/t/javascript-frameworks/195/15?u=skud

**Comment by cobismith** [comment]
sharing relevant stuff from my email: 

after I click on 'new garden' (or whatever it was I forget now) and fill in profile details here http://growstuff.org/members/edit and save it, I remain on this page rather than being taken to a page where I can do some next step about the new garden. I was anticipating being taken to a page where I can share information about my balcony garden

**Comment by Br3nda** [comment]
Let's split this -- consider this issue the "epic"


#1619 edit in place for Seeds
#1618 edit in place for Plantings
#1617 edit in place for Gardens
#1616 Edit in place for Harvests
