### ISSUE TITLE
Down-arrows on dropdowns look skinny and weird

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#675]
Screenshot (Firefox 34 running on Arch Linux):

![screenshot from 2015-01-24 11 57 42](https://cloud.githubusercontent.com/assets/225991/5887307/452a0870-a3c0-11e4-8d76-c45810c07790.png)

**Comment by maco** [comment]
This looks like a Bootstrap bug: https://github.com/twbs/bootstrap/issues/765

The current recommended workaround there is to use https://github.com/silviomoreto/bootstrap-select

**Comment by maco** [comment]
I'm shifting this to effort medium because it's a bug in how Bootstrap itself works and so this will be a little more involved (figuring out how to integrate new library and such).

**Comment by Br3nda** [comment]
changed to radio buttons now
