### ISSUE TITLE
Add organic/GMO/heirloom/maturity to seeds CSV and RSS

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#677]
See #493 and #523 -- basically we did the main story but didn't have time to add them to the CSV and RSS so we forked off a different issue for that.

**Comment by gabrielle27** [comment]
I can take a look at this one today.

**Comment by gabrielle27** [comment]
on second thought I can see this has some dependencies so I'll hold off

**Comment by Skud** [comment]
#493 is *super* close to being merged, though!  Probably in less than a day.
