### ISSUE TITLE
Get rid of old support/, policy/ etc pages

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#690]
We're getting a shiny new CMS (#525) to keep these sorts of pages in, so once stuff has been migrated over there we should remove the static pages we're serving at present.

AFAIK these are the routes we no longer need (based on what's currently linked in the footer):

/support
/policy
/about/contact

**Comment by pozorvlak** [comment]
I started work on this with @twconquest, but we realised we didn't understand CMS well enough. [Our work-in-progress branch is here](https://github.com/twconquest/growstuff/tree/removestaticfiles)

**Comment by cesy** [comment]
First thing is to get the footer back working. Then based on https://github.com/comfy/comfortable-mexican-sofa/wiki/How-to-protect-other-engines-from-catch-all-route, it implies that the catch-all route at the end means you don't need to add anything special or new, just do the deletions that you did.

**Comment by cesy** [comment]
Okay, footer is working. But now we need to create those pages and put the content in the CMS before we delete them.

**Comment by cesy** [comment]
Okay, prod and staging now both have about/contact, support, policy/tos, privacy, community, api. Next decision is whether we stick with it at /cms/ or whether we try and remove that from the URL. If we leave it, potential external links will break when we remove the static pages.

**Comment by cesy** [comment]
Aha, I've figured out how to remove it, and done so on staging. So I think we should try cleaning up the static pages and test carefully on staging.

**Comment by maco** [comment]
Skud wanted the /cms/ part of the url, I believe

**Comment by cesy** [comment]
I also found /policy/copyright which doesn't seem to be linked from anywhere - I've copied it into the CMS but left it there for now.

**Comment by cesy** [comment]
Okay, I've put it back on staging and will leave it in, then. Do we need any plan for redirects, or shall we just let them break?

**Comment by pozorvlak** [comment]
The point of using a CMS was to enable us to change static text without making code changes. If we remove the /cms/ will we be able to add other static pages easily, or will they require changes to `config/routes.rb`?

I can see the following arguments for removing `/cms/`:

 - it exposes internal implementation details
 - it will presumably change if we move to another system.
 - it [breaks existing links](http://www.w3.org/Provider/Style/URI.html), if any.

**Comment by cesy** [comment]
We'll be able to add other pages easily without changing routes.rb.

**Comment by cesy** [comment]
I'm inclined to keep /cms/ out of it. Since Skud is not currently around, let's take a quick vote - @pozorvlak, @maco?

**Comment by maco** [comment]
@pozorvlak do you have admin access to be able to update the CMS pages
without Skud?

**Comment by cesy** [comment]
I have access to do it as well. It would be worth adding you, too,
Mackenzie.

**Comment by maco** [comment]
Oh, I just read back the thread. I was thinking you meant "let's stick to
hardcoding instead of a CMS" but you mean the URLs. I think Skud wanted
"/cms" in there so that it'd be namespaced in case we ever want to have a
page under / with the same path as a CMS-controlled page has.

The route setup means that if the CMS will only be invoked if there isn't
already a route under / right?  (I'm just trying to think of things that
can break)

**Comment by cesy** [comment]
Yes, exactly.

**Comment by maco-fme** [comment]
Alright, sure, let's go with maintaining existing URLs

**Comment by pozorvlak** [comment]
Maintaining existing URLs sounds good to me.​
