### ISSUE TITLE
After deleting a photo, show a message to say you have

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#713]
After deleting a photo, there's no flash message saying it was successfully deleted (per [this post](http://talk.growstuff.org/t/please-test-improved-search-garden-photos-harvest-csv-unsaved-sci-names/208/5?u=skud)).  A flash message should be shown saying something like "Photo successfully deleted."

**Comment by laramelniker** [comment]
I'd like to take a stab at this. I wrote a message here: http://talk.growstuff.org/t/development-login/256 about where I'm getting stuck. 

I'm fairly new so would be very much open to pairing with someone else, but if not I'll try my best!

**Comment by jendiamond** [comment]
I would be interested in pairing with you on this remotely. :) thejendiamond @ gmail

**Comment by pozorvlak** [comment]
Fixed in #748.
