### ISSUE TITLE
Clearly make optional fields optional on planting/harvest/seed/garden forms

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#718]
These four forms (planting, harvest, seed, and garden) are long and include many optional fields.

The simplest incremental incremental to these is to simply put "Optional" next to the optional fields on the form.

The required fields are:

* Garden - name
* Planting - crop and garden
* Harvest - crop
* Seeds - crop

A further improvement might be:

If the object is new (as opposed to editing an existing one), hide the least important/relevant fields behind a "Show more options" link, and use jquery(?) to display them only if asked for.

Fields to hide behind this link might include:

* Garden: area, active
* Planting: planted from, sun/shade, mark as finished (move "description" up higher in this case)
* Harvest: hmmm I think it's all fine (as long as optional fields are marked optional)
* Seeds: move description up under quantity, then everything below that (plant before, days until maturity, organic/gmo/etc) that can be hidden.

I'd be happy with the simpler version of this and delighted with the slightly more complex one.  I don't think it's worth doing anything super fancy as the long-term fix to this is #672.

**Comment by pozorvlak** [comment]
The UI pattern I'm used to seeing is "* denotes required field", with all non-starred fields being optional.

**Comment by maco** [comment]
Ditto

**Comment by Skud** [comment]
I don't think that's necessarily obvious enough for these forms.

A.

On 20/02/2015 9:39 am, pozorvlak wrote:
>
> The UI pattern I'm used to seeing is "* denotes required field", with 
> all non-starred fields being optional.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/718#issuecomment-75154069>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by pozorvlak** [comment]
OK, but I think it's more common to mark the required fields than the
optional ones.

**Comment by sha1sum** [comment]
I completely overlooked the commits by @pozorvlak and just issued a pull request for the same issue. My mistake :)

**Comment by pozorvlak** [comment]
Fixed in #779.
