### ISSUE TITLE
On harvest form, "fruit" is always shown

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#719]
It's a bit weird that "fruit" is selected by default for all harvests. Can we add a blank option, and put a place holder like "eg: fruit, leaves..."

**Comment by maccath** [comment]
I can do this. Shall I use the exact text 'eg: fruit, leaves...' or something different? I think maybe just 'e.g. fruit' is appropriate, to keep consistent with the placeholder on the crop selection. Let me know. :smile:

**Comment by pozorvlak** [comment]
Fixed in #759.
