### ISSUE TITLE
"Places" page should show plantings, harvests, seeds, etc

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#720]
It would be cool if http://growstuff.org/places/melbourne could show stuff other than members near here.  For instance:

* what is growing/being harvested near here
* what seeds are available near here

In future we might even show seed retailers, and things like that.

I'd like to see a mockup/wireframe before implementation of this!

**Comment by oshiho3** [comment]
I'm working on this.

**Comment by oshiho3** [comment]
I started working on backend for this. Is someone doing wireframe?
Otherwise, I'm thinking of adding below sections which looks similar to the ones on the homepage.

- Recently planted near Melbourne
- Seeds available to trade near Melbourne

Once the screen is available I'll paste it here.

**Comment by oshiho3** [comment]
Just made a quick mockup. Please comment on the look and functionality. Anyone is welcome!

![growstuff dev members near melbourne - growstuff dev 2015-03-10 18-12-59](https://cloud.githubusercontent.com/assets/7848188/6570640/216f420a-c752-11e4-9934-10b7f5a486c8.png)

**Comment by GabrielSandoval** [comment]
Any update on this one?

**Comment by oshiho3** [comment]
Hi @GabrielSandoval,
I was working on this one but have since dragged away due to lack of time. I've decided to drop this item, so feel free to take it and work on this.

**Comment by GabrielSandoval** [comment]
Thanks @oshiho3. I'll start working on this soon.
