### ISSUE TITLE
unable to escape a quick crop link

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#721]
I was trying to mention in a comment on Growstuff how someone should use the quick crop links feature.  I tried to escape the square brackets as per http://daringfireball.net/projects/markdown/syntax#backslash but it didn't work.

I suspect our special Growstuff filter might need to take escaping into account, but I'm not sure.

You can see this in action here: http://staging.growstuff.org/posts/skud-20150222-testing-link-escaping

**Comment by maco** [comment]
You successfully did it in one when I couldn't figure out how. I'll have to
look back at previous ones. Hopefully it's bit that posts and comments
treat it differently!

**Comment by Skud** [comment]
Yeah I remember that thread!  It won't be handled differently though... 
we have a filter that filters all markdown, that lives in lib/, and 
it'll be doing that in both places.

Actually I think that other thing was something like, if you had two 
links in the same paragraph, it was greedy-matching or something.

Hmmm.

On 23/02/2015 8:24 am, Mackenzie wrote:
> You successfully did it in one when I couldn't figure out how. I'll 
> have to
> look back at previous ones. Hopefully it's bit that posts and comments
> treat it differently!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Growstuff/growstuff/issues/721#issuecomment-75460902>.
>

-- 
Alex "Skud" Bayley
skud@growstuff.org
http://growstuff.org/

**Comment by maco** [comment]
Right, there was the greedy match bug, and then we were trying to figure
out how to show the mark down to explain the bug after we fixed it.
