### ISSUE TITLE
More representative Facebook thumbnail

### ISSUE THREAD

**Issue by emhoracek** [Growstuff/growstuff#733]
When I share the http://growstuff.org link on Facebook to invite friends to visit the page, the thumbnail that appears doesn't represent the site very well. I would think it would be the Growstuff logo or at least a picture of a plant. But instead it looks like its somebody's randomly generated avatar? Thanks Facebook. :)

![growstuff](https://cloud.githubusercontent.com/assets/5353499/6770049/cd0eb2d6-d089-11e4-9fd3-cf6fe0ef4130.png)

This looks like [a good how-to article](http://cypressnorth.com/social-network-media-marketing/how-to-customize-preview-thumbnail-images-for-pages-on-your-website/).

This is super minor, but I think a good thumbnail on Facebook links makes people more likely to share and makes friends more like to click on the shared links.

**Comment by cesy** [comment]
Sadly it's still using members' avatars instead of the logo.

**Comment by cesy** [comment]
http://www.limecanvas.com/how-to-make-facebook-use-a-custom-thumbnail-image-for-your-website/ gives another way to try and force it.

**Comment by CloCkWeRX** [comment]
https://developers.facebook.com/tools/debug/og/object?q=growstuff.org - "The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags." seems to be worth looking at

**Comment by CloCkWeRX** [comment]
```
<html prefix="og: http://ogp.me/ns#">
```
Seems to be missing, which means the opengraph stuff may not kick in straight away

**Comment by CloCkWeRX** [comment]
Argh, so close.
https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fstaging.growstuff.org%2F

```
og:image could not be downloaded or is too small	og:image was not defined, could not be downloaded or was not big enough. Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook. 
```
It's clearly not accurate when it says:
```
Image 'http://staging.growstuff.org/assets/growstuff-apple-touch-icon-precomposed-dc69b96d88315604421071635f3a2e36.png' will be used instead. 
```

**Comment by CloCkWeRX** [comment]
I'm confused - the debugging tool shows me a share link that is quite reasonable, but the result I get seems wrong when I share just http://staging.growstuff.org/

If I share http://staging.growstuff.org/?hello ; never having seen that URI before I get a quite reasonable preview snippet with the image we want.

Clearly there's some kind of caching at play, but I haven't seen any documentation / have no idea what will happen if we share the prod site even after this is implemented.

**Comment by b4thestorm** [comment]
I Think I may know how to solve this issue. The image that is being linked is too small, also og:image may not be the best meta property. I would like to submit a PR request with the fix for this. If this is still an open issue.

**Comment by cesy** [comment]
That would be great, thank you!

**Comment by CloCkWeRX** [comment]
Facebook no longer has the old image in the cache and correctly renders http://staging.growstuff.org/assets/growstuff-apple-touch-icon-precomposed-dc69b96d88315604421071635f3a2e36.png as a preview icon now for staging.growstuff.org. This is likely closeable.

**Comment by CloCkWeRX** [comment]
![image](https://cloud.githubusercontent.com/assets/365751/14075397/5dbec99a-f520-11e5-8b9d-35dea8592266.png)

**Comment by emhoracek** [comment]
Thanks for doing this!! :tulip:
