### ISSUE TITLE
Resizing compatablility 

### ISSUE THREAD

**Issue by srshuff** [Growstuff/growstuff#780]
Whenever resizing the website to half page, the website layout messes up at the bottom. It stays this way unless I size it smaller or larger for about an inch size difference. 

![growstuff](https://cloud.githubusercontent.com/assets/9614389/8836283/ebc508e2-308d-11e5-9659-c6b3b913f081.png)

**Comment by maco** [comment]
Testing this out,  it looks like ~700px wide to ~1000px wide has this problem

**Comment by maco** [comment]
The funny oversized overlapping avatar bit behind the odd-floating footer is also a problem.

**Comment by maco** [comment]
Ok, I just tried out in my browser (need to put it in the actual codebase) a fix for the weird avatar thing going on, and in the process that fixed the footer. Here's the site at the avatar-y part of the page, at different widths.

![screen shot 2015-07-22 at 5 48 21 pm](https://cloud.githubusercontent.com/assets/401264/8838343/f575624a-3099-11e5-8101-7bd7bb9da632.png)
![screen shot 2015-07-22 at 5 48 33 pm](https://cloud.githubusercontent.com/assets/401264/8838344/f57a6f42-3099-11e5-9250-11c547e8b50b.png)
![screen shot 2015-07-22 at 5 48 44 pm](https://cloud.githubusercontent.com/assets/401264/8838342/f5723c78-3099-11e5-9714-d5bbba5e14a5.png)
