### ISSUE TITLE
Improve experience on mobile browsers

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#807]
Right now I use two features of growstuff.org on mobile heavily:
- After I plant,  I want to snap a quick picture/add a progress image, adding other details
- When I harvest,  snap a photo and enter yield.

Right now the UI does use the basics of responsive design to adapt to smaller resolution,  but the workflow, control sizing and positioning make things harder than they need to be.

For example,  adding a photo seems to rely on Flickr sync occurring rather than simply allowing upload (to Flickr/whatever service on my behalf), or writing out to an uploaded photos location. (Am aware this may be from storage cost pov).

Other nitpicks include the use of typing controls/latency of autocomplete - caching of the most popular data (top 10 seeds,  plants, etc) locally may improve this experience; with fallback to remote lookup.

I'd like to open this up for discussion, to see if others find the same and pull together a concrete list of improvements we can achieve - particularly taking it from subjective opinions into clearly documented pain points with clear solutions.

Related:
 * #1334 
 * #904 
 * #808 
 * #809

**Comment by maco** [comment]
We do have photo hosting as a thing we'd like to do, just nobody's written
the code yet.

**Comment by cesy** [comment]
For future reference, for a wide-ranging discussion it may be better to use talk.growstuff.org, as that gets other users as well as developers, and keep issues for things that are well-defined. Caching most popular data for the autocomplete to speed it up sounds like a good idea, as that one's definitely slow enough to be a usability problem on occasion - let's spin off an issue for that.

**Comment by cesy** [comment]
And in general, yes, nitpicks on mobile are a good thing and we're very keen to improve usability, so suggestions welcomed :)

**Comment by CloCkWeRX** [comment]
Ah, had missed it in the README
