### ISSUE TITLE
Avoid tables as layout markup for better mobile experience

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#808]
Part of  #807

In a few places, a table is a logical layout tool for various lists. Unfortunately, on smaller resolution devices this causes a scroll left/right problem.

https://css-tricks.com/responsive-data-tables/ describes the problem in general; and offers one solution (for truely tabular data). 
I think there are other approaches, like using the bootstrap grid system (.span1 / .span4 / etc) that can achieve a similar experience on the web, but reflow better on compact UI with the right media css.

I've attached some screenshots demonstrating the problem as it specifically relates to growstuff:

![2015-08-20 05 20 07](https://cloud.githubusercontent.com/assets/365751/9376495/f964ae28-474c-11e5-8e50-e81cea126949.png)

![2015-08-20 05 19 43](https://cloud.githubusercontent.com/assets/365751/9376542/a0f926d2-474d-11e5-9f5f-bad02df3d58c.png)

These views may be affected in varying degrees:

 * app/views/products/index.html.haml
 * app/views/roles/index.html.haml
 * app/views/accounts/index.html.haml
 * app/views/gardens/index.html.haml (Different/improved on staging, some small screen rendering issues still)
 * app/views/plantings/index.html.haml (Different/improved on staging, but still exhibits odd behaviour on small UI)
 * app/views/admin/orders/search.html.haml
 * app/views/notifications/index.html.haml
 * app/views/posts/_summary.html.haml
 * ~~app/views/seeds/index.html.haml~~ (Done!)
 * app/views/harvests/index.html.haml (99% improved on staging)
 * app/views/crops/wrangle.html.haml
 * ~~app/views/scientific_names/index.html.haml~~ (Not really affected)
 * ~~app/views/alternate_names/index.html.haml~~ (Not really affected)
 * app/views/account_types/index.html.haml
 * app/views/home/_seeds.html.haml
 * app/views/orders/index.html.haml
 * app/views/orders/complete.html.haml
 * app/views/orders/show.html.haml

**Comment by cesy** [comment]
Our general aim with most of those is to switch to a card-based design, I
think, as we've already done in a couple of places.

**Comment by CloCkWeRX** [comment]
For those that have swapped to card based design; there's still a few things worth tweaking on smaller views. I'll probably do explicit PR's for those / have updated the list from a quick investigation

**Comment by CloCkWeRX** [comment]
#570

**Comment by maco** [comment]
Do we still need this if we're going card-based?

**Comment by CloCkWeRX** [comment]
Happy to close, its much improved
