### ISSUE TITLE
Images on mobile layout should default to full width

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#809]
Part of #807 
In some locations, the way that images are rendered is very effective on smaller screens, such as:

![2015-08-20 05 19 08](https://cloud.githubusercontent.com/assets/365751/9376680/a5443c16-474f-11e5-86b9-d262d087d8fc.png)
(Full width, stylish border, easy to see given on a small screen)

However, other lists seem to limit the thumbnails while enforcing a single column layout:

![2015-08-20 05 15 34](https://cloud.githubusercontent.com/assets/365751/9376667/722dfeca-474f-11e5-86f5-c45e0c640ace.png)

![2015-08-20 05 18 22](https://cloud.githubusercontent.com/assets/365751/9376679/9ea334a2-474f-11e5-8127-9ccd68c35bdd.png)

We should investigate better ways to handle this; either:
- Treating 'thumbnails' on smaller UI as warranting a larger picture that consumes 90% width when in single column mode
- Or a more compact photo 'grid' view; like http://0day.kiev.ua/uploads3/1315379162_4e6717da3543d.jpg or a more compact version, relying on square thumbnails and alt tags/title attributes to explain who the author is.

**Comment by CloCkWeRX** [comment]
After a bit of investigation; it seems that on desktop browsers it behaves as a grid properly due to:

```
@media (min-width: 992px)
.col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12 {
    float: left;
}
```

but at lower widths, the float: left is absent.

We seem to have the responsive bootstrap stuff commented out as of e226ce40
```
//@import "twitter/bootstrap/responsive";
```

That at least seems to be the cause of the crops list/index page behaving as it does on mobile.

Members seems to be similar, but layout is a bit funny there.

**Comment by maco** [comment]
I made changes to the members stuff recently so it'd be flex layout cards
(see staging) rather than what it was doing...full width, no border,
falling to float proper, layering things on top of each other, and shoving
the footer up. I need to make the same changes to the crop list.

**Comment by maco** [comment]
Wait...did I ever send in that PR? Now I'm not sure.I thought I did... it
was for a mobile issue that was submitted a few weeks back

**Comment by CloCkWeRX** [comment]
Yeah on staging, crops is still a bit funny.
