### ISSUE TITLE
Interacting with the 'mark as finished' control triggers the calendar

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#847]
http://staging.growstuff.org/plantings/new?crop_id=257 Chrome
- Tick/untick mark as finished

Expected:
You only see the calendar if you focus on the datepicker

Actual:
Focus is automatically shifted for you

**Comment by maco** [comment]
I believe this was intentional, to prompt you to actually fill the date in.

**Comment by CloCkWeRX** [comment]
Maybe we could look at a more subtle highlight or other visual cue then - the way it triggers at the moment is a bit unexpected, and if you accidentally toggle it it becomes hard to uncheck it

**Comment by maco** [comment]
I'm removing this from Release 11 because we haven't figured out what the other visual cue should be yet.
