### ISSUE TITLE
Harvests UI: "Read More" link on long descriptions should be implemented with CSS

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#854]
The card UI makes assumptions about screen size; and character width. Because the card UI is controlled by CSS; but we're trying to restrict content length server side we end up with floating issues if the browser size isn't exactly as we expected.

![image](https://cloud.githubusercontent.com/assets/365751/14226447/0fd15122-f92a-11e5-9176-cd82b6707ae8.png)

Instead of doing just
```
      truncate(harvest.description, length: 130, separator: ' ', omission: '... ') { link_to "Read more", harvest_path(harvest) }

```

we should probably move this logic back to the partial and render the 'Read more' as a relative positioned element (bottom right); and a z-index/solid background plus overflow: hidden on the parent div so that long text cannot distort the layout.

**Comment by CloCkWeRX** [comment]
Proper way to do this with CSS: 
```
text-overflow: ellipsis
```

**Comment by CloCkWeRX** [comment]
Super frustrating to get this working in Chrome inside of a panel footer. I give up again

**Comment by maco** [comment]
Is the issue placing the "read more" link after you've got the main stuff
ellipsified? If so, push a branch, and I'll take a peak?

**Comment by CloCkWeRX** [comment]
Its more chrome refusing to apply text-overflow:ellipsis even though the parent block styled element has the right width height and overflow  behaviour specified.

**Comment by maco** [comment]
try
```
display: block
display: -webkit-box
```

a la https://codepen.io/martinwolf/pen/qlFdp

**Comment by maco** [comment]
Ok, it looks like `text-overflow: ellipsis` can *only* be used with `white-space: nowrap` because it only handles single lines of text. But then, we could put the READ MORE on the next line, so I guess that works.
