### ISSUE TITLE
Prompt with planting reminders

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#864]
Gardenate does this well: emailing to suggest what will be ready to plant.

See if there are open data sets or ways we can make it easy to know *when* to plant (and thus update growstuff).

Very similar to #524 but more distinctly about plants for your climate/region/etc.

![image](https://cloud.githubusercontent.com/assets/365751/14414184/cd0fff8c-ffcd-11e5-9cfa-28116e69bb5b.png)

Easiest implementation: link to gardenate so we don't double build the feature.

**Comment by CloCkWeRX** [comment]
One of the things that reminded me to pick this up again, I bought more seeds and dealt with my compost.

I happened to buy the seeds off of ebay. While we do have seed trading built in, there's definitely a market place thriving over there already... pave the cowpaths and all that.

It would be useful to *also* add in links to ebay, sorted by distance to encourage 'local' seed trading, and maybe chuck in an affiliate id or something if there is one floating around to chip in for hosting costs.

**Comment by cesy** [comment]
Sounds sensible to me - we want to link to existing services rather than reinventing the wheel. We don't have an ebay affiliate link yet, so feel free to set one up and email the details to the maintainers list.
