### ISSUE TITLE
Inconsistency: Show post doesn't show reply very obviously

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#869]
Show post doesn't permit reply
- Visit posts index page (http://staging.growstuff.org/posts), reply to post
- Visit actual post (http://staging.growstuff.org/posts/clockwerx-20160422-does-this-timestamp-correctly-on-the-front-page-or-stay-as-1-minute-forever#comments) - no reply controls available.

**Comment by maco** [comment]
The "Comment" button on the post page does what the "Reply" button on the index page does. However, I guess you do have to [scroll past a bajillion comments](http://growstuff.org/posts/skud-20130319-requests-for-new-crops) to reach that. Is that what this issue is trying to address?

**Comment by CloCkWeRX** [comment]
Ah hah, missed it because it was below the fold/differently named. +1 to adding a comment/reply link straight under the post

**Comment by cesy** [comment]
Okay, so we should add a second link so that it's obvious for people in both places.
