### ISSUE TITLE
Inconsistency: No way to navigate from seeds to a person's seeds in new card UI

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#873]
There's no way to get from http://staging.growstuff.org/seeds to http://staging.growstuff.org/seeds/clockwerx-coffee with the new card UI (you end up in the members profile link too easily).

**Comment by maco** [comment]
I'm inclined to simply replace the link to the member's profile with a link to the member's seed page.

**Comment by CloCkWeRX** [comment]
Yeah, and it becomes trivial to add an "Owner" link in the attributes bit of the card UI for the old link behaviour
