### ISSUE TITLE
Further improvement wanted: You can now search from the places index page

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#874]
http://staging.growstuff.org/places

![image](https://cloud.githubusercontent.com/assets/365751/18033053/4015f956-6d4b-11e6-916d-f50c0d9fa859.png)

You can search, but the placeholder text is misleading  - "New location" should be "Search for location" or similar.

Bonus points: An autocomplete wouldn't go astray either (but we can split this out to another issue if needed)

**Comment by Norman-Lee** [comment]
@CloCkWeRX Working on fixing this issue, first time contributor as well :)
