### ISSUE TITLE
Unclear: Posts and comments now show when they were edited, if they're edited - not on homepage

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#875]
We did work on showing when a comment/post was edited but missed the front page.

On the homepage created_date is still used. For example http://staging.growstuff.org/posts/clockwerx-20160402-dfd - homepage says 2nd, view says edited on 22nd.

Should either:
Update homepage partial to be COALESCE(updated_at, created_at) or render created + edited on the show.

**Comment by cesy** [comment]
I started looking at this and then got distracted by pre-requisites in my dev environment, so feel free to grab it if anyone else can get to it first.
