### ISSUE TITLE
Inconsistent: Photo view page now links back to the harvest or garden it is a photo of

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#876]
Depending on what it is a photo of you get different UI behaviour:

http://staging.growstuff.org/photos/124 This photo depicts lettuce in CloCkWeRX's garden
http://staging.growstuff.org/photos/127 This photo depicts "Example" (Why not CloCkWeRX's Example garden)

**Comment by maco** [comment]
It's happening this way:
```      %p This photo depicts:
      %ul
        - if @photo.plantings.size > 0
          - @photo.plantings.each do |p|
            %li= link_to p, p
        - if @photo.harvests.size > 0
          - @photo.harvests.each do |h|
            %li= link_to h, h
        - if @photo.gardens.size > 0
          - @photo.gardens.each do |g|
            %li= link_to g, g
```

and comes down to what `.to_s` does on each model.

``` def to_s
    self.crop_name + " in " + self.location
  end```

```  def to_s
    name
  end```

...and Harvest has a very long `.to_s` that renders something like `2 buckets of apricots, weighing 10kg`

Changing any of these would change how we link to things all over the site. Do you propose we special-case the Photo page's string?

**Comment by CloCkWeRX** [comment]
I don't think we should rely on the default .to_s; as its got such wide implications.

Why don't we swap this to be something like
```
Depicts:
  link_to thing, "A #{thing.model.name} by #{thing.owner}"
```
which should work across all equally well across Garden, Crop, Harvest, Seed, etc.

**Comment by maco** [comment]
In that case, I'll grab this and make sure to do it so it's i18n-friendly
