### ISSUE TITLE
Automatically assign reviewers

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#883]
Apparently Rust has an [automated system for greeting new contributors and assigning reviewers](http://huonw.github.io/blog/2015/03/rust-infrastructure-can-be-your-infrastructure/). We should look into setting this up for Growstuff, to ensure pull requests don't fall through the cracks.

I don't think the other bot described would be as useful to us, since our tests run pretty quickly.

**Edit**: here's where we've got to:
- [ ] Greeting new contributors
- [ ] Automatically assigning reviewers
- [X] Merge-on-green - welcome, @homu-gs! [Usage instructions here](http://mackenzie.morgan.name:54856/).
- [X] Allowing non-admins to claim issues - welcome, @claimbot-gs! [Usage instructions here](https://github.com/afuna/ghi-assist/blob/master/README.md)
- [ ] Document our new robot overlords in the new-contributors guide and/or README.
- [ ] Put something informative in the NROs' bios.

Three cheers for @maco for setting up and hosting the Homu and ghi-assist servers!

**Comment by cesy** [comment]
I like this.

**Comment by pozorvlak** [comment]
Scratch my last comment above: I've wanted the "merge when tests pass" bot half a dozen times in the last few days alone!

**Comment by pozorvlak** [comment]
Another good idea from @maco: a "dibs bot", so non-core contributors can assign issues to themselves.

**Comment by maco** [comment]
For dibs, Dreamwidth has a nice bit that lets you say "claim" "claimed" or
"claiming" anywhere in a comment ("I'm claiming this one") too self assign.
It also does label magic like marking new issues "untriaged" and things.

**Comment by pozorvlak** [comment]
- [Source of Dreamwidth's assignment-bot](https://github.com/afuna/ghi-assist)
 - [Documentation for it](http://wiki.dwscoalition.org/wiki/index.php/Github_Issues#Curating_Bugs)

**Comment by pozorvlak** [comment]
- [Instructions for Homu](https://github.com/barosl/homu#usage), the "merge on green" bot
- [Hosted Homu-as-a-service](http://homu.io/n/) - needs admin access to the repo being tested.

I want this more with every hour that passes.

**Comment by maco** [comment]
Years from now someone's going to have a laugh at this thread.

**Comment by maco** [comment]
I looked at that Homu as a service, and it's only set up for doing merges on master, but we use dev. So we'll have to self-host that one.

**Comment by pozorvlak** [comment]
@maco, awesome work on @claimbot-gs and @homu-gs! Do you also want to try setting up a [highfive](https://github.com/nrc/highfive) bot?

**Comment by maco** [comment]
I did do a little bit of documenting! There's an "our bots" page on the wiki. But we need, ya know, the *rest of the wiki*.

**Comment by maco** [comment]
Also, right now these are running in a screen session on my server. At some point I need to make them be an upstart service so that after reboot they turn back on automatically. But I don't reboot often.

**Comment by pozorvlak** [comment]
Yay!

Another option might be to host them on Heroku, so we can give admin access
to all the Growstuff maintainers.

**Comment by maco** [comment]
Oh, that's a point. I forgot how not-hard it is to throw something at
heroku, and simple stuff with little database is free

**Comment by pozorvlak** [comment]
@maco is @homu-gs still configured to merge things to master?

**Comment by maco** [comment]
I futzed with the code so it should do dev now. Maybe test that on a readme
change.

**Comment by Br3nda** [comment]
There's also : https://github.com/facebook/mention-bot

**Comment by Br3nda** [comment]
I propose i go ahead and hook up @mentionbot here.

**Comment by pozorvlak** [comment]
@Br3nda: go for it.

**Comment by Br3nda** [comment]
Done -- tested in #1234
