### ISSUE TITLE
Minor style regression? Bootstrap active navbar options 

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#896]
Might just be new laptop/display; but the style seems off when you select a top nav menu item:

![image](https://cloud.githubusercontent.com/assets/365751/15457754/a3b55fc0-20ce-11e6-81d5-ad42b29cc5c2.png)

Font color should probably be darker

**Comment by maco** [comment]
White on grey, yeah...that's...not a good thing.
