### ISSUE TITLE
Flaky CI builds

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#901]
https://travis-ci.org/Growstuff/growstuff/jobs/132256191#L1038 failed despite [the PR being merged having previously passed CI](https://travis-ci.org/Growstuff/growstuff/builds/132193909). I _really_ don't want to get into a situation where our CI is unreliable and we re-run builds until they pass.

Here's the relevant part of the logs:

> [!!!] Index does not exist (Elasticsearch::Transport::Transport::Errors::NotFound)
> .......F.................................WARN: tilt autoloading 'tilt/kramdown' in a non thread-safe way; explicit require 'tilt/kramdown' suggested.
> ..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/plantings/member1464-garden-magic-bean"]
> Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/plantings/member1464-garden-magic-bean-7d5f4ec1-26e4-4813-ad65-546692844d6d"]
> ...Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/harvests/member1469-magic-bean"]
> Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://localhost:8080/harvests/member1469-magic-bean-5fcc0ba8-db9c-4ec2-8511-a036582eac8d"]
> ..........................................................................................................................................**_..........................................................................................................................................................................................................................................._.....................Unused parameters passed to Capybara::Queries::SelectorQuery : ["http://en.wikipedia.org/wiki/Magic_bean"]
> ........................
> [snip]
> Failures:
>   1) Planting a crop Marking a planting as finished
>      Failure/Error: page.should have_selector('ul.ui-autocomplete li.ui-menu-item a')
>        expected to find css "ul.ui-autocomplete li.ui-menu-item a" but there were no matches
>      # ./spec/support/feature_helpers.rb:11:in `select_from_autocomplete'
>      # ./spec/features/plantings/planting_a_crop_spec.rb:186:in`block (2 levels) in <top (required)>'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in `load'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:63:in`kernel_load'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:24:in `run'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/lib/bundler/cli.rb:304:in`exec'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/exe/bundle:27:in`block in <top (required)>'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
>      # /home/travis/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.12.4/exe/bundle:19:in`<top (required)>'

**Comment by pozorvlak** [comment]
Here's the failing test:

```ruby
  scenario "Marking a planting as finished" do
    fill_autocomplete "crop", with: "mai"
    select_from_autocomplete "maize"
    within "form#new_planting" do
      fill_in "When?", with: "2014-07-01"
      check "Mark as finished"
      fill_in "Finished date", with: "2014-08-30"

      # Trigger click instead of using Capybara"s uncheck
      # because a date selection widget is overlapping_
      # the checkbox preventing interaction.
      find("#planting_finished").trigger 'click'
    end
```

It would make sense for the Elasticsearch error above to be related, but in that case why don't we see failures from all the other `select_from_autocomplete` tests?

**Comment by pozorvlak** [comment]
Also, we get [the same ElasticSearch error](https://travis-ci.org/Growstuff/growstuff/builds/132193909) on a successful build.

**Comment by CloCkWeRX** [comment]
We should potentially put in a check for 'service is up' into the tests, and if we suspect the error is temporary; simply retry.

For our ajax heavy ember app we tend to use matchers like:
```
  matcher :become_true do
    match do |block|
      begin
        Timeout.timeout(waiting_time) do
          until block.call do sleep(2); end
        end
        true
      rescue TimeoutError
        false
      end
    end

    supports_block_expectations
  end
```
to avoid unexpected failures bringing down a long running test suite.

Another alternative: build in retry/backoff with exponential wait into the ajax autocomplete (failure? Wait 1 sec.. .another ... 2 sec... another ... 4 sec, give up)

**Comment by maco** [comment]
And another...

<img width="852" alt="screen shot 2016-05-29 at 11 36 16 pm" src="https://cloud.githubusercontent.com/assets/401264/15639131/3d9c0126-25f6-11e6-9d69-c7cdb2dc9966.png">

**Comment by pozorvlak** [comment]
Maco's [first error](https://github.com/Growstuff/growstuff/issues/901#issuecomment-222280165) would fit the "ElasticSearch isn't coming up in time for the test to run" hypothesis, but her [second error](https://github.com/Growstuff/growstuff/issues/901#issuecomment-222405611) looks different. @maco, can you post links to the builds where these errors occurred?

**Comment by maco** [comment]
It was the "remove crowdfunding code" build. I restarted it, and I'm not
sure how to find the original failure again.

**Comment by pozorvlak** [comment]
Are we still getting random PhantomJS failures? I've found that replacing my system's PhantomJS with [the latest stable download](http://phantomjs.org/download.html) makes those go away on my own environment (including on Nitrous.io).

**Comment by pozorvlak** [comment]
[Cookbook for installing a recent PhantomJS on Travis](https://github.com/travis-ci/travis-cookbooks/commit/e38732d).

**Comment by pozorvlak** [comment]
Looking at our last few failed builds on the `dev` branch, I see

 - Four "Request to 'http://localhost:8081/foo' failed to reach server, check DNS and/or server status" errors: [1](https://travis-ci.org/Growstuff/growstuff/jobs/135901016#L2077) [2](https://travis-ci.org/Growstuff/growstuff/jobs/134443763#L1073) [3](https://travis-ci.org/Growstuff/growstuff/jobs/134739875#L2075) [4](https://travis-ci.org/Growstuff/growstuff/jobs/135026651#L2075) (all for different URLs).
 - One [Heroku timeout](https://travis-ci.org/Growstuff/growstuff/jobs/134467280#L1131).
 - One [expected to find css selector but there were no matches](https://travis-ci.org/Growstuff/growstuff/jobs/134467280#L1131) error, which passed on re-running.
 - One [failed to commit Gemfile.lock](https://travis-ci.org/Growstuff/growstuff/jobs/132343462#L182) error, which is legit but which we should really have caught in the PR build - it looks like we're using a different `bundle install` line for [branches](https://travis-ci.org/Growstuff/growstuff/jobs/132343462#L181) and [PRs](https://travis-ci.org/Growstuff/growstuff/jobs/132331819#L181). I guess we could add a dumb check for "you committed Gemfile XOR Gemfile.lock"? That would catch this specific problem, but possibly not others.

**Comment by pozorvlak** [comment]
A [random PhantomJS client death](https://travis-ci.org/Growstuff/growstuff/jobs/136173245#L2088) seen in the wild!

**Comment by pozorvlak** [comment]
Determining how old Travis' version of PhantomJS is: #978.

**Comment by pozorvlak** [comment]
Stack trace:

```
     # ./spec/features/crops/crop_wranglers_spec.rb:62:in `block (3 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /home/travis/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
```

And actually, https://c.tiles.mapbox.com/v3/0/2/1/1.png is returning `{"message":"Not Found"}` for me - I wonder if their API has changed? :-(

**Comment by pozorvlak** [comment]
I left tcpdump running during a test-suite run yesterday, and found a bunch of HTTP requests to www.gravatar.com (but none to mapbox.com, oddly).

**Comment by CloCkWeRX** [comment]
Hitting the member page defaults to hitting gravatar (spec/features/member_profile_spec.rb). 

Do we want to cheat and make sure all but one of these are under VCR or faked?

**Comment by pozorvlak** [comment]
Something like that, definitely. Our CI should be repeatable, which means
it shouldn't depend on anything that's not controlled by the code under
test, so "is #{service we don't control} available and fast at #{time the
test is being run}?" is Right Out.

**Comment by pozorvlak** [comment]
More localhost:8081 errors: http://imgur.com/a/fyxiL

**Comment by maco** [comment]
I think we can declare this closed?

**Comment by CloCkWeRX** [comment]
+1

**Comment by pozorvlak** [comment]
\o/

**Comment by Br3nda** [comment]
Ah, I'm still getting some failures money of the 2 jobs will fail, and I'll go tell it to run again. If you're not getting these it's because I'm restarting them.

**Comment by Br3nda** [comment]
Next time it fails, I'll copy the message here.

**Comment by Br3nda** [comment]
> Failures:
>   1) account types admin user adding an account type
>      Failure/Error: expect(current_path).to eq account_type_path(AccountType.last)
>       expected: "/account_types/2"
>             got: "/account_types/new"
>        (compared using ==)
>      # ./spec/features/admin/account_types_spec.rb:37:in `block (3 levels) in <top (required)>'

just happened on one job, but not the other. 
Passed when i re-rant

**Comment by pozorvlak** [comment]
From #1201:

```
Failures:
  1) forums as an admin user adding a forum
     Failure/Error: expect(current_path).to eq forum_path(Forum.last)
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"forums", :id=>nil} missing required keys: [:id]
     # ./spec/features/admin/forums_spec.rb:42:in `block (3 levels) in <top (required)>'
```

Passed when I re-ran the Travis job.
