### ISSUE TITLE
Automatically detect HAML errors

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#902]
Now that we've eliminated controller tests, it's possible for a simple HAML syntax error to make it through the test suite because the relevant feature test says "oh yes, the string I'm looking for is present in the error page, everything's fine here". This is annoying. We could add controller tests back, but a lighter-weight alternative could be to add a static HAML-checking pass to our test suite, possibly using [haml-lint](https://github.com/brigade/haml-lint).

**Comment by pozorvlak** [comment]
In general, I'm in favour of adding as much static analysis and checking as possible.

**Comment by maco** [comment]
regarding static analysis... https://docs.codeclimate.com/docs/scss-lint

**Comment by maco** [comment]
Wait, better link: https://docs.codeclimate.com/docs/list-of-engines

**Comment by pozorvlak** [comment]
Oh, cool! So possibly a better approach would be to try integrating
haml-lint with Code Climate...

**Comment by maco** [comment]
There doesn't seem to be a haml-lint plugin for Code Climate yet. Brakeman (security static analyzer) can heck haml as far as security goes, but I don't know if it does what you need for this issue.

I _do_ wonder how hard it'd be to make something that goes on Code Climate's "community-maintained engines" list, though, given haml-lint already exists.

**Comment by pozorvlak** [comment]
It turns out that haml-lint does report syntax errors:

```
miles@bashful:~/src/growstuff 17:31  pr/948 
65 $ haml-lint app/views/posts/_summary.html.haml 
app/views/posts/_summary.html.haml:18 [E] Illegal nesting: nesting within plain text is illegal.
```

Unfortunately it also reports several thousand trivial warnings, and I can't see any way of only reporting errors. I'm fixing the warnings over in #930.

**Comment by Br3nda** [comment]
This is fixed by haml-lint being in travis now
