### ISSUE TITLE
Mark as finished does weird stretchy thing from member plantings page

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#906]
Calendar popped up. Instead of clicking "confirm without date" I just clicked elsewhere on the page to dismiss the calendar. And then this happened.
<img width="846" alt="screen shot 2016-05-24 at 5 31 38 pm" src="https://cloud.githubusercontent.com/assets/401264/15520664/75286c94-21d5-11e6-9ab1-36ac81b54810.png">

**Comment by CloCkWeRX** [comment]
Related #847
