### ISSUE TITLE
Weird wrapping of plantings on member page

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#908]
The first planting has "Quantity: not specified" while the second has "Quantity: 32". The "not specified" is getting line-wrapped so it's two lines long. Consequently the first planting is 1 line of text taller than the second planting.

So the third planting floats around that first planting and lines up under the second planting. And finally, the fourth planting, having enough room on the left after it gets knocked off row 2 by the third planting, lines up on the left.

<img width="1005" alt="screen shot 2016-05-24 at 5 50 33 pm" src="https://cloud.githubusercontent.com/assets/401264/15521131/149e7834-21d8-11e6-904e-4456861137f3.png">

**Comment by CloCkWeRX** [comment]
Should be fixed with the planting card UI tweaks in #898 - check staging

**Comment by maco** [comment]
Ah ok, yep, text's not wrapping and knocking things over anymore
