### ISSUE TITLE
Sidebar on Member page overlaps Planting cards

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#913]
<img width="1174" alt="screen shot 2016-05-25 at 3 36 43 pm" src="https://cloud.githubusercontent.com/assets/401264/15553859/2ba77ff0-228f-11e6-9d7d-ce6e9c8bd0e0.png">

The DOM structure is:

```
%div.col-md-9
  %div.tabbable
    %div.tab-content
      %div.tab-pane.active
        %div.container
%div.col-md-3
```

Here's the trouble: that `%div.container`? That's 12 columns wide. 

We can't just move the entire `%div.tabbable` down, though, because then we'd get:

<img width="1195" alt="screen shot 2016-05-25 at 3 51 03 pm" src="https://cloud.githubusercontent.com/assets/401264/15554123/882a670a-2290-11e6-9cce-8de9dcf1c140.png">

So, we need to decide how we're rearranging things.

**Comment by CloCkWeRX** [comment]
Does it resize happily with us setting the .container to span10?

**Comment by CloCkWeRX** [comment]
![image](https://cloud.githubusercontent.com/assets/365751/15564011/05f40a94-234d-11e6-8316-2a616e7bb16e.png)

font-size: 85%;
activity list gets the list-inline class

We can maybe trim one or two extra headings as needed as well

**Comment by maco** [comment]
Oh, just realized this only happens if you don't have a location set. On http://staging.growstuff.org/members/niftygrifty the map pushes everything below the sidebar, but on http://staging.growstuff.org/members/maco there's no map, so there's overlap.

Anyway, setting `.col-md-10` on `.container` results in this:

![screen shot 2016-05-26 at 12 52 00 am](https://cloud.githubusercontent.com/assets/401264/15564066/2a4e4f60-22dc-11e6-99f1-93c403a30a13.png)

**Comment by maco** [comment]
A map or globe with a ? in place of the real map could work to push things down and indicate "hey, you haven't set your location yet!"  (The silly side of me says a picture of Carmen Sandiego)

**Comment by pozorvlak** [comment]
Good idea! I think a map/globe would be more universally understood.​

**Comment by Br3nda** [comment]
Looks fixed now
