### ISSUE TITLE
Anything that sends emails results in Error 500

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#917]
We can't send notifications, and *we can't sign up new users*.

This is because the standalone Mandrill shut down. Either we have to go to using the paid MailChimp/Mandrill feature, or we need a new service. [SparkPost](https://www.sparkpost.com/mandrill-migration-guide) looks promising as a free for low volume service. I've linked the migration guide.

We really should try to get this into Release 11 because not being able to sign up new users is a serious problem.

**Comment by CloCkWeRX** [comment]
> On April 27, Mandrill became a paid MailChimp add-on. More information about this transition is in this blog post. 
> $20/block for 1-500k emails

I imagine that volume would last us a while; and if its just a matter of adding an API token or something I'd be happy to cough up the $ for it; so we have a bit of time with migrating

**Comment by maco** [comment]
More generally there's a "admin access to MailChimp" problem at the moment.
But we couldn't switch to another service without updating the SPF records
in DNS without running into another admin access snag, either. Wheels are
turning regarding credentials for the services we use, though, so soon. I
wanted to get it "on the list" though for hopefully this release, maybe
next. Don't want it falling through the cracks or anything.

**Comment by cesy** [comment]
Yeah, I'd suggest we pay for a month of MailChimp to give us breathing room, then migrate to SparkPost once things are a bit more stable.

**Comment by maco** [comment]
Ok, I have the needed access to make the Mandrill/MailChimp changes, so I'll work on that tomorrow when it's supposed to be a horrible thunderstorm of "heck no, I'm not going to archery practice."

**Comment by CloCkWeRX** [comment]
Did we manage to sort this one out? I can't remember.

**Comment by maco** [comment]
Yes, this works now
