### ISSUE TITLE
Unknown error after creating a minimal seed

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#920]
http://staging.growstuff.org/crops/lettuce currently shows "We're sorry, but something went wrong." after I created http://staging.growstuff.org/seeds/clockwerx-lettuce

I suspect some kind of formatting mishap

**Comment by maco** [comment]
It's loading just fine for me. Hmm.

**Comment by CloCkWeRX** [comment]
Can we see if anything crops up in newrelic?

**Comment by maco** [comment]
Uh.... @pozorvlak? I don't have access to newrelic.

**Comment by cesy** [comment]
I have access as well - Maco, can you follow the link from Heroku? Happy to do a screenshare over Hangouts or Skype if it helps. I can't see Clockwerx's error, as it apparently only keeps them for half an hour on staging, and that page loads fine for me.

**Comment by maco** [comment]
Oh, it's a thing in Heroku. Well, I'm out of town today for a living
history event and tomorrow for a wedding, so I'll try that Monday.

I have seen a few other times staging has tripped in ways I haven't seen
production do. Can't remember exactly what though. Maybe a finished
planting?

**Comment by cesy** [comment]
Seeds/lettuce gave this error on Show:
ActiveRecord::RecordNotFound
…ms/friendly_id-5.0.5/lib/friendly_id/
finder_methods.rb:  23:in `find'
…n-1.14.0/lib/cancan/model_adapters/
abstract_adapter.rb:  20:in `find'
…ems/cancancan-1.14.0/lib/cancan/
controller_resource.rb: 111:in `find_resource'
…ems/cancancan-1.14.0/lib/cancan/controller_resource.rb:  63:in `load_resource_instance'
…ems/cancancan-1.14.0/lib/cancan/controller_resource.rb:  32:in `load_resource'
…ems/cancancan-1.14.0/lib/cancan/
controller_resource.rb:  25:in `load_and_authorize_resource'
…ems/cancancan-1.14.0/lib/cancan/controller_resource.rb:  10:in `block in add_before_filter'

Crops/lettuce gave this error on Show:
ActionView::Template::Error: nil can't be coerced into Fixnum
/app/app/helpers/
crops_helper.rb:   6:in `block in display_seed_availability' 
/app/app/helpers/
crops_helper.rb:   4:in `display_seed_availability'

**Comment by cesy** [comment]
I think that helper line 6 may need a catch for if the seed.quantity hasn't been specified, assume it is 1, or something like that?

**Comment by CloCkWeRX** [comment]
ignore the seeds/lettuce one, that was me stuffing about with URLs
