### ISSUE TITLE
Planting card buttons look weird

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#929]
<img width="351" alt="screen shot 2016-05-27 at 10 09 00 am" src="https://cloud.githubusercontent.com/assets/401264/15610415/1eedaacc-23f3-11e6-9e1d-3b7da7b99bbe.png">
It's `text-align: right` with a button that's bigger than the space it's been given.

<img width="183" alt="screen shot 2016-05-27 at 1 02 51 pm" src="https://cloud.githubusercontent.com/assets/401264/15615295/721186f2-240b-11e6-9c13-15f8a3ee91d1.png">

**Comment by maco** [comment]
This *might* be as simple as changing from `col-md-2` to `col-md-3` (or similar) on the `ul` or the element  that holds it.

**Comment by CloCkWeRX** [comment]
Relabelling it to "Done" and a title attribute of 'mark as finished' might do the trick, or maybe some other placement.

![image](https://cloud.githubusercontent.com/assets/365751/15623286/2eaa641e-24b1-11e6-97e5-4448e4976345.png)

**Comment by Br3nda** [comment]
fixed a while ago
