### ISSUE TITLE
Member page garden overview should better differentiate (or even hide) finished plantings

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#940]
http://growstuff.org/members/clockwerx

![image](https://cloud.githubusercontent.com/assets/365751/15711745/8a488d46-284e-11e6-87da-a8d22cdcb537.png)

Compare that to
http://growstuff.org/gardens/clockwerx-garden

Which at least has a "Previously planted in this garden" heading to split things out.

![image](https://cloud.githubusercontent.com/assets/365751/15711788/c49f87b0-284e-11e6-802c-1722e5e1d2f4.png)

Given this is meant to really only be a 'quick overview'; maybe we should omit finished plantings (or only show them if there are no active plantings)

**Comment by maco** [comment]
I vote omit. I've found it odd to look at too

**Comment by maco** [comment]
claiming

(we'll see if the bot notices)

**Comment by maco** [comment]
trying again...

claiming

**Comment by maco** [comment]
claiming

**Comment by maco** [comment]
one more go...

claiming

**Comment by Br3nda** [comment]
This was done a while ago :-)
