### ISSUE TITLE
Homepage 'recently planted' is a bit too cache-y

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#941]
http://growstuff.org/plantings - shows plantings May 29th 2016

http://growstuff.org/ - shows 'recent plantings' that never seem to update.

**Comment by CloCkWeRX** [comment]
```
  .col-md-4.hidden-xs
    - cache cache_key_for(Planting) do
      %h2= t('.recently_planted')
      = render :partial => 'plantings/list', :locals => { :plantings => Planting.interesting.first(6) }
```
I think because we never set an expiry, depending on the store, it may persist Forever.

**Comment by maco** [comment]
Yipes

**Comment by cesy** [comment]
Ah, I'd assumed it was just because most of the recent ones don't count as interesting because they don't have photos.

**Comment by Br3nda** [comment]
I don't think this is an issue anymore
