### ISSUE TITLE
Seeds available for trade shows me seeds I cannot trade for

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#946]
http://growstuff.org/ -> "Seeds available for trade" lists a number of trades, all of which are 'local trade only', but are on another continent (Australia vs America).

For a logged in member with a location set, we should prefer showing seed trades (local) near their location (we already do this on the places page, though there appear to be a few bugs there as well).

IE:
http://growstuff.org/places/Adelaide shows 3x crops/seeds available for trade (but not the actual seed-trades themselves - we should maybe make the same UI as the frontpage appear here)

**Comment by maco** [comment]
This sounds like we need to factor a partial out of what's on the places page and use it. Discrepancies like this mean (poorly) duplicated code.
