### ISSUE TITLE
Branded error pages

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#950]
Add Growstuff branding to the error pages currently in /public, particularly the Error 500 and 404 ones.

Include links back to the homepage, or ideally the whole standard header and footer. This can be done by copying the code from app/views/layout or app/views/home. You'll need to spell it out in full instead of just using HAML, because the error pages are used when Rails isn't fully working.

**Comment by Prashanth261993** [comment]
Hi, I would like to work on this one. This is my first contribution, so if you could hep me with how to change its assignee, that would be great. Thanks!

**Comment by maco** [comment]
Github is silly and prevents people from assigning, even to themself,
unless they already have commit (I think?) access. In the next week or so,
I'll have a bot setup to make it possible, but in the meanwhile, your
comment here is your claim.

**Comment by Prashanth261993** [comment]
Oh thanks a lot. I'm unable to signup though. The confirmation seems to be redirecting to localhost:8080. I am guessing its a staging or production server. Is there a password for one of these members : test1, admin1?

**Comment by maco** [comment]
Ah, yes, the password for test1 is password1 and for test2 is password2
etc. Similarly, wrangler1's password is wrangler1, and admin1's password is
password1

For future reference, if you look in db/seeds.rb you can search for a
username that's in the test db and find its password.

**Comment by Prashanth261993** [comment]
The header and footer use bootstrap-css and bootstrap-sprockets. Is there an easy way to integrate them to files under public folder?

If not, which of the following should be done:
  i) Write custom css, js under <style> and <script> respectively
  ii) Do something similar to : [http://stackoverflow.com/questions/24235805/rails-4-how-do-i-create-a-custom-404-page-that-uses-the-asset-pipeline]

**Comment by Prashanth261993** [comment]
Thanks @pozorvlak . Will definitely try.

Could you also please explain what cms_snippet_content(:footer1) does? 
It is part of _footer.html.haml.

It seems to be populating content in production but nothing under development. I can't find any code that initializes the content.

**Comment by maco** [comment]
We have a CMS (content management system) called Comfy Mexican Sofa in use.
The footer content is stored in the DB and configured using the web
browser. I wouldn't worry about having much in the way of footer and all,
just making it matching in terms of color, font, etc.

**Comment by Prashanth261993** [comment]
Hi, I have fixed the issue. I created a new branch, committed my changes and then merged dev into my branch. But when I try to push it, permission is denied.

**Comment by Prashanth261993** [comment]
Also I'm relatively new to haml. I'm unable to change the title of the page for now. If I use content_for :title, along with the html title the application.html also yields :title under maincontainer.

How do I change only the title of the browser without it being yeid under application.html?

**Comment by maco** [comment]
Do not push it to upstream/dev. Push it to your fork, on its own branch. If
your fork is cloned as "origin" then you'd do:

git push origin branded_error_pages

If you cloned directly from here, not from a fork, go do the fork, then
you'll need to add a new remote to git, like:

git remote add me git@github.com/prashanth261993/growstuff.git

And push to that.

After you push to your fork, when you visit the front page of the upstream
growstuff repo, you'll see a little thing going "you just pushed. Do you
want to make a pull request?" Follow that.

**Comment by Prashanth261993** [comment]
@maco Thank you so much. That really helped.

**Comment by Prashanth261993** [comment]
@maco Any idea about resolving the :title issue commented above? Also, Is there any particular forum where doubts regarding coding can be asked?

**Comment by arealdeadone** [comment]
Is this issue still **open** so that I can contribute?

**Comment by pozorvlak** [comment]
@arealdeadone it's still open, but assigned to @Prashanth261993  - please discuss with them about collaborating on it or taking it over.

**Comment by arealdeadone** [comment]
@pozorvlak thanks I will surely do that!

**Comment by maco** [comment]
@arealdeadone @Prashanth261993 either of you still around and interested in picking this back up?

**Comment by vbrazo** [comment]
@maco it seems they are not. I could take a look at this issue if you allow me to do that.

**Comment by maco** [comment]
Sure, go ahead

**Comment by meganft** [comment]
@maco has this been addressed?

**Comment by maco** [comment]
Nope. You wanna grab it?

**Comment by meganft** [comment]
Sure!
