### ISSUE TITLE
Queue and manage emails better

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#951]
Ideally, if the email server goes down or is unavailable, you should still be able to post the comment or whatever you were doing, and the notification should be stored to retry later. We could look at something like resque_mailer or delayed_job.

**Comment by maco** [comment]
## curated: railsy

(we'll see if that bot is working)

**Comment by maco** [comment]
## curated: railsy

**Comment by CloCkWeRX** [comment]
This might be as simple as ```Notifier.notify(self).deliver_now``` swapping to ```Notifier.notify(self).deliver_later```

http://edgeapi.rubyonrails.org/classes/ActionMailer/MessageDelivery.html#method-i-deliver_later

https://blog.codeship.com/how-to-use-rails-active-job/

I have a lot of love for sidekiq (and the associated sidekiq web ui etc); though its a pain in the behind to restart it without ssh access if it falls over.
It will definitely fall over at some point.

**Comment by cesy** [comment]
Do we have any ideas on how to get it restarted? That will be an issue on heroku.
