### ISSUE TITLE
Enable one-click setup of developer environments

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#958]
Setting up development environments is annoying and fiddly, it's easy to forget to document changes to the process, and it's the first activity any new developer has to go through: problems here will disproportionately cost us potential new contributors.

The obvious approach is to package our development environment using virtual machines (Vagrant) or Linux containers (Docker). In theory, this would make setup of a new developer environment as easy as
1. Download and install the VM/container manager.
2. Run "$tool up".
3. Go and get a coffee, or a four-course meal if you're in a place with slow Internet.

Upsides: I for one am sick of setting up environments manually every time I change machines (most of my personal machines are old and/or second-hand, and they're constantly breaking). Fewer problems related to developers' idiosyncratic environments. Easier migration off Heroku, should we choose to do that. Hopefully more drive-by contributors. Setup documentation becomes less brittle.

Downsides: it increases the amount that a new developer will have to download (~1GB for a VM, ~200MB for a container). VMs are slow. More toolchain complexity. Actually automating setup keeps turning out to be harder than I expect.

I know of at least three attempts along these lines:
- [Skud's "vagrant" branch](/skud/growstuff/vagrant). Uses Vagrant and Virtualbox for VMs and Puppet for configuration. Stalled.
- [My "vagrant2" branch](/pozorvlak/growstuff/vagrant2). Uses Vagrant, Virtualbox and shell. Installs RVM inside the VM to ensure we get the correct version of Ruby. PhantomJS keeps crashing, possibly just because it's a really old version? Should probably be abandoned.
- [My work-in-progress Docker branch](https://github.com/Growstuff/growstuff/pull/957). I can use this to create and run a Growstuff instance in a container, but I can't yet run the full test suite.

**Edit**: a possible alternative (at least for those with reliable internet connections) might be Nitrous Quickstarts, documented at https://community.nitrous.io/docs/nitrous-quickstarts. I've updated the title of this issue accordingly.

**Further edit**: a ["deploy to Heroku" button](https://devcenter.heroku.com/articles/heroku-button) might be pretty cool too. I'm thinking of quickly spinning up a server for manual testing of pull requests.

**Comment by pozorvlak** [comment]
Copying over some comments from #957:

In my last job, we had two "setup environment" processes, and skew between the two was a constant nightmare - people using the old setup kept unwittingly breaking the new one, which meant that the new setup was constantly playing catch-up and could never quite take over. So (assuming we get this to work!) I think we should aim to have a clean switchover if possible, rather than trying to maintain "automated environment setup" and "manual environment setup" as equal first-class citizens.

[Fully-native Docker for Windows/Mac](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) is still in beta, but Docker Toolbox appears to be non-beta on both [Windows](https://docs.docker.com/engine/installation/windows/) and [OS X](https://docs.docker.com/mac/step_one/). That runs Docker in a tiny Linux VM, though, so developers on OS X and Windows would have to suffer virtualization overhead. OTOH, our current suggestion for Windows is "develop in a Linux VM".

**Comment by pozorvlak** [comment]
On the subject of "limiting the amount new users have to download", we're currently installing nearly half a gigabyte of gems!

```
$ du -h --max-depth=0 ruby-2.2.4\@growstuffdev/
480M	ruby-2.2.4@growstuffdev/
```

**Comment by pozorvlak** [comment]
The "please let's not have two first-class dev-env setup processes" argument should probably apply to Docker/Nitrous and Vagrant/Nitrous too. Hrm.

**Comment by CloCkWeRX** [comment]
I think this is achieved "enough" with codespaces.
It's got problems.
For some reason, you can't stay logged in when running the app there.
Elasticsearch eats too much memory.
But can you run rspec and write code? Yes.
