### ISSUE TITLE
Update to Mapbox API v4

### ISSUE THREAD

**Issue by pozorvlak** [Growstuff/growstuff#981]
We appear to be using the [deprecated v3 API](https://c.tiles.mapbox.com/v3/0/2/1/1.png), and this [may be causing build failures](https://github.com/Growstuff/growstuff/pull/980), though maps are rendering fine on staging.

**Comment by CloCkWeRX** [comment]
This is easy enough to do but then requires an access token -
https://www.mapbox.com/help/define-access-token/

I can fork the style, but it would be better if we generated a proper token and added it. I think we could also trial vector maps
