### ISSUE TITLE
If a harvest has a photo, it should be displayed instead of crop photo

### ISSUE THREAD

**Issue by maco** [Growstuff/growstuff#997]
On my harvests page, my sweet potato harvest displays like this:
<img width="580" alt="screen shot 2016-06-19 at 8 18 14 pm" src="https://cloud.githubusercontent.com/assets/401264/16180693/0fe50f96-365b-11e6-9df5-b482da3b1c04.png">

I thought I must not have attached a photo of that harvest when I made it, but I did! 

<img width="1163" alt="screen shot 2016-06-19 at 8 18 23 pm" src="https://cloud.githubusercontent.com/assets/401264/16180694/0fe53002-365b-11e6-9e0a-2b6c11ef13eb.png">

On the harvest index pages, it should first look for a photo attached to the harvest then *fall back* to a crop photo if none is found.

**Comment by CloCkWeRX** [comment]
Not even too tricky.

```
        = link_to image_tag((harvest.crop.default_photo ?  harvest.crop.default_photo.thumbnail_url : 'placeholder_150.png'), :alt => harvest.crop.name, :class => 'img'), harvest.crop
```
turns into something like
```
        - image = harvest.photos.first || harvest.crop.default_photo || 'placeholder_150.png'
        = link_to image_tag(image, :alt => harvest.crop.name, :class => 'img'), harvest.crop
```

**Comment by pozorvlak** [comment]
Looks sensible, though I'd slightly prefer it if the "find appropriate
image" logic were in a helper, or maybe a method on the model object.
