### ISSUE TITLE
Mark as finished from garden list gets the wrong plant

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#998]
Something is wrong with the marking as finished. I tried to mark my basil as finished and it updated the parsley instead. If I go into the basil entry to edit it, it's fine, but going from the list of plantings in the garden is broken.

Maco wonders if she broke that when fixing the "the button replicates itself as many times as there are buttons" bug (#906 / 03c74dae03a5e4199a435d289046bad8b94eacb2). It should've only been the text getting captured that she changed there though...but that's the last change to the finished button, so it's suspect.

**Comment by CloCkWeRX** [comment]
I don't think it's @maco introducing regression, but a very similar bug to the original text problem.

It boils down to doing
```
  el = $('.append-date')
  href = el.attr('href')
```
when it should be 
```
  href = el.attr('href')

  el.click (e) ->
    originalText = $(this).text()
    href = $(this).attr('href')
```
otherwise it'll get the href of the last item in the collection presumably.
